### ISSUE TITLE
WP-CLI Staging PHP errors

### ISSUE THREAD

**Issue by crstauf** [versionpress/support#1]
When attempting to create a staging site using the `wp vp clone --name=staging` command, I received PHP errors displayed within the terminal:

https://cloudup.com/cNOEAv8ruO5
![image](https://cloud.githubusercontent.com/assets/101152/11299797/fa95bfe6-8f89-11e5-9777-833f328716ca.png)

I sent the screenshot to @borekb via email, and he provided me with an updated build. After running a similar command (`wp vp clone --name=vp-staging`), I received the following output: 

https://cloudup.com/iOAQfLO-9KI
![image](https://cloud.githubusercontent.com/assets/101152/11299812/251d57b0-8f8a-11e5-8275-7635329e5468.png)

During this second attempt, VP indicated it had completed with errors, so I decided to try and install WordPress; I then saw these errors on the install screen:

https://cloudup.com/i-M89aFdIa0
![image](https://cloud.githubusercontent.com/assets/101152/11299828/3e39e18c-8f8a-11e5-9cc6-90feabfe1e71.png)

(These errors are interesting since there is no `wp_categories` table in the original site.)

@borekb then asked me to run the command again, dumping the contents of the `$entity` var in the `flattenEntity` function, which led to the following output:

http://pastebin.com/FbZRZXDe

Is anyone else experiencing a similar issue when using the WP-CLI to create a staging site?

(I am running VP on a very clean install of WordPress; no more than five plugins, default content, default theme.)

**Comment by borekb** [comment]
From the info provided, it's not entirely clear to us what could be causing this. Could you please ZIP up the whole site, incl. `.git` and a MySQL dump, so that we could try to reproduce it here? Thanks.

**Comment by crstauf** [comment]
Zip file of WordPress install, with sql file.
https://drive.google.com/file/d/0B3zlAD3FXu0eZkQtRzkzcHcwNE0/view?usp=sharing

**Comment by borekb** [comment]
Thanks for that. After looking at the Git history, it looks like the site was created even before VersionPress 1.0 and was not properly upgraded to the current VP release (2.1) which left it in a weird and unsupported state.

Would you be able to reproduce the issue if you installed current VersionPress onto a fresh installation of WordPress? Thanks.

**Comment by crstauf** [comment]
I thought there might've been a prescribed upgrade process, but did not see any mention of it, so just replaced the current version. Will install a fresh WP and try it there.

**Comment by borekb** [comment]
Sorry it's not very smooth at the moment as we don't have an automated upgrade process yet (still some moving parts between EAP releases..) - upgrade steps are always described in the [release notes](http://docs.versionpress.net/en/getting-started/installation-uninstallation#update--upgrade).

Let us know how the clear install goes.

**Comment by crstauf** [comment]
Ok so starting with a fresh WP and VP install, running `wp vp clone --name=vp-staging` worked very well. I did receive the following notices inside of Terminal:

```
Notice: Constant VERSIONPRESS_PLUGIN_DIR already defined in /Applications/XAMPP/xamppfiles/htdocs/vp-staging/wp-content/plugins/versionpress/bootstrap.php on line 8

Notice: Constant VERSIONPRESS_MIRRORING_DIR already defined in /Applications/XAMPP/xamppfiles/htdocs/vp-staging/wp-content/plugins/versionpress/bootstrap.php on line 9

Notice: Constant VERSIONPRESS_TEMP_DIR already defined in /Applications/XAMPP/xamppfiles/htdocs/vp-staging/wp-content/plugins/versionpress/bootstrap.php on line 10

Notice: Constant VERSIONPRESS_ACTIVATION_FILE already defined in /Applications/XAMPP/xamppfiles/htdocs/vp-staging/wp-content/plugins/versionpress/bootstrap.php on line 11
```

(Terminal screenshot: https://cloudup.com/cTDav5AaeVm)

There do not appear to be any issues with either install at this point. I am closing this issue, and will test out merging between the two installs and see how that goes.

Thanks for your fantastic support and time, @borekb!

P.S. I understand the lack of an automated upgrade process at this time. Very excited to be apart of VP's development and growing pains. ;-)

**Comment by borekb** [comment]
Thank you, we will look into that notice, it shouldn't be happening.
