### ISSUE TITLE
Missing wp_json_encode

### ISSUE THREAD

**Issue by 650hours** [versionpress/support#10]
Seeing this error in the log files on a v4.0.1 site which I'd prefer to install VersionPress onto prior to upgrading. Any suggestions?

PHP Fatal error:  Call to undefined function VersionPress\\Api\\BundledWpApi\\wp_json_encode() in /var/www/__SITE__/wp-content/plugins/versionpress/src/Api/BundledWpApi/lib/infrastructure/class-wp-rest-server.php on line 182, referer: http://__SITE__/wp-admin/admin.php?page=versionpress

**Comment by pavelevap** [comment]
Hi, latest VersionPress 2.2 does not work on WordPress 4.0.x, as noted in [system requirements](http://docs.versionpress.net/en/release-notes/2.2#system-requirements). We thought it might work on 3.9+ but there's no [wp_json_encode()](https://developer.wordpress.org/reference/functions/wp_json_encode/) function before WordPress 4.1 which is required by VersionPress 2.2.

I would suggest to make standard backup (files and database) and upgrade at least up to WordPress 4.1.x and then start using VersionPress.
