### ISSUE TITLE
Remote workflow considerations

### ISSUE THREAD

**Issue by bluepresley** [versionpress/support#100]
Hello,

I'm not sure I fully grasp some of the concepts behind VP's workflow capabilities.

I'm following the workflows as discussed here, namely Example 1: Teamwork via GitHub.  https://blog.versionpress.net/2016/11/remote-workflows/

This most closely resembles my current situation. I am a developer in America while I have two other contributing developers in Japan and South Africa.  

Ok, so I get through step 3 with no problem. Git is initiated, and files are uploaded to a _**private**_ repository. "Jane" and everyone has run 'git clone address.git' and has a copy on their server.

Step 4) is where I'm having some real issues. "Jane" runs wp vp restore-site. Unfortunately, nothing magical happens here like in the example. In fact, I get an error:

Error: wp-config.php not found. 

After quite a bit of searching, I come across the doc's wp-cli explanation of wp vp restore-site which says I have to run through 4 steps before I can issue the command with --site-url and --require arguments. Ok, I get that, but I have questions about the 4 steps.

_1) Manually put VersionPress into to wp-content/plugins/versionpress folder._
Where should I get this from? Copy it from the site I'm cloning? Or can I just install a fresh version of the plugin from github?

_2) Run wp core config from the site root to setup the database._
Here is what I get when I run that:
Error: Parameter errors:
 missing --dbname parameter (Set the database name.)
 missing --dbuser parameter (Set the database user.)

What should I name these? What do I populate the db with to get started?

_3) Run wp vp restore-site with siteurl and require parameters._

My theory is, if I run 2) as a simple wp-cli command, then I get an empty database, or wp core default database. so, install a fresh version of versionpress and I run:

wp core config --dbname=testrestore --dbpass --dbroot ; wp db create

wp vp restore-site --arguments
Error: Can’t select database. We were able to connect to the database server (which means your username and password is okay) but not able to select the `testrestore` database.

4) Enjoy your up and running site.
I never made it here

So this is where I'm at a loss. Based on that example in Remote Workflows, In step 5) Jane "_makes some changes, e.g., changes the site title, chooses a different theme and updates it a bit. Her Git repo contains new commits and she pushes them to GitHub_"

Those are database changes, and implies that when she pushes things back to the central repository "something" has to go with it that let's "john" know he has to manage db conflicts before he can up his changes.

What data has to be passed to or stored on the central repository so that remote developers are 1) able to pull down a working copy of the database and 2) are able to merge database changes / resolve conflicts across remove collaborative environments? Wouldn't I have to have a copy of the db dump.sql as well as all versionpress files to make this happen (which aren't tracked by default)?

There seems to be a huge gap between step 3) and step 4) in that workflow, right?

- VersionPress version:  4.0-beta
- WordPress version: 4.8
- OS, webserver, PHP: Ubuntu 16.04
- Git version: 2.7

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by borekb** [comment]
Hi @bluepresley, sorry that the step 4 isn't documented better. I've at least put an explicit link to the documentation there for now.

Generally, after you get beyond step 4, all should start working fine. VersionPress automatically tracks database changes and stores them in the Git repo, and the command `wp vp pull` makes sure the database is updated on the machine where "pull" is executed. 

Some quick notes to your struggles with `wp vp restore-site`:

1) Yes, it can be the version from GitHub, or a copy from your other environment, this doesn't really matter. (We will automate this step in the future.)
2) This is a non-VersionPress `wp core config` command and you can find its documentation [here](https://developer.wordpress.org/cli/commands/config/). You can name your DB any way you want (the generated `wp-config.php` is Gitignored and completely local).
3) You probably found a gap in our documentation, yes the database should already exist. (I'm not sure off top of my head whether WP-CLI tries to created it or not but it's a safe bet to just create it manually.)

Thanks for your detailed report, let us know how you get on.

**Comment by JanVoracek** [comment]
VersionPress tries to [create the database](https://github.com/versionpress/versionpress/blob/8244d42a267d2041c09eaf08031aa5cdaeb26a4b/plugins/versionpress/src/Cli/vp.php#L332) on `restore-site`. Maybe the DB user does not have permission to create databases? Anyway, there could be some error message.

**Comment by dmeehan1968** [comment]
Ok, I had terrible trouble with this using MAMP on MacOS, the documentation is poor in its examples, and I got stymied by the fact that ```wp config create``` assumes the mysql server is on ```localhost```.  This DOES NOT work with MAMP installs, where is needs to be specified as ```127.0.0.1:3306``` or whatever IP:Port your MAMP/mysql server is configured to use.

NB: This assumes that you are using Github as a third repository for sharing via team members.  The docs appears to assume you will use the production/staging machines directly.

1. On Github, create a new repo.  This will give you a giturl, which starts ```git@guthub.com``` and ends ```.git```

e.g.:
```
git@github.com:<gitusername>/<reponame>.git
```

2. On the original versionpress host (default/production/localdev), setup a remote and push:
```
git remote add origin <giturl>
git push origin master
```

3. On the new server ('Jane' in the docs example)
NB: 'localhost' is the default host name that ```wp config create``` uses, and this is not sufficient to connect to MAMP's mysql instance.

```
git clone <giturl> <local_dir>
cd <local_dir>
wp config create --dbhost='127.0.0.1:3306' --dbname=<mysql_schema> --dbuser=<mysql_user> --dbpass=<mysql_password>
wp db create
```

NB: If the database Schema already exists, it will warn you when you ```wp db create```, so for completeness, issue a ```wp db drop --yes``` before creating.

4. Download and unzip versionpress install to ```<local_dir>/wp-content/plugins``` (download the file from https://github.com/versionpress/versionpress/releases to the <local_dir>)

```
unzip versionpress-4.0-beta.zip -d wp-content/plugins/
rm versionpress-4.0-beta.zip
```

5. Fix versionpress directory permissions

```
chmod -r +X wp-content/plugins/versionpress
```

6. Run restore-site

```
wp vp restore-site --siteurl=<siteurl> --require=wp-content/plugins/versionpress/src/Cli/vp.php
```

**Comment by pavelevap** [comment]
It looks to me that problem was solved in the end. I am closing this issue for now, please reopen if you have additional info or need further assistance.
