### ISSUE TITLE
Wrong Git Version being detected

### ISSUE THREAD

**Issue by Techgeekster** [versionpress/support#101]
After I activated VersionPress I was going over the checklist before I could do the secondary activation and it said I needed to upgrade git to 1.9+.  I upgraded my server to use git version 2.9.4 but version press isn't detecting this new version. I verified with my web host that my server was indeed running 2.9.4 and they confirmed this.

System info page: http://www.brytermarketing.com/wp-admin/admin.php?page=versionpress%2Fadmin%2Fsystem-info.php
-- to confirm my versions on wordpress

VersionPress: 4.0-alpha1
WordPress: 4.8
Server OS: Linux
Webserver: InMotion VPS hosting
PHP: 5.6.3
Git: 1.8.3.1 according to the system info page, however my server is running 2.9.4

**Comment by pavelevap** [comment]
Hi @Techgeekster,

there are several hints:

- What can you see when using command `git --version` from website directory?
- It is possible that the old Git version is still the first in `PATH` and VersionPress uses it. You can check Git section of [system info page](https://docs.versionpress.net/en/troubleshooting/system-info-page) to find out details.
- You can specify path to latest Git version with `VP_GIT_BINARY` in `wp-config.php`, see [manual](https://docs.versionpress.net/en/getting-started/configuration#vp_git_binary).
- I would recommend to update VersionPress to [latest beta](https://blog.versionpress.net/2017/07/versionpress-4-0-beta/) version.
- Related issues: #32, #33 and #34.

**Comment by pavelevap** [comment]
Hi, did you manage to make it work? I will close it for now, please let us know if you need further assistance.

**Comment by cuonghungmai** [comment]
HI PVELEVAP
Please help me with this issue, thanks!
 Git
array (
  'git-binary-as-configured' => '/home3/jredimer/git-1.9.5',
  'git-available' => false,
  'output' => 
  array (
    'stdout' => '',
    'stderr' => 'sh: /home3/jredimer/git-1.9.5: is a directory',
  ),
  'env-path' => '/bin:/usr/bin',
)
