### ISSUE TITLE
Ran out of memory on activation

### ISSUE THREAD

**Issue by sandstones** [versionpress/support#103]
Tried to install versionpress 4.0 beta and got the following:

Setting things up for you. It may take a while, please be patient.
Environment set to 'default'
Starting up
Helper database tables created
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 608 bytes) in /home/moneythu/public_html/wp/wp-includes/wp-db.php on line 1877

Running Wordpress 4.8, PHP Version 5.6.31, git 2.13

We do have 
define( 'WP_MAX_MEMORY LIMIT', '256M' );

I deactivated the versionpress plugin and things seemed to return to normal.

How much memory should I need, or how can I tell?

And what would I have to do to 'start over'?

**Comment by pavelevap** [comment]
Hi @sandstones,

do you have any info about your database and WordPress installation (see [docs](https://docs.versionpress.net/en/troubleshooting/system-info-page))? How many entities were recognized by VersionPress before activation? How many plugins do you use?

This problem is probably related to database size or size of any particular row, for example some option for some plugin can have 10 MB (and more). Error leads to [this line](https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/wp-db.php#L1877) - performing particular database query call. But it can be also some problem on VersionPress side when transforming database values to `.ini` files, I am not sure yet. I tried database with more than 100 MB and it works well with `memory_limit` 256 MB.

Could you please deactivate all your plugins, switch to Twenty Seventeen and then try to activate VersionPress? The best way to start over is deleting VersionPress through WordPress administration and installing it once again.

**Comment by sandstones** [comment]
We have many plugins and disabling everything is not a practical solution on our live site.  We could try this in a test site, but that kind of defeats the purpose of version press.  And our db is not that big ~70MB.

Also, it appears that the attempt to activate versionpress did a purge of page versions in the WordPress db.  Is that expected?  It was not anything I saw in the documentation.

**Comment by borekb** [comment]
Hi @sandstones , yes please try on a test site (that is recommended anyway as VersionPress is currently a Developer Preview, not a production-ready software).

It shouldn't purge page versions for sure. Is it possible that some other plugin did that?

**Comment by sandstones** [comment]
I was particularly interested in versionpress for merging changes from a staging site, and thought we could try it for that, even if we didn't use anything else.  Is that realistic?

As far as the purging, it is something I wanted to do, and tried a plugin called WP Optimize,.  It said there were only 3 pages with versions to purge, whereas I expected there to be hundreds.  And now the old versions are gone in mysql.  So maybe WP Optimize just had bad reporting, and it did what it was supposed to.

**Comment by borekb** [comment]
VersionPress is great for database merging but currently works on simpler sites only, and is marked as a Developer Preview to indicate its overall status. Could you please attach the output of the [System Info Page](https://docs.versionpress.net/en/troubleshooting/system-info-page)? Thanks.

**Comment by pavelevap** [comment]
VersionPress is great (especially for developers), but you should be very carefull, especially for important production site with many plugins. You should also [check](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) every plugin and theme to avoid possible merging problems (data references, etc).

Memory problem is strange, maybe there is some conflict with other plugin or VersionPress does not like something in database. When you make a testing copy of your website we can find with your help the real cause.

- After deactivating all plugins and activating Twenty Seventeen problem should disappear. In this case it is probably some conflict and we should find which plugin is causing it.

- If there is still memory issue, something wrong is probably inside database. Could you share your mysql dump in this case?

**Comment by sandstones** [comment]
I upped memory to 500MB just to be sure, and then the activation did not get errors, but it did not complete.  I let it run overnight just to be sure, but there is still the message about "Please finish the activation"

It created the vpdb folder, and after about 10 minutes the post folder within that.  But it did not create a .git folder anywhere in the file system.  And there are no entries in the php error log.

I did not deactivate all the plugins and theme, doing that would make the site unreadable and useless. And doing this purely as an academic exercise is not what I had in mind.

**Comment by pavelevap** [comment]
If `vpdb` folder is not larger and larger every minute (transforming data from database to files) then it probably stopped working :-( Could you look at your PHP error logs if there is any hint? Also data from System Info Page (link above) would be helpful.

**Comment by borekb** [comment]
We got this in the past if there was a parsing error or something similar. Logs are indeed the only way to find out.

**Comment by sandstones** [comment]
I did mention in my earlier message that I checked the php error log and there were no new errors.  

The results of system info are attached.

[systeminfo.txt](https://github.com/versionpress/support/files/1197701/systeminfo.txt)

**Comment by borekb** [comment]
Thanks for the info. Without any info in the error log, this will be impossible to debug but looking at your site configuration, VersionPress will not work anyway (a site with 40+ plugins is not supported yet). Thanks for trying to make it work anyway, we hope to support such complex sites in the future.

**Comment by pavelevap** [comment]
Right, sorry for that. Some plugins are really complex for VersionPress, for example Advanced Custom Fields (see #102) or WooCommerce (see [here](https://github.com/pavelevap/versionpress-for-woocommerce)). Plugin support will be improved in the future, but no safe merging possible for now.

The only thing we can try (to enable VP for tracking your website) is testing your activation problem. But in this case we need your mysql dump to process it and locate error (probably some plugin data).

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info (`error.log`) or need further assistance.
