### ISSUE TITLE
Wordpress/Versionpress doesn't recognize git installation, what do I miss? 

### ISSUE THREAD

**Issue by ArneDBKey2info** [versionpress/support#105]
Wordpress-version: 4.8
I installed the latest GIT on my pc
I'm running localhost via XAMPP
Versionpress-Version:  4.0-beta

For some reason I think my GIT version doesn't get recognized.

Screenshot:
https://i.gyazo.com/2f6c7944602ff8caf2575c2b024a7c77.png

Quick summary
```
array (
  'wordpress-version' => '4.8',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Windows NT AFLUXX-PC 6.3 build 9600 (Windows 8.1 Professional N Edition) i586',
  'php-version' => '7.0.2',
  'php-sapi' => 'apache2handler',
  'git-version' => '',
  'git-full-path' => '',
  'wp-cli-full-path' => 'wp',
)
```
Git
```
array (
  'git-binary-as-configured' => 'tmp/git',
  'git-available' => false,
  'output' => 
  array (
    'stdout' => '',
    'stderr' => 'The system cannot find the path specified.',
  ),
  'env-path' => 'C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\redist\\intel64\\compiler;C:\\Program Files (x86)\\Razer Chroma SDK\\bin;C:\\Program Files\\Razer Chroma SDK\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\QuickTime\\QTSystem\\',
)

```

**Comment by pavelevap** [comment]
Hi @ArneDBKey2info,

which Git version, from where and how did you install it?

- What can you see when using command `git --version` from website directory? Does this work?
- It seems to me that Git is missing from your system `PATH`?

**Comment by ArneDBKey2info** [comment]
I’m running XAMPP, so I’m not really sure how to check which git version is running on XAMPP
I just went to the git website, downloaded the latest version.

**Comment by pavelevap** [comment]
You can check your Git version directly from Terminal. Did you install Git from [official](https://git-scm.com/downloads) site? Did you follow [instructions](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Comment by HughesProvare** [comment]
Hi @pavelevap, 

I am having this same problem. 

I installed git from here https://gitforwindows.org/ and am able to see git --version from the command line (2.18.0). However, WordPress does not find git. How do I check if git is on my system PATH?

WordPress does recognize git on my staging server but the issue occurs when I use VersionPress to create a local copy. 

Thanks,
Harrison

array (
  'wordpress-version' => '4.9.6',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Windows NT RECEPTION-SONY 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586',
  'php-version' => '7.1.13',
  'php-sapi' => 'apache2handler',
  'git-version' => '',
  'git-full-path' => '',
  'wp-cli-full-path' => 'wp',
)

array (
  'git-binary-as-configured' => 'git',
  'git-available' => false,
  'output' => 
  array (
    'stdout' => '',
    'stderr' => '\'"git"\' is not recognized as an internal or external command,
operable program or batch file.',
  ),
  'env-path' => 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\WIDCOMM\\Bluetooth Software\\;C:\\Program Files\\WIDCOMM\\Bluetooth Software\\syswow64;C:\\Program Files (x86)\\PuTTY\\;C:\\Program Files\\TortoiseGit\\bin;C:\\Users\\Harrison Hughes\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Harrison Hughes\\AppData\\Local\\atom\\bin',
)
