### ISSUE TITLE
My website is syncing

### ISSUE THREAD

**Issue by sebastienserre** [versionpress/support#108]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 3.0.2
- WordPress version: 4.8.1
- OS, webserver, PHP: Debian, Apache, PhP7
- Git version: git version 2.14.0.rc1

I'd like testing VersionPress but it's syncing for more than 2 Weeks. ...
it said me, it could be long as they're 18000 objects... but it seems strange....

**Comment by pavelevap** [comment]
Hi @sebastienserre,

there is probably any error, timeout or insufficient PHP memory, see for example related issue #103. Could you please check your error logs if you can find any hint what is wrong? Could you also share your [system info](https://docs.versionpress.net/en/troubleshooting/system-info-page)?

You can also try latest [4.0-beta](https://blog.versionpress.net/2017/07/versionpress-4-0-beta/) which fixes some bugs and problems.

**Comment by sebastienserre** [comment]
[system-info.txt](https://github.com/versionpress/support/files/1215967/system-info.txt)
I had the same pb with the 40-beta, ( I've tested it first) and seeing it was long, I re-install the latest stable

**Comment by pavelevap** [comment]
Thank you for info, it is probably almost the same problem as here: #103 (please read details about plugin support, etc).

1) Could you please check your error logs if you can find any hint what is wrong? We are not sure about the real cause.

2) Could you try to deactivate all plugins, activate Twenty Seventeen and then activate VersionPress again? Then we could find if there is problem only with stored data in database or some kind of plugin/theme conflict.

Please note that VersionPress is currently Developer Preview and it will not work for a site with many complex plugins. You should be able to use it as a tracking tool, but merging database will be impossible until there is support for your active plugins, see our [docs](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md). There are some examples to help you understand how it works ([WooCommerce](https://github.com/pavelevap/versionpress-for-woocommerce), [Advanced Custom Fields](https://github.com/versionpress/support/issues/102)).

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info (especially error log) or need further assistance.
