### ISSUE TITLE
Clone failing with error "git-upload-pack: command not found"

### ISSUE THREAD

**Issue by mBread** [versionpress/support#109]
When trying to run `wp vp clone` I'm getting the following error:

```
wp vp clone --name=staging --siteurl=http://{original URL omitted}/staging

Error: Cloning into '/home/me/staging'...
warning: templates not found /usr/share/git-core/templates
git-upload-pack '/home/me/public_html': git-upload-pack: command not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Error: Cloning Git repo failed
```

I have to specify `siteurl` as my existing site URL does not contain the name of the current folder in its path, so VP cannot work out the new URL.

If I run `which git-upload-pack` then it returns ` no git-upload-pack in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/cpanel/composer/bin:/usr/local/easy/bin:/home/me/bin)`

Running `which git` returns `/usr/bin/git`, and there are no other executables starting with the characters `git` in that directory. `ls -l /usr/bin/git` does not indicate that it is a symlink. So it looks like this is a problem with my git installation (on FastComet), but is there any information you can give me from VersionPress's side before I go to my hosting provider?

* WP version 4.8.1
* VP version 4.0-beta
* git version 2.14.1
* Other plug-ins: The only other active one is WordPress Importer. Hello Dolly and Akismet are also installed, but not active.
* PHP version 5.6.31
* uname -a returns: Linux (hostname omitted) 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fastcometcloud** [comment]
Hey there,

FastComet Team here!

Regrettably, we are not able to allocate your account so that check what might be the reason for the error that has occurred. Can you please post a ticket to our Tech support team so that we would be able to look into this.

Thanks!

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance. I suppose that problem is related to server configuration and I hope you figured it out with FastComet support.
