### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by qwik3r** [versionpress/support#11]
Hello,

Using Siteground as per your site's recommendation for a host. I downloaded my FTP from WP Engine, then exported my database and created a new database on Siteground, then imported my WP Engine site via phpmyadmin.This works fine and I'm able to load the site accordingly, changing a few things such as site url etc.

I should note that my sites are in sub directories. So inside of public_html is a folder for the main site called "site" (how clever). 

Using v2.2 I initiate the clone, it duplicates the site fine into a sub folder sitting next to 'site' called 'test', I go to visit my cloned site and a few things happen. 

1) An error with Revolution Slider plugin (see below)

Fatal error: Uncaught exception 'Exception' with message 'fetch - <b>Unknown column 'type' in 'where clause'</b><br>---<br> Query: select * from wp_test_revslider_sliders where `type` != &#039;template&#039; OR `type` IS NULL order by id ASC /* From [37.60.247.225/~lindsa75/test/] in [/home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/framework/db.class.php:130] */' in /home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/framework/functions.class.php:14 Stack trace: #0 /home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/framework/db.class.php(26): RevSliderFunctions::throwError('fetch - <b>Unkn...', -1) #1 /home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/framework/db.class.php(41): RevSliderDB->throwError('fetch - <b>Unkn...') #2 /home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/framework/db.class.php(132): RevSliderDB->checkForErrors('fetch') #3 /home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/slider.class. in /home/lindsa75/public_html/test/wp-content/plugins/revslider/includes/framework/functions.class.php on line 14

So I have to temporarily remove that plugin. 

2) Issue with Membermouse. 

Fatal error: Class 'WordPressHTTPS' not found in /home/lindsa75/public_html/test/wp-content/plugins/membermouse/bootstrap/class.utils.php on line 215

Then I have to remove that plugin. 

3) After removing the aforementioned plugins I get an error 404 that the homepage isn't found. This is because the homepage isn't set in the admin settings, but why... I'm simply cloning the site, so that's odd. 

4) Can't login to the admin because then a site redirect occurs which brings me back to /site/ instead of the login for test. Looks like I have to edit the .htaccess file in the cloned /test/ directory as well as the wp-config.php file and change the site url and the home url to reflect the clone. 

5) I am finally able to (almost) login and then I get an error relating to my theme. Fatal error: Cannot use object of type Closure as array in /home/lindsa75/public_html/test/wp-content/themes/Total/framework/visual-composer/vc-config.php on line 97 - So then I have to comment out the following that works fine in the original site but not on the clone: 

		// Loop through filter
		foreach ( $filters as $priority => $filter ) {
			foreach ( $filter as $identifier => $function ) {
				if ( is_array( $function )
					and is_a( $function['function'][0], 'Vc_Updater' )
					and 'upgradeFilterFromEnvato' === $function['function'][1]
				) {
					remove_filter( 'upgrader_pre_download', array ( $function['function'][0], 'upgradeFilterFromEnvato' ), $priority );
				}
			}
		}
6) Now i'm able to login and try to test some things out. Following your documentation about "pushing" from my clone's directory I try to PULL down the latest version of the site from the main site directory (site) so I do (in the clone) wp vp pull --from=site and get the following error. What am I doing wrong here? I thought I could pull things from the live site to the cloned/staging site? 

Error: Changes from site couldn't be pulled. Details:

fatal: 'site' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pavelevap** [comment]
Hi,
thank you for detailed report.

Some issues are probably expected because VersionPress currently does not support complex plugins, please see our [documentation](http://docs.versionpress.net/en/integrations). I was not able to reproduce you problems, because you are using premium (paid) plugins which are not available.

Other issues are a little bit strange and I am not sure about it yet. But maybe they are caused by previous incompatibilities (or combination of different factors). Any chance to share your website (files and database dump) to allow us directly follow your steps?

**Comment by qwik3r** [comment]
HI there,

I'm not sure if I can share that information or what can done beyond that
at this point. It could be any combo of plugins etc that are causing this
issue. Is there anyway to for you guys to test some complex plugins like
Membermouse on a trial? I'm sure they would let you if you introduced
yourselves.

**Comment by borekb** [comment]
@qwik3r At this point, we will not be able to add specific support for specific plugins (commercial or not), unfortunately. This will be a broader effort later this year as we'll provide some sort of hooks for 3rd party plugins and they will then be able to hook into our versioning functionality.

If your goal is to support your current website, it's unfortunately too complex for VersionPress at the moment. If you want to test cloning on a vanilla WordPress site and still see the issues, then that would be something we should look into.

**Comment by qwik3r** [comment]
Thanks
