### ISSUE TITLE
Not really sure if VersionPress is installed or stuck

### ISSUE THREAD

**Issue by ArneDBKey2info** [versionpress/support#110]
- VersionPress version:
4.0 - beta

- WordPress version:
4.8.1

- OS, webserver, PHP:
OS: not sure
webserver: Varnish, Nginx
PHP 7.0

- Git version: 
2.14.1

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

I can't get to this page, because I only see the following:
https://i.gyazo.com/6de9bf35f9569c4d396db2f2f552b71d.png

I was wondering if Versionpress is actually doing something right now? Or is it stuck? I'm not really sure.

**Comment by pavelevap** [comment]
Hi @ArneDBKey2info,

sorry for trouble, it is a known bug: https://github.com/versionpress/versionpress/issues/1244
You can fix it by enabling [proc_open](http://php.net/manual/en/function.proc-open.php) in your PHP configuration.
