### ISSUE TITLE
Your local changes to the following files would be overwritten by merge

### ISSUE THREAD

**Issue by ericft** [versionpress/support#111]
I have installed the plugin on both local (MAMP Pro Mac) and staging (CentOS 7). When I try to wp vp pull I have an error message (bellow).

Maybe it's a problem with my gitignore:
[gitignore.zip](https://github.com/versionpress/support/files/1261751/gitignore.zip)

Thanks for your help.

error: Your local changes to the following files would be overwritten by merge:
	wp-content/vpdb/options/%3/%3C%3Ctable-prefix%3E%3Eewwwio_media_optimize_batch_a.ini
	wp-content/vpdb/options/%3/%3C%3Ctable-prefix%3E%3Eewwwio_media_optimize_batch_b.ini
	wp-content/vpdb/options/%3/%3C%3Ctable-prefix%3E%3Einstaller_clientside_active_tab.ini
	wp-content/vpdb/options/%3/%3C%3Ctable-prefix%3E%3Einstaller_settings.ini
	wp-content/vpdb/options/%3/%3C%3Ctable-prefix%3E%3Euser_roles.ini
	wp-content/vpdb/options/30/301_redirects.ini
	wp-content/vpdb/options/6b/6b5871162fda2e24de77cfc6ff21d19b.ini
	wp-content/vpdb/options/CC/CC_HR_OPTIONS.ini
	wp-content/vpdb/options/Fo/Forms3rdPartyIntegration_settings.ini
	wp-content/vpdb/options/Fo/Forms3rdPartyIntegration_version.ini
	wp-content/vpdb/options/MP/MPSUM.ini
	wp-content/vpdb/options/WB/WBOUNCE_OPTION_KEY_version.ini
	wp-content/vpdb/options/WP/WPCF_VERSION.ini
	wp-content/vpdb/options/WP/WPLANG.ini
	wp-content/vpdb/options/__/__nelio_ab_used_free_trial.ini
	wp-content/vpdb/options/_e/_et_core_portability_temp_files.ini
	wp-content/vpdb/options/_w/_wpcf_promo_tabs.ini
	wp-content/vpdb/options/ab/abl_admincssmu_version.ini
	wp-content/vpdb/options/ac/active_plugins.ini
	wp-content/vpdb/options/ad/admin_email.ini
	wp-content/vpdb/options/ad/admincssmu_custom_css.ini
	wp-content/vpdb/options/ai/ai1wm_secret_key.ini
	wp-content/vpdb/options/ai/ai1wm_status.ini
	wp-content/vpdb/options/ai/ai1wm_updater.ini
	wp-content/vpdb/options/ai/ai1wm_url_adapter.ini
	wp-content/vpdb/options/ai/ai1wm_url_ip.ini
	wp-content/vpdb/options/ai/ai1wm_url_transport.ini
	wp-content/vpdb/options/am/ame_pro_external_updates.ini
	wp-content/vpdb/options/av/avatar_default.ini
	wp-content/vpdb/options/av/avatar_rating.ini
	wp-content/vpdb/options/b6/b64_block_id.ini
	wp-content/vpdb/options/b6/b64_button_option.ini
	wp-content/vpdb/options/b6/b64_button_text.ini
	wp-content/vpdb/options/b6/b64_format.ini
	wp-content/vpdb/options/b6/b64_wordwrap.ini
	wp-content/vpdb/options/ba/background_color_tint.ini
	wp-content/vpdb/options/bl/blacklist_keys.ini
	wp-content/vpdb/options/bl/blog_charset.ini
	wp-content/vpdb/options/bl/blog_public.ini
	wp-content/vpdb/options/bl/blogdescription.ini
	wp-content/vpdb/options/bl/blogname.ini
	wp-content/vpdb/options/bo/bodhi_svgs_admin_notice_dismissed.ini
	wp-content/vpdb/options/bo/bodhi_svgs_plugin_version.ini
	wp-content/vpdb/options/bo/bodhi_svgs_settings.ini
	wp-content/vpdb/options/c2/c2c_add_admin_javascript.ini
	wp-content/vpdb/options/ca/category_base.ini
	wp-content/vpdb/options/cf/cf7_mch_4689.ini
	wp-content/vpdb/options/cf/cf7_mch_5170.ini
	wp-content/vpdb/options/cf/cf7_mch_5244.ini
	wp-content/vpdb/options/cl/close_comments_days_old.ini
	wp-content/vpdb/options/cl/close_comments_for_old_posts.ini
	wp-content/vpdb/options/cm/cms_tpv_options.ini
	wp-content/vpdb/options/cm/cms_tpv_show_annoying_little_box.ini
	wp-content/vpdb/options/cm/cms_tpv_show_promo.ini
	wp-content/vpdb/options/cm/cms_tpv_version.ini
	wp-content/vpdb/options/co/comment_max_links.ini
	wp-content/vpdb/options/co/comment_moderation.ini
	wp-content/vpdb/options/co/comment_order.ini
	wp-content/vpdb/options/co/comment_registration.ini
	wp-content/vpdb/options/co/comment_whitelist.ini
	wp-content/vpdb/options/co/comments_notify.ini
	wp-content/vpdb/options/co/comments_per_page.ini
	wp-content/vpdb/options/co/content_link_color.ini
	wp-content/vpdb/options/cp/cpac-install-timestamp.ini
	wp-content/vpdb/options/cp/cpac_general_options.ini
	wp-content/vpdb/options/cp/cpac_options_et_pb_layout__default.ini
	wp-content/vpdb/options/cp/cpac_options_lp.ini
	wp-content/vpdb/options/cp/cpac_options_lp__default.ini
	wp-content/vpdb/options/cp/cpac_options_page.ini
	wp-content/vpdb/options/cp/cpac_options_page__default.ini
	wp-content/vpdb/options/cp/cpac_options_post.ini
	wp-content/vpdb/options/cp/cpac_options_post__default.ini
	wp-content/vpdb/options/cp/cpac_options_product__default.ini
	wp-content/vpdb/options/cp/cpac_options_produit.ini
	wp-content/vpdb/options/cp/cpac_options_produit__default.ini
	wp-content/vpd
error: Your local changes to the following files would be overwritten by merge:
	.gitignore

**Comment by pavelevap** [comment]
Hi @ericft,

something is probably wrong with your `.gitignore` file. This is your original file from basic website (or from staging)? It is based on some special project rules? I tried to use it and create staging (with [wp vp clone](https://docs.versionpress.net/en/sync/cloning) command), but it did not work because of your rule `/*` (Ignore everything in the root except the `wp-content` directory). So, I was not able to create working staging website to test pull command. How did you manage to create staging site? Manually?

**Comment by ericft** [comment]
Yes i did manually. But I will change my workflow. My problem right now is
I keep having errors because of Yaml, I'm on PHP 7.0 and CentOS.
