### ISSUE TITLE
Yaml error

### ISSUE THREAD

**Issue by ericft** [versionpress/support#112]
Hi,

We have a constant error with Yaml and PHP 7.0.22 (cli) on CentOS 7.

[Wed Aug 30 22:09:35.463388 2017] [:error] [pid 3962] [client 23.91.147.228:23533] PHP Fatal error:  Uncaught Symfony\\Component\\Filesystem\\Exception\\IOException: Failed to remove file "/var/www/wp-mainline/wp-content/vpdb/posts/FD/FD28111840174946805AFF6C43385239.ini": unlink(/var/www/wp-mainline/wp-content/vpdb/posts/FD/FD28111840174946805AFF6C43385239.ini): Permission denied. in /var/www/wp-mainline/wp-content/plugins/versionpress/vendor/symfony/filesystem/Filesystem.php:180\nStack trace:\n#0 /var/www/wp-mainline/wp-content/plugins/versionpress/vendor/symfony/filesystem/Filesystem.php(172): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#1 /var/www/wp-mainline/wp-content/plugins/versionpress/vendor/symfony/filesystem/Filesystem.php(172): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#2 /var/www/wp-mainline/wp-content/plugins/versionpress/vendor/symfony/filesystem/Filesystem.php(172): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#3 /var/www/wp-mainline/wp-content/plugins/versionpress/src/Utils/FileSystem.php(49): Symfony\\Component\\Filesystem\\Filesystem->remove(Array)\n#4 /var/www/wp- in /var/www/wp-mainline/wp-content/plugins/versionpress/vendor/symfony/filesystem/Filesystem.php on line 180, referer: /wp-admin/admin.php?page=versionpress
[Wed Aug 30 22:11:09.844439 2017] [authz_core:error] [pid 6975] [client 54.161.42.51:41424] AH01630: client denied by server configuration: /var/www/wp-mainline/wp-content/plugins/versionpress/versionpress-nginx.conf

![2017-08-31](https://user-images.githubusercontent.com/1869027/29932204-9cb031c8-8e41-11e7-944b-139c2c8cd92c.png)

Any idea or suggestions?

Thank you for your support!

**Comment by borekb** [comment]
Not exactly sure but this looks most likely like a server configuration issue, not something wrong with VersionPress. Will you be able to get help from some system admin?

**Comment by ericft** [comment]
Yes and did not find the issue. Any suggestions?

Thank you

**Comment by borekb** [comment]
Not really, apart fixing your server :) I've personally never seen that Yaml error, and also file system permissions seem to be incorrect.

**Comment by ericft** [comment]
Ok thanks Borek

**Comment by ericft** [comment]
Is it normal vpcache/actions/wp-content-actions.yml is empty after the
installation?
