### ISSUE TITLE
Empty yml file

### ISSUE THREAD

**Issue by ericft** [versionpress/support#113]
Hi,

Is it normal vpcache/actions/wp-content-actions.yml is empty after the installation?

**Comment by pavelevap** [comment]
Hi @ericft 

file `wp-content/vpcache/actions/versionpress-actions.yml` should be a copy of `wp-content/plugins/versionpress/.versionpress/actions.yml`. From previous issues (#111 and #112) it looks like that there is some permissions problem on your server.

How do you install VersionPress? Did you download [latest](https://github.com/versionpress/versionpress/releases) .zip package? There were no notices during activation?

**Comment by ericft** [comment]
Yes I installed the latest package. I did copy the file manually and
everything seems to work.

Thank you!
