### ISSUE TITLE
Error restoring site using versionpress and wp-cli on windows

### ISSUE THREAD

**Issue by alexfrench** [versionpress/support#115]
Hi

I've got VP working on our webserver, have cloned the repo to bitbucket, cloned again to GIT on local dev environment, installed WP, installed VP plugin, have WP-CLI working on dev,

I've checked the system info on VersionPress via the admin page. It checks out fine. GIT version above 1.9+.

However, when I try to restore from the local repo using the command below, it reports that the version of git is not 1.9+. 

wp vp restore-site --siteurl='http://localhost/mysite’

I have only one version of GIT installed. I have checked the path it is included in the environment variables. I also tried setting the path in wp-config-common.php. Same result. 

When I run the command I see this which may be relevant? Not sure if this is an error or info!
/** Sets up WordPress vars and included files. */
') phar://C:/xampp/htdocs/wp-cli/wp-cli.phar/php/WP_CLI/Runner.php:1020
    0.7458    5579120   9. include_once('C:\xampp\htdocs\mysite\wp-config.common.php') phar://C:/xampp/htdocs/wp-cli/wp-cli.phar/php/WP_CLI/Runner.php(1020) : eval()'d code:2

'wordpress-version' => '4.8.1',
'versionpress-version' => '4.0-beta',
'operating-system' => 'Windows 10)
'php-version' => '5.6.14',
'php-sapi' => 'apache2handler',
'git-version' => '2.14.1',
'git-full-path' => 'C:\\Program Files\\Git\\cmd\\git.exe
Using XAMPP/Apache

Any help appreciated.

Cheers
Alex

**Comment by pavelevap** [comment]
Hi @alexfrench,

so you have some website with VersionPress activated (on server). And you cloned (`git clone`) this website to local dev environment (Windows computer)? And then you tried to [restore](https://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site) this site from cloned git repository? I am also using Windows and xampp and I did not notice any problem. When you clone website repository to your development machine, there is no need for manual WordPress installation and activating VersionPress. You can only follow [steps](https://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site) for restoring the whole website, especially part named **development scenario**.

As regards to Git version problem, could you please check similar issue #101?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
