### ISSUE TITLE
New install issues

### ISSUE THREAD

**Issue by mmendelson222** [versionpress/support#116]
Hi - I have a couple of issues, after a first-time install.  Apologies if this is a basic request.  There must be something fundamentally wrong, but it's not clear how to troubleshoot.  

1. when doing a pull, the "Synchronized Database" step takes about 15 minutes.  Does this indicate a large database, or a misconfiguration somewhere? 

2. When pushing, I receive the following error: 
Error: Push couldn't be finished. Details:
Error: Working directory couldn't be reset

Here's some of the troubleshooting data, in case it helps.  Thanks.

```
 Quick summary
 array (
  'wordpress-version' => '4.8.1',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Linux ip-10-0-0-109 4.9.38-16.35.amzn1.x86_64 #1 SMP Sat Aug 5 01:39:35 UTC 2017 x86_64',
  'php-version' => '7.0.21',
  'php-sapi' => 'apache2handler',
  'git-version' => '2.7.5',
  'git-full-path' => '/usr/bin/git
',
  'wp-cli-full-path' => 'wp',
 )
 Git
 array (
  'git-binary-as-configured' => 'git',
  'git-available' => true,
  'git-version' => '2.7.5',
  'git-binary-as-called-by-vp' => 'git',
  'git-full-path' => '/usr/bin/git
',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => true,
 )
```

**Comment by pavelevap** [comment]
Hi @mmendelson222,

what is your database size? Did you notice any warning about web size during VersionPress activation? Initial VersionPress activation was quick? Could you please share any [info](https://docs.versionpress.net/en/troubleshooting/system-info-page) about your WordPress installation (especially plugins)?

1) There were many changes to pull? Synchronizing database ended with success? What is your `max_execution_time` settings in PHP?

2) This error can be [seen](https://github.com/versionpress/versionpress/blob/a94dc0d3ea6fabb7bbefac649efc2905d5e555b5/plugins/versionpress/src/Cli/vp-internal.php#L177) when `git reset --hard` does not work. Could please try to describe steps to reproduce on simple testing website? I prepared clean WP installation `wp481`, created clone `wp481staging`, manually deleted Akismet plugin there, moved my console to `wp481staging` directory and used `wp vp push`. Everything worked smoothly, original `wp481` was updated with merged changes from staging environment.

**Comment by mmendelson222** [comment]
Hey thanks for your response.  I decided to go a completely different route, so I'm closing this issue.
