### ISSUE TITLE
Backend resources not loaded

### ISSUE THREAD

**Issue by Michael-Reich** [versionpress/support#117]
All fresh new installs of Wordpress and Versionpress and get this error on backend/admin.php

```
admin.php?page=versionpress:43 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/css/style.css?ver=4.0-beta 
admin.php?page=versionpress:41 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/css/jquery.webui-popover.min.css?ver=4.0-beta 
admin.php?page=versionpress:42 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/css/popover-custom.css?ver=4.0-beta 
admin.php?page=versionpress:44 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/icons/style.css?ver=4.0-beta 
admin.php?page=versionpress:56 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/js/vp-admin.js?ver=4.0-beta 
admin.php?page=versionpress:55 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/js/jquery.webui-popover.min.js?ver=4.0-beta 
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=4.8.1:9 JQMIGRATE: Migrate is installed, version 1.4.1
admin.php?page=versionpress:55 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/js/jquery.webui-popover.min.js?ver=4.0-beta 
admin.php?page=versionpress:56 GET http://wordpress.dev/wp-content/plugins/versionpress/admin/public/js/vp-admin.js?ver=4.0-beta 
```

500 internal server error

- VersionPress version: 4.0
- WordPress version: 4.8.1
- OS, webserver, PHP: Vagrant VCCW.cc
- Git version:

**Comment by pavelevap** [comment]
Hi @Michael-Reich,

sorry for delay :-(
How did you install VersionPress?
Did you download [latest](https://github.com/versionpress/versionpress/releases) `.zip` package?
There were no notices during activation?
Maybe there is some problem/conflict with [VCCW](http://vccw.cc/)?
Missing Git version is strange, but in this case VersionPress should not be available for activation.
Could you check your error logs to see if there is something related?

**Comment by pavelevap** [comment]
I am closing this issue for now, because it is probably server configuration problem. Please reopen if you have additional info or need further assistance.
