### ISSUE TITLE
Cannot commit in VersionPress console

### ISSUE THREAD

**Issue by Elethier** [versionpress/support#119]
- VersionPress version: 3.0.2
- WordPress version: 4.8.2
- OS: Linux ip-172-26-11-148 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64
- PHP Version: 7.0.12
- Git version: 1.9.1

I am currently unable to commit changes in the VersionPress console. The last commit I have was from a month ago, and I haven't made any configuration changes to my site since then. Looking in the Chrome Web inspector, I can see a POST to the URL `/wp-json/versionpress/commit` with a 200 OK response when I hit the "commit changes" button. However, the changes don't actually get committed, and the console says there's still uncommitted changes, even after I hit the commit button. When I SSH into the server, I can see that Git detects uncommitted changes in the website folder.

I am also seeing a related issue where one of my administrators is attempting to commit the changes, but he gets a 403 response from `/wp-json/versionpress/commit` and a message in the console: "Cookie nonce is invalid." He then ends up locked out of his WordPress account and ends up requiring a password reset. (If I should split this out to a separate issue, let me know.)

**Comment by pavelevap** [comment]
Hi @Elethier,

I am not sure what is wrong here, but there are some hints:

- Could you check your PHP logs to see if there is some helpfull information regarding this issue?
- Could you try to log out and log in to WP admin once again?
- Do you have any plugins active? Could you try to deactivate them all and activate basic theme (Twenty Seventeen)? Could you share any [details](https://docs.versionpress.net/en/troubleshooting/system-info-page) about your installation (particular plugins, etc)?
- Could you try to update to latest [4.0-beta](https://github.com/versionpress/versionpress/releases) version?

Cookie error probably comes from [here](https://github.com/WordPress/WordPress/blob/37ec288f71260cff568a90699c4c33aa0be85b97/wp-includes/rest-api.php#L784), but hard to say what is the reason.

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
