### ISSUE TITLE
Total meltdown

### ISSUE THREAD

**Issue by qwik3r** [versionpress/support#12]
I've tried to sync once and only once did it work. Piggy backing on my last support issue (#11) I decided to start from scratch. The following is my procedure to the letter and the errors that occurred thereafter. 

1) Cloned my main site
2) Had all sorts of issues just loading my cloned site (see other ticket)
3) Finally was able to load the 'test' (aka cloned) site. 
4) In Membermouse on the 'live' site I added a member, hoping to see if it would reflect accordingly on the test environment. (note: Membermouse plugin was not ACTIVE on the cloned site, not sure if this lead to an issue)
5) I added a new post on the test site
6) I go back to WP CLI and run the command to sync within the main site's directory and the following occurs. 

```
lindsa75@serv01 [~/public_html/site]# wp vp pull --from=test
Success: Maintenance mode turned on
Warning: 
Warning: CONFLICTS DETECTED. Your options:
Warning: 
Warning:  1) Keep the conflicts. You will be able to resolve them manually.
Warning:  2) Abort the process. The site will look like you never ran the pull.
Warning: 
Choose 1 or 2: 1
Success: You've chosen to keep the conflicts on the disk. MAINTENANCE MODE IS STILL ON.
Success: 
Success: Do this now:
Success: 
Success:  1. Resolve the conflicts manually as in a standard Git workflow
Success:  2. Stage and `git commit` the changes
Success:  3. Return here and run `wp vp apply-changes`
Success: 
Success: That last step will turn the maintenance mode off.
Success: You can also abort the merge manually by running `git merge --abort`
```

For some reason there are conflict unbeknownst to me. I proceed with allowing them and apply changes. It says all is good so I then proceed. 

6) I go back to the 'live' (aka 'site') site and it says that Maintenance mode is still active, uh oh. So then I go to delete the .maintenance file. 

7) I go refresh the site and I get a lovely message from WP citing "One or more database tables are unavailable. The database may need to be repaired.". 

8) I follow WP's recommendation ... "To allow use of this page to automatically repair database problems, please add the following line to your wp-config.php file. Once this line is added to your config, reload this page. define('WP_ALLOW_REPAIR', true);"

9) I refresh the page and it says "One or more database tables are unavailable. To allow WordPress to attempt to repair these tables, press the “Repair Database” button. Repairing can take a while, so please be patient."

10) I click 'repair' and wait and everything says "okay" and it instructs me to remove the line from my config file, so I do so and refresh the page.

11) I attempt to go back to /wp-admin and get the same error "One or more database tables are unavailable. The database may need to be repaired."

12) Going to the front end is a big ol message saying "Error establishing a database connection"

I give up :(

**Comment by borekb** [comment]
Just to be clear, in step 6, did you actually [resolve the Git conflicts](http://docs.versionpress.net/en/sync/merging#resolving-conflicts)? It seems that you might have just called the `apply-changes` without resolving the conflicts first which would then caused all sorts of trouble, like you experienced.

**Comment by qwik3r** [comment]
I didn't really resolve anything. I just did apply changes as it didn't
tell me what changes I need to resolve so I had no idea what to do...

**Comment by borekb** [comment]
Yes, sorry, this is not very user-friendly yet, you have to resolve conflicts manually using Git. However, if you do, the workflow should work. I'm closing this, let us know if there's anything else that doesn't work. Thanks.

**Comment by eddielee394** [comment]
It's probably worth mentioning, the Membermouse plugin the op mentions uses a custom db prefix `mm_` which may be causing some of the conflicts.  Not sure whether VP is able to handle table prefixes not defined in the wp-config file.
