### ISSUE TITLE
Git not passing activation

### ISSUE THREAD

**Issue by petergus** [versionpress/support#120]
I am trying to activate Versionpress locally.

The activation page says that Git is not available, So i entered the following in wp-config.php 
`define('VP_GIT_BINARY', '/usr/local/git/bin/git');`

Which returns
 `# /usr/local/git/bin/git --version
git version 2.0.1`

However, with that in the config, the activation does not load. 

Without that in the config I get the following on the more info page.

the proc_open user may be wrong, where does that get set?

I may be into all this trouble because I am trying to copy from the server and set up a dual system locally. What is the correct workflow, especially when copying the database??

```

Git
array (
  'git-binary-as-configured' => 'git',
  'git-available' => false,
  'output' => 
  array (
    'stdout' => '',
    'stderr' => 'xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun',
  ),
  'env-path' => '/usr/bin:/bin:/usr/sbin:/sbin',
)
Permissions
array (
  'exec-user' => 'petergus',
  'proc_open-user' => 'petergus',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),

```

- VersionPress version: 4.0-beta
- WordPress version: 4.8
- OS, webserver, PHP: Mac, MAMP, PHP 5.6.27
- Git version: 2.0.1

**Comment by petergus** [comment]
I just want to add that I fixed it by following the instructions here https://blog.versionpress.net/2016/11/remote-workflows/
and then setting the git path as advised with WP CLI instead of manually.

"If at first you don't succeed, read the manual" :)

**Comment by borekb** [comment]
@petergus Thanks for letting us know!
