### ISSUE TITLE
Cannot unzip

### ISSUE THREAD

**Issue by petergus** [versionpress/support#121]
When I download 4.0 beta, and try to unzip (MacOS 10.12) I get the following:

Unable to expand, Error 1, operation not permitted.

![screen shot 2017-10-22 at 10 58 04](https://user-images.githubusercontent.com/1854091/31860261-f4b5e17a-b717-11e7-8dee-372bd2d97851.png)

**Comment by pavelevap** [comment]
Hi @petergus,

it [was](https://github.com/versionpress/versionpress/issues/1138) a problem for `4.0-alpha1` version, but `4.0-beta` should be OK :-( Did you download archive from [here](https://github.com/versionpress/versionpress/releases)? You can always install this archive manually through WordPress administration, menu Plugins - Add New - Upload Plugin.

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
