### ISSUE TITLE
append a on siteurl

### ISSUE THREAD

**Issue by petergus** [versionpress/support#122]
Everytime I do `wp vp pull` an "a" get appended on the `siteurl`.

- VersionPress version: 4.9 beta
- WordPress version: 4.8

**Comment by pavelevap** [comment]
Hi @petergus,

sorry for delay. I tested `wp vp pull` ([docs](https://docs.versionpress.net/en/sync/merging)) and did not notice similar behaviour. Could you please describe your workflow? How did you created staging site and in which direction pulling causes this problem?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
