### ISSUE TITLE
Activation starts but nothing happens. 

### ISSUE THREAD

**Issue by a200tq** [versionpress/support#123]
Hey,
I am trying to activate VersionPress, website gets set to maintenance mode for a while, then site goes back to live mode, but VersionPress in back-end still does show same:

VersionPress Activation
Setting things up for you. It may take a while, please be patient.

> Environment set to 'Production'
> Starting up
> Helper database tables created and not change for long time. 
> 

If I do refresh or go to VersionPress dashboard it just gives Activation option again. 

'wordpress-version' => '4.8.3',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Linux am4.fcomet.com 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64',
  'php-version' => '7.0.25',
  'php-sapi' => 'cgi-fcgi',
  'git-version' => '2.14.1',
  'git-full-path' => '/usr/local/bin/git',
  'wp-cli-full-path' => 'wp',

Any advice? 

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by pavelevap** [comment]
Hi @a200tq,

there are some hints to troubleshoot this issue:

- Could you please check your PHP logs to see if there are some helpfull information regarding this issue?
- Do you have any plugins active? Could you try to deactivate them all, activate basic theme (Twenty Seventeen) and then activate VersionPress? Could you share any [details](https://docs.versionpress.net/en/troubleshooting/system-info-page) about your installation (particular plugins, etc)?
- How large is your website (especially database)?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info (especially error log)  or need further assistance.
