### ISSUE TITLE
How to merge db

### ISSUE THREAD

**Issue by shaded2** [versionpress/support#124]
I have not installed yet, i just got burnt but not having version control and a proper process and i'm researching options to not have it happen again. 

My host has a staging option but its rather useless when supporting a live site with active woocommerce customers. If we could merge the prod db with staging, it would make staging viable again. 

Imagine my surprise when i saw this: 

> Merge databases  ← yes, really!
I'm not even sure how that's possible. Been searching the documentation and i cant find anything relating to this topic. Can someone help point me in the right direction?

**Comment by borekb** [comment]
Hi @shaded2 , how it works is briefly mentioned here: https://blog.versionpress.net/2016/11/remote-workflows/

Basically, VersionPress transforms database entities to plain text files, then version-controls them with Git which enables all the nice things like branching and merging, then updates the database using the `wp vp apply-changes` command. The most tricky part is ID handling, i.e., when you create two new posts in two different environments and they both get the same ID (say, `15`), VersionPress needs to re-number one of them and update all references to it.

Hope this helps a bit.

**Comment by shaded2** [comment]
@borekb  that is awesome! Unfortunately that site i wanted to use it on has a bunch of third party plugins and is a multisite :(

I tried the latest beta on a smaller site and git log looks great.. the ui has an issue. See screenshot below, its been like this for a day.  Nothing in wp debug.log

![screenshot 2017-11-24 at 11 40 25 am](https://user-images.githubusercontent.com/762383/33218704-586b9e90-d10c-11e7-8c1f-10012d3eb86e.png)

**Comment by borekb** [comment]
Any errors in the browser console?

**Comment by shaded2** [comment]
yup.. 
![screenshot 2017-11-24 at 9 16 41 pm](https://user-images.githubusercontent.com/762383/33226485-d1ba35cc-d15c-11e7-8ba3-2dc5e3b02ecf.png)

**Comment by borekb** [comment]
Is it possible that the home / siteurl are not set correctly?

**Comment by shaded2** [comment]
yup that was it. changed them both to https, and all is well now
Thanks!
