### ISSUE TITLE
UI NOT Loading as wp json is working and Network response is also 200 ok

### ISSUE THREAD

**Issue by mkbalhotra** [versionpress/support#125]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 4.0
- WordPress version:4.8
- OS, webserver, PHP: PHP 5.6+ 
- Git version:Git 1.9+

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by pavelevap** [comment]
Hi @mkbalhotra,

sorry to miss your issue :-(

- What can you see on VersionPress page (do you have a screenshot)?
- Did you check your PHP error logs (fatal errors, insufficient memory, etc)?
- Do you have any active plugins on your site? Could you please deactivate them all and activate default theme Twenty Seventeen?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
