### ISSUE TITLE
sys_temp_dir not passing requirements check

### ISSUE THREAD

**Issue by petergus** [versionpress/support#129]
Trying to activate version press on a Debain 7 VPS, and it is not liking the permissions of the sys_temp_dir, which is confirmed to be /tmp

Here is the ls -al from /tmp

```
drwxrwxrwt.  5 root root 4096 Jan  8 06:27 .
drwxr-xr-x  25 root root 4096 Jan  8 06:15 ..
drwxrwxrwt.  2 root root 4096 Jan  8 04:54 .ICE-unix
drwxrwxrwt.  2 root root 4096 Jan  8 04:54 .X11-unix
-rw-rw-r--.  1 web  web     5 Jan  8 06:22 .vp-try-write
-rw-rw-r--.  1 web  web     5 Jan  8 06:22 .vp-try-write-process
```

```
Permissions
array (
  'exec-user' => 'web',
  'proc_open-user' => 'web',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => false,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => false,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)
```

**Comment by petergus** [comment]
I had to set 
`open_basedir = "php_admin_value open_basedir "/var/www/web/data:/tmp"`
in the apache vhost directory directives.

**Comment by zauker** [comment]
I add this line in my php.ini file to solve the same issue:

`
sys_temp_dir="/Applications/XAMPP/xamppfiles/temp/"
`

I have a local installation with XAMPP on Mac Book Pro.

**Comment by pavelevap** [comment]
Thank you for info! I am closing this issue for now, because it is probably configuration problem. Please reopen if you have additional info or need further assistance.
