### ISSUE TITLE
VP Welcome Panel Not Showing

### ISSUE THREAD

**Issue by glmtechcrew** [versionpress/support#13]
Hello there! I have setup a new testing / development server on my local machine using Desktop Server (ServerPress) In installed VersionPress and the setup process went fine. I get a few warnings concerning non tested third party plugins...and when I click on the VersionPress link in wp-admin The page is not loading. My console states that display-welcome-panel and commits are not found....

I also tried disabling all other plugins but the issue is still there. Anyway if I ccheck out my Git on my laptop I see that I have a working local git repository and monitoring.

What can I do?

**Comment by glmtechcrew** [comment]
I just realized that the directory http://www.mylocaldomain.dev/my_wordpress_subdir/vp-json/versionpress/display-welcome-panel does not exist....

**Comment by borekb** [comment]
Hi, which versions of WordPress and VersionPress are you running? Can you reproduce the issue on a vanilla WordPress install? Thanks.

**Comment by borekb** [comment]
@glmtechcrew if you have additional info please let us know, for now, I'm closing this.
