### ISSUE TITLE
Permissions denied while running `wp vp pull` : could not read from remote repository

### ISSUE THREAD

**Issue by maxperei** [versionpress/support#130]
hello there, this is the system info where i'm getting this issue:

- VersionPress 3.0.2
- WordPress 4.9.1
- Windows 10, Apache 2.4.27, PHP 7.0.23
- Git 2.15.1

so, i'm using versionpress with ubuntu and i'm very pleased of the way the plugin works, especially while merging database when running `wp vp pull`; you are doing an amazing job !

but, when i switch my operating system from ubuntu to windows and after successfully cloning the project (i followed [this section](https://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site)) i realized i could only execute basic git commands such as `git pull` or `git push` with success but i can't perform neither `wp vp pull` nor `wp vp push` .

## when pulling :
``` 
Warning: is_dir(): Unable to find the wrapper "ssh" - did you forget to enable it when you configured PHP?
Error: changes from origin couldn't be pulled. Details :
Permission denied (password, publickey)
```
## when pushing : 
```
Warning: proc_open(): CreateProcess failed, error code - 267
Fatal Error: uncaught Symfony\Component\Process\Exception\RuntimeException: Unable to launch a new process.
```

when i go back to ubuntu after a `git pull` on windows i'm able to receive all i want by running `wp vp pull` even merging database, but i don't understand exactly why it works in that sense, perhaps i'm missing something.

anyway, thank you for your time and for developing such a "revolutionary" tool !

**Comment by borekb** [comment]
Hi @maxperei, so `git pull` on Windows works but `wp vp pull` doesn't? That's strange because if SSH fails, it should fail equally for plain `git` and for the same command wrapped in `wp vp pull`. Maybe you could try HTTPS instead of SSH for pulling to see if that helps.

**Comment by pavelevap** [comment]
Hi @maxperei,

for possible explanation of `wp vp push` error please see issue #134. When you are pushing changes to Git repository which is not running site (for example Bitbucket, Github, etc), there is no need for `wp vp push`, but `git push` is good enough in this case.

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
