### ISSUE TITLE
Error when "wp vp push"

### ISSUE THREAD

**Issue by adriamt** [versionpress/support#134]
Hello, first this is my system info:

- VersionPress version:  4.9.2
- WordPress version: 4.0-beta
- OS, webserver, PHP: Windows 10, Apache,  PHP 7.0.10
- Git version: 2.10.2

I'm trying to achieve TeamWork with a bitbucket repo. 

On my computer 1 I've created a Wordpress site and then installed versionpress like described on Example 1 ([https://blog.versionpress.net/2016/11/remote-workflows/](https://blog.versionpress.net/2016/11/remote-workflows/))
But when it's time to make "wp vp push" it doesn't work, it only works when I use git push.
These are the errors I'm getting:
```
C:\wamp64\www\tag\myrfon_test>wp vp push
Warning: proc_open(): CreateProcess failed, error code - 267 in C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\vendor\symfony\process\Process.php on line 337
Fatal error: Uncaught Symfony\Component\Process\Exception\RuntimeException: Unable to launch a new process. in C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\vendor\symfony\process\Process.php:344
Stack trace:
#0 C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\src\Utils\Process.php(45): Symfony\Component\Process\Process->start(NULL)
#1 C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\vendor\symfony\process\Process.php(214): VersionPress\Utils\Process->start(NULL, NULL)
#2 C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\src\Cli\VPCommandUtils.php(63): Symfony\Component\Process\Process->run()
#3 C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\src\Cli\VPCommandUtils.php(40): VersionPress\Cli\VPCommandUtils::exec('wp vp-internal ...', 'https://adriamt...')
#4 C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\src\Cli\vp.php(1226): VersionPress\Cli\VPCommandUtils::runWpCliCommand('vp-internal', 'maintenance', Array, 'https://adriamt...')
#5 C:\wam in C:\wamp64\www\tag\myrfon_test\wp-content\plugins\versionpress\vendor\symfony\process\Process.php on line 344
```

I think it's similar to the error #130 but there is no solution there, and as a difference I can make "wp vp pull" without problems.

**Comment by pavelevap** [comment]
Hi @adriamt,

I am not sure, but I found several references which could help:

- Our related troubleshooting [page](https://github.com/versionpress/versionpress/blob/master/docs/content/en/08-troubleshooting/05-iis.md) is related to IIS, but maybe part of it can be used also for Windows + Apache.
- I found also mention related to VersionPress in SE [question](https://stackoverflow.com/questions/30296288/php-warning-proc-open-createprocess-failed-error-code-267). It looks like some configuration/permission issue, but hard to say :-(

**Comment by adriamt** [comment]
I've looked the references you put but I'm not able to solve the issue.

If I look the System info page, I think that the permissions are Ok
![image](https://user-images.githubusercontent.com/11394100/35589729-10dcdca0-0605-11e8-90fb-8f14cc230e1e.png)

And about the tmp dir, I don't know where to look or what to do, any help will be appreciated.

**Comment by pavelevap** [comment]
Yes, everything looks fine. So, you have local WordPress installation with VersionPress activated and you want to push your site into Github repository? It looks like you are pushing changes back to original site (default `origin`)? Maybe you have to [add remote](https://help.github.com/articles/adding-a-remote/) (setting path to your Github repo) first (or use `--to` parameter, [source](https://github.com/versionpress/versionpress/blob/129bf9724fa468cfcdbb86df6f7ddfa86c46889f/plugins/versionpress/src/Cli/vp.php#L803))?

**Comment by adriamt** [comment]
Yes, I have a local WordPress installation with VersionPress activated and what I'm trying to achieve is to work from another computer on the same Wordpress repo.
So after the installation, I've added my remote repo (at bitbucket)
![image](https://user-images.githubusercontent.com/11394100/35613373-2a84a072-066c-11e8-92c8-76a2e5615a29.png)
And then when I try `wp vp push` to the remote repo it shows the error that I mentioned before.

**Comment by pavelevap** [comment]
You are right, I tested it a moment ago with Bitbucket repo and received the same error :-( I will try to investigate this issue...

**Comment by adriamt** [comment]
Thanks !! I'll hope you find a solution!

**Comment by borekb** [comment]
@adriamt Hi, I've updated the blog post to use `git push` instead of `wp vp push`, it was there by mistake. Thanks for letting us know about the error!

**Comment by adriamt** [comment]
Ok, I'll try later to complete all the process to see if I have any other problem.

The step `Jane clones the repo to her machine using git clone.` Is it new? I think I didn't see there before and if it was I think I didn't do the last time.

**Comment by borekb** [comment]
Yes, it was there before. If you have three locations – your machine, remote server like GitHub and someone else's machine (Jane), you have to clone the repo to that third location.

**Comment by pavelevap** [comment]
`wp vp push` or `wp vp pull` should be used when target location is running site (with database, etc). When you start with simple site and want to share it through online repository (Github, Bitbucket), only `git push` is currently needed to push your site to repository (not running site). But you should use `wp vp pull` to get updates from this repository because target is now your local site (with database) and other functions should be applied during pull (maintenance mode, database sync).

I hope that it makes sense and sorry for troubles.

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
