### ISSUE TITLE
Updated option cron_time

### ISSUE THREAD

**Issue by vishalanandgit** [versionpress/support#135]
Installed a fresh version of VersionPress (version 4) on a clean bitnami powered aws install of wordpress(version 4.9.4). 

Under Versionpress - I am seeing continuous updates with following line: 
"Updated option cron_time"

This is not something that I need or rolled back. Did I do something wrong while installing? I also got an warning in system check before activating:
"VersionPress automatically tries to secure certain locations, like wp-content/vpdb. You either don't have a supported web server or rules cannot be enforced"

Platform details:
  'wordpress-version' => '4.9.4',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Linux ip-172-31-27-77 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64',
  'php-version' => '7.0.26',
  'php-sapi' => 'fpm-fcgi',
  'git-version' => '2.7.4',
  'git-full-path' => '/usr/bin/git
',
  'wp-cli-full-path' => 'wp',

**Comment by pavelevap** [comment]
Hi @vishalanandgit,

`cron_time` option is probably updated by any plugin? Plugins are not supported by default, but you can create custom definitions for particular plugin and ignore this option (see [docs](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md#ignoring-entities)) or add it to frequently ignored entities (see [docs](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md#frequently-written-entities)).

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
