### ISSUE TITLE
Issues creating staging site

### ISSUE THREAD

**Issue by vinoa-team** [versionpress/support#136]
Hi,

I recently installed Versionpress 4.0 on my Wordpress install. It is hosted on OVH shared server, website URL here: www.phytplus.com

I have successfully installed Versionpress, and used Command Line on my Mac to create staging. Here is the command I ran:
php wp vp clone --name=staging --siteurl=https://staging.phytplus.com --dbname=XXX --dbuser=XXX --dbpass=XXX --dbhost=XXX

The parameters marked XXX are working, I just replaced in this ticket.
I don't get much updates from vp, and after a short while, I get this warning message:
**Success: Site files cloned
The Git repo of this site already defines remote 'staging', overwrite it? [y/n]** 

I enter "y' and then get this error message:
**Error: Could not update remote's URL**

The staging site is copied into the staging folder, but the DataBase stuff doesn't seem to happen, as when I load the staging URL, I am prompted to install wordpress, and logging into phpMyAdmin I can see the database is completely empty.

What could be going wrong here ? 
Thanks in advance for your help

Thanks
Greg

**Comment by pavelevap** [comment]
Hi @vinoa-team,

it looks like your remote `staging` is already defined. Could you try to list your remotes with `git remote -v` and check it? Did you try to change name to `staging2` or something else?

I tried your example and even if staging remote is defined, I was able to change it without problems. Maybe there is any permission issue on your machine? Could you try to change remote path manually with `git remote set-url staging https://staging.phytplus.com`?

**Comment by vinoa-team** [comment]
Hi @pavelevap 
Thanks for the reply.
Some weord things happen here:
- list of remotes : the command `git remote -v` returns nothing at all. It immediately executes and gives me the next command line with nothing as a reply.
- Did I try changing it to something else like staging2 : yes, and I get the exact same behavior (remote already exists, and then can't change the remote URL
- finally: changing the remote URL manually: this also does not work and returns an error.

Few more comments: I am working with a server hosted by OVH, on a shared hosting plan. Not sure if this is relevant or not.

Also, the command wp vp clone didn't give me any intermediate updates such as "files copied" or "database created". I launch the command, and then nothing happens for a while (the files are copied, that I can se via FTP) and then I get the error messages described.

How can I check if I have the correct permissions? Could it be an issue here?

Also, something is slightly unclear to me: when I tried to clone the remote server content on a local git repository on my machine, the versionpress plugin doesn't get copied, as it seems to be ignored  by the .gitignore file. Is that normal ? How would I run a vp-restore site on my local machine once the file have been successfully downloaded using `git pull` if the versionpress plugin is absent ? 

Many thanks and sorry for any stupid questions above

Greg

**Comment by pavelevap** [comment]
As regards `vp restore-site`, please see our [docs](https://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site). Second (development) scenario is related to your example (restoring site from Git repository). You are right that `wp-content/plugins/versionpress` is not tracked (you have to install it manually) and also running `wp core config` is needed (`wp-config.php` is also not stored). But everything is explained in our docs. You will use only `git clone` for cloning a remote Github repository to your local computer. On the other hand `wp vp clone` is used for cloning site inside one environment (for example server).

So, you have a production site on OVH server (with VersionPress installed) and you want to create staging (on subdomain)? And you connected through SSH to server and `wp vp clone` does not work and you ran into errors from the first post?

**Comment by vinoa-team** [comment]
Hi,

Thanks for the additional info on clone and restore, that makes sense.

With regards to my first question: yes, I have a production server, and logging on it using SSH. So yes, I'm running a `wp vp clone` to create a staging environment, but have been running in the mentioned issues so haven't been able to create a working staging environment as of yet. 

Thanks
Greg

**Comment by pavelevap** [comment]
Hi @vinoa-team, did you manage to solve your issue with cloning? It looks like to me that it could be some kind of server restriction (or misconfiguration) related to your shared hosting.
