### ISSUE TITLE
.active disappear on restore-site error

### ISSUE THREAD

**Issue by zauker** [versionpress/support#138]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 4.0-beta
- WordPress version: 4.9.4
- OS, webserver, PHP: AMI Linux x86_64 / Apache / 5.6.2
- Git version: 2.7.4

If error occurred on `wp vp restore-site` command the file `wp-content/vpdb/.active` disappear and it seam there is not an active tracking.

for example if MySQL command are not in path the restore process will stop and .active file will be deleted.

**Comment by pavelevap** [comment]
Hi @zauker,

yes, `.active` file displays current VersionPress status (if it is active and if Git repo is created by VersionPress).

Did you have any problem with restoring site? Any particular errors?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
