### ISSUE TITLE
Cannot add menu items to wordpress menu

### ISSUE THREAD

**Issue by josh-skc** [versionpress/support#139]
VersionPress 4.0beta
WordPress 4.9.4
Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6/PHP 7.1.15
Git version 2.6.1

I'm having trouble adding items to the menu. I have tried on 2 sites now (the only 2 I had installed VersionPress on) and it seems that when VersionPress is active, pages cannot be added to my custom menu using the Appearance > Menus option. The little loading icon just keeps spinning (left for a few hours in the background). 

As soon as I deactivate the plugin the page adds within seconds, as it should. 

Have you come across this issue before? I wonder if it's theme related? Both websites are using the up to date version of BeTheme.

**Comment by pavelevap** [comment]
Hi @josh-skc,
I tried adding items to custom menu and it seems that everything works as expected.
Are there any messages in browser console?
Any PHP errors in logs?
It is possible some theme/plugin conflict, could you please try it with all plugins deactivated and Twenty Seventeen theme active?

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Comment by martinszy** [comment]
I'm seeing the issue, console shows:

```
[Tue Nov 19 18:11:07.524029 2019] [proxy_fcgi:error] [pid 11554:tid 140392129320704] [client 201.103.237.87:55134] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php:316\nStack trace:\n#0 /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php(316): serialize(Array)\n#1 /home/members/1/sites/betaweb/wp-content/plugins/versionpress/src/Git/Committer.php(294): VersionPress\\Git\\Committer->savePostponedChangeInfos(Array)\n#2 /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php(82): VersionPress\\Git\\Committer->postponeChangeInfo(Array)\n#3 /home/members/1/sites/betaweb/wp-content/plugins/versionpress/setup-hooks.php(259): VersionPress\\Git\\Committer->commit()\n#4 /home/members/1/sites/betaweb/wp-includes/class-wp-hook.php(288): {closure}(0, 8602)\n#5 /home/members/1/sites/beta...\n', referer: http://beta.1.org/wp-admin/nav-menus.php?menu=967
[Tue Nov 19 18:11:07.524321 2019] [proxy_fcgi:error] [pid 11554:tid 140392129320704] [client 201.103.237.87:55134] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php:316\nStack trace:\n#0 /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php(316): serialize(Array)\n#1 /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php(294): VersionPress\\Git\\Committer->savePostponedChangeInfos(Array)\n#2 /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php(82): VersionPress\\Git\\Committer->postponeChangeInfo(Array)\n#3 [internal function]: VersionPress\\Git\\Committer->commit()\n#4 {main}\n  thrown in /home/members/1/sites/beta/web/wp-content/plugins/versionpress/src/Git/Committer.php on line 316\n', referer: http://beta.1.org/wp-admin/nav-menus.php?menu=967

**Comment by martinszy** [comment]
- VersionPress version: 3.0
- WordPress version: 5.2.3
- OS, webserver, PHP: 7.2
- Git version: 2.11.0

**Comment by meostar** [comment]
I had same issue in Avada theme and after updating theme to newest version, issue resolved.
