### ISSUE TITLE
Incompatability with Wordfence during environment setup

### ISSUE THREAD

**Issue by captainhook** [versionpress/support#140]
- VersionPress version: 4.0beta and 4.0beta with merge of commits since release
- WordPress version: 4.9.4
- OS, webserver, PHP: Linux [retracted] 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64, CentOS, Plesk, PHP 7.2.3, Apache with Nginx proxy, fpm-fcgi
- Git version: 2.16.3

Just a heads up: I get Error 503 if I have Wordfence enabled. Deactivating Wordfence seems to allow the setup to complete.

Not sure what logs I can provide to help with this.

**Comment by pavelevap** [comment]
Please note that WordFence is also using custom tables and it is not supported by VersionPress by default (some data will not be tracked). You can follow our [documentation](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) to add support for this plugin.

I am closing this issue for now, please reopen if you have additional info or need further assistance.
