### ISSUE TITLE
Error: Maintenance mode couldn't be switched. Details:  sh: wp: command not found

### ISSUE THREAD

**Issue by oliver-lawrenz** [versionpress/support#141]
Hello, 

I'm using versionpress 4.0 on wordpress to connect my local installation and my staging.

| Field       | Value                               |
|--------|---------------|
| name        | versionpress                        |
| title       | VersionPress                        |
| author      | VersionPress                        |
| version     | 4.0-beta                            |
| description | Git-versioning plugin for WordPress |
| status      | active                              |

Everytime I try to use one of the following the commands "wp vp pull/push/apply-changes", I get the output:

```Error: Maintenance mode couldn't be switched. Details:  sh: wp: command not found```

It works fine on my local installation.

My git version is 2.7.4
My php version is PHP 7.1.11

**Comment by oliver-lawrenz** [comment]
Nevermind I got it. I just needed to change the path to the `wp-cli.phar` in the `VPCOmmandUtils` from`$cliCommand = VP_WP_CLI_BINARY . "$command";` to  `$cliCommand = "php wp-cli.phar $command";`

**Comment by pavelevap** [comment]
Hi @oliver-lawrenz,

please see related support issue: #81. Currently you can define absolute path to WP-CLI by using `VP_WP_CLI_BINARY` constant, see details here: https://github.com/versionpress/versionpress/issues/1186

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
