### ISSUE TITLE
How to install VP on a cPanel based site?

### ISSUE THREAD

**Issue by MarceloPedra** [versionpress/support#143]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 3.0.2
- WordPress version: 4.9.5
- OS, webserver, PHP: CentOS 7.5 with cPanel. PHP 7.0
- Git version: 1.8.3

I want to use your plugin in a cPanel server. But the bundled git version is 1.8.3. Is there any way I can force update it, or to make your plugin compatible with 1.8.3? Otherwise, VP cannot be used on cPanel servers without troubles. I really want to use VP. Help me please.

Thanks in advance!

**Comment by pavelevap** [comment]
Hi @MarceloPedra,

I am not familiar with your cPanel server configuration, but it should be possible to update Git.

But I found a related topic forum: https://forums.cpanel.net/threads/any-way-to-update-git-to-1-9-2-0-or-up.628655/

And it seems to me that you have 2 different Git installations and VersionPress identifies older version? In this case you can try to define `VP_GIT_BINARY` in `wp-config.php` with path to updated version (see [manual](https://docs.versionpress.net/en/getting-started/configuration#vp_git_binary)).

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you have additional info or need further assistance.
