### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Blathers** [versionpress/support#144]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 
- WordPress version:
- OS, webserver, PHP:
- Git version:

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by borekb** [comment]
Probably created by accident.

**Comment by Blathers** [comment]
Yup sorry about that, no idea how that happened - probably button mashed my phone!

**Comment by borekb** [comment]
No problem :)
