### ISSUE TITLE
Applying required access rules

### ISSUE THREAD

**Issue by philvallender** [versionpress/support#15]
Hi guys, 

I'm nearly there with activating VP on my EC2 instance. I just have to tick the access rules requirement. 

I have several problems:

1) I can't find any folder called /.git - I'm guessing the folder in question is not actually called this. Any pointers?

2) I don't find folders called /vpdb or /vpbackups either

3) I have a htaccess.conf file to which I can add rules for specific directories if I can find them. I can also see htaccess file in the versionpress plugin folder containing:

    # Apache 2.2
    <IfModule !mod_authz_core.c>
	Order Deny,Allow
	Deny from all
    </IfModule>

    # Apache 2.4
    <IfModule mod_authz_core.c>
	Require all denied
    </IfModule>

Which I guess deny direct access requests to that folder. 

So I think I only need to tackle the git folder issue. 

Thanks in advance for your help.

Cheers, Phil.

**Comment by philvallender** [comment]
Update, i ran the basic git config commands from https://help.ubuntu.com/lts/serverguide/git.html

Still had a warning on the VP dashboard but hit activate and it seems to be working.

**Comment by borekb** [comment]
Hi Phil, thanks for the report, just a couple of notes:

Access rules are a warning and will not stop activation, however, bear in mind that you might expose some sensitive information this way.

The `.git` folder is a hidden one.

Good luck!

**Comment by philvallender** [comment]
Thanks Borek - I'm up and running now. So I'll close this issue.

**Comment by borekb** [comment]
:+1:
