### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by tridoan** [versionpress/support#151]
Hi there,
This is a local test environment using local-by-flywheel. There is no data being displayed on the Versionpress dashboard, despite making a few content changes to test. There are no other plugins installed.
- VersionPress version: 4-beta
- WordPress version: 4.97
- OS, webserver, PHP: Apache, php7.1.4
- Git version: 2.1.4

![image](https://user-images.githubusercontent.com/1179626/43222944-5ee00b3a-9006-11e8-9244-dc0b18eea080.png)

Any suggestions on where to start troubleshooting, would be greatly appreciated. Thanks!

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by pavelevap** [comment]
Hi @tridoan,

could you look at your browser console (for example F12 on Chrome) if there are any related errors?

Did you check your PHP error logs (fatal errors, insufficient memory, etc)?

There is also special [docs page](https://docs.versionpress.net/en/troubleshooting/ui-not-loading/) for this situation.

**Comment by tridoan** [comment]
Hi @pavelevap , looks like it started working and starting to show changes. I think it just needed to give it time to pick up changes. Thanks for the response.
