### ISSUE TITLE
Plugin installation failed with 4.0-beta

### ISSUE THREAD

**Issue by robert1112** [versionpress/support#155]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 4.0-beta
- WordPress version: 4.9.8
- OS, webserver, PHP: ubuntu 16, nginx/1.15.3, 7.1.16
- Git version: N/A

You can get more details from your system info page: 

I cannot install. I prompt me the error below. Please Kindly help! Thanks.

```
VersionPress could not be activated
It seems that your copy of VersionPress was not built correctly. Please download release ZIP file from GitHub and install it again.
```

**Comment by borekb** [comment]
Please verify that the plugin was installed correctly, it seems that some files are missing from your installation:

https://github.com/versionpress/versionpress/blob/e2209836d30889727991365fde2c983d0121e5a1/plugins/versionpress/versionpress.php#L53-L67

**Comment by robert1112** [comment]
Hi @borekb 

Thanks for your reply. I download it from here 
https://github.com/versionpress/versionpress/releases/download/4.0-beta/versionpress-4.0-beta.zip

and upload and install from WP dashboard. Is it the correct file? I don't know what is missing step here? Thanks so much.

**Comment by robert1112** [comment]
Hi @borekb 

I noticed the zip file is not downloaded completely with Safari so downland with Chorme this time and it works. Thanks for your support.
