### ISSUE TITLE
Jetpack generating FAR TOO MANY changes in repository

### ISSUE THREAD

**Issue by traek** [versionpress/support#156]
Just installed VP. Running:
 - VP Version 4.0-beta
 - WP 4.9.8
 - Centos 7.5 running cPanel 74.0.6
 - Apache 2.4.34
 - PHP 7.2 (ea-php72)
 - Git version 2.18.0

Some type of heartbeat functionality in Jetpack is generating a disgusting amount of changes to my repository (see attached screenshot)
![jetpack_next_sync_time](https://user-images.githubusercontent.com/2188747/45516068-ddc0a980-b75e-11e8-988f-16750bf1adc6.png)

Now running for around 20 minutes, I have 6 pages of changes. 6!!!

My initial thought was to disable Jetpack but we are using Wordpress.com authentication for security purposes. Is anyone aware of what feature is updating this record so much? If not, can I ignore this record somehow? In the meantime I need to disable VP.

**Comment by borekb** [comment]
Hi @traek, this will be supported via [plugin definitions](https://docs.versionpress.net/en/developer/plugin-support/) in the future. Right now, you'd need to create a definition for Jetpack yourself (and ideally share it!), or wait as you suggested.

**Comment by pavelevap** [comment]
This could help (not tested):

- Create `schema.yml` file in `wp-content/.versionpress/plugins/jetpack` folder.

- Insert following lines to this file:

```
option:
  ignored-entities:
    - 'option_name: jetpack_next_sync_time_full-sync-enqueue'
```

**Comment by pavelevap** [comment]
I am closing this issue for now, please reopen if you need further assistance.

**Comment by michaeljaekel** [comment]
Hi, 
I just want to be sure:
Is  `wp-content/.versionpress/plugins/jetpack/schema.yml `still the right file to be updated?
I found `schema.yml` in `wp-content/plugins/versionpress/.versionpress/` with a lot of quite simular entries and entered 
    `- 'option_name: jetpack_next_sync_time_full-sync-enqueue'`
in here.

**Comment by pavelevap** [comment]
Hi, @michaeljaekel,

yes, file `wp-content/.versionpress/plugins/jetpack/schema.yml` is the best place, see related docs: https://docs.versionpress.net/en/developer/plugin-support/#discovery-mechanism

File `schema.yml` in `wp-content/plugins/versionpress/.versionpress/` is core VersionPress file and your changes there can be lost during plugin update.

**Comment by michaeljaekel** [comment]
Hi @pavelevap 
thank you. I will update the settings.
