### ISSUE TITLE
schema.yml for Advanced Custom Field PRO

### ISSUE THREAD

**Issue by zauker** [versionpress/support#158]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 4.0-beta-16-g2071052a
- WordPress version: 4.9.8
- OS, webserver, PHP: macOS High Sierra 10.13.6, Apache/2.4.25 (Unix),5.6.30
- Git version: 2.17.1

Hi all,
I have a question about ACF plugin and Schema.yml file.
With "Advanced Custom Field" I made a schema.yml as follow:

```yml
postmeta:
  value-references:
    meta_key@meta_value:
      hp_mainbuttons_sx_icon: post
      hp_mainbuttons_sx_bg_image: post
```
and it works fine

I upgraded ACF to PRO version and new type of fields are available like `flexible_content` or `repeater`.

If I configure a field "flexible" and if it has a "repeater" field I could have the meta key with the follow structure:
`flexible_field_id` + NR + `field_id` (for non repeater)
`flexible_field_id` + NR + `repeater_field_id` + NR + `field_id`
i.e.
assuming to have a flexible_content with id `components` and one layout `two_column` with this field:
Text: `two_column_text` (text)
Image: `two_column_image` (image)
Content: `two_column_content` (repeater)
    Title: `content_title` (text)
    Image: `content_image` (image)

The meta key are stored as:
`components_0_two_column_image`
`components_0_two_column_content_0_content_image`

**How must edit `schema.yml` for detect all `content_image` ??**

is it possible use something like this to catch the field?
```regex
^\w+content_image$
```

**Comment by borekb** [comment]
Hi @zauker , sorry for a late response, have you been able to find out more about this? To me, it looks like a feature that might not be supported in plugin definitions yet, unfortunately.

**Comment by zauker** [comment]
Hi @borekb I didn't yet have no time to investigate. If someone of the developer team could show me the point where the wildcards are handled maybe I could try to add the support for these kinds of meta_key.

**Comment by zauker** [comment]
hi @borekb I investigate and I see that the regex used for wildcard allow the asterisk sign at start, end or middle of source name.
[(regex example)](https://regex101.com/r/tC8zD4/3)

So for my need I put into schema.yml something like this:
```yml
postmeta:
  value-references:
    meta_key@meta_value:
      components_*_content_image: post
```

to detect field like:
`components_0_two_column_content_0_content_image`

One thing I didn't know was that to apply the new rules set in the schema.yml file it was necessary to save the affected contents again.
I believed that the association of the reference ID happened during the pull phase, while it seems that it is applied directly to the saving of the individual posts.

I updated the schema.yml, saved the affected contents, and now the pull from another environment works fine.

thanks for your support

**Comment by borekb** [comment]
Great that you got it sorted! I'm going to close this issue now, feel free to reopen of file a new one if there's anything new. Thanks!
