### ISSUE TITLE
Database errors during cloning process

### ISSUE THREAD

**Issue by digitalartworks** [versionpress/support#16]
wp vp clone --name=dev --siteurl=https://dev.xxx.pl --debug

Debug: No readable global config found (0.006s)
Debug: No project config found (0.007s)
Debug: ABSPATH defined: /var/www/xxx/prod/ (0.008s)
Debug: Begin WordPress load (0.008s)
Debug: wp-config.php path: /var/www/xxx/prod/wp-config.php (0.008s)
Debug: Loaded WordPress (0.566s)
Debug: Running command: vp clone (0.567s)
Success: Site files cloned
The Git repo of this site already defines remote 'dev', overwrite it? [y/n] y
Success: Updated remote configuration
Success: Enabled pushing to the original repository
Success: Enabled pushing to the clone
Success: wp-config.php updated
Success: Copied VersionPress
Success: Database tables created
Success: VersionPress tables created

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE meta_id=(SELECT id FROM wp_dev_vp_id WHERE vp_id=UNHEX("71798F1DC06E4FD7A3' at line 1 for query UPDATE wp_dev_postmeta SET meta_value= WHERE meta_id=(SELECT id FROM wp_dev_vp_id WHERE vp_id=UNHEX("71798F1DC06E4FD7A384827A5813371C")) made by include('phar:///usr/local/bin/wp-cli.phar/php/boot-phar.php'), include('phar:///usr/local/bin/wp-cli.phar/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll, VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks, VersionPress\Synchronizers\SynchronizerBase->synchronize, VersionPress\Synchronizers\SynchronizerBase->fixSimpleReferences, VersionPress\Synchronizers\SynchronizerBase->fixValueReferencesOfOneEntity

...and above error several times...

Success: Database synchronized
Success: All done. Clone created here: ....

cloned site works but there are database issues

**Comment by JanVoracek** [comment]
Hi. Thanks for flagging. 
We're familiar with this bug. The fix will be part of 3.0 release.

**Comment by FlorinOprina** [comment]
I'm having the same problem when cloning the site --- does this mean we can't use the plugin until version 3? Is there a workaround?

**Comment by JanVoracek** [comment]
Hi. Here's quick'n'dirty fix. 

You can replace method `parametrize` in `wp-content/plugins/versionpress/src/Utils/ArrayUtils.php` with this code:
``` php
    public static function parametrize($array) {
        $out = array();
        foreach ($array as $key => $value) {
            if (empty($value)) {
                $out[] = "$key=''";
            } else {
                $out[] = "$key=$value";
            }
        }
        return $out;
    }
```

**Comment by FlorinOprina** [comment]
Seems to have done the trick.Thank you!
