### ISSUE TITLE
Support for WP Engine platform?

### ISSUE THREAD

**Issue by crstauf** [versionpress/support#162]
I seem to recall an announcement of a partnership with WP Engine to get VersionPress working on their system...?

Has there been any progress made on/with that? VersionPress is listed as a [disallowed plugin](https://wpengine.com/support/disallowed-plugins/) currently due to a server level function being blocked for security purposes.

We nearly always recommend WP Engine to our clients, but we're also very anxious to use VersionPress (aware that VP is in developer preview status).

**Comment by crstauf** [comment]
Must've been a dream then. 😇 

They do talk about VP in their resource articles... maybe that's where I got the thought from.

**Comment by borekb** [comment]
That might be it. Let me close this issue then, feel free to post back if you learn something from their support.
