### ISSUE TITLE
Cloning in non-standard folder structure

### ISSUE THREAD

**Issue by philvallender** [versionpress/support#17]
My wordpress is installed at /wordpress/htdocs but when I run wp vp clone, it creates the clone at /wordpress and I can't seem to pass a path - special characters are rejected. Is there a workaround for creating a clone in a subdirectory?

**Comment by JanVoracek** [comment]
Hi, Phill. Custom folder structures will be partially supported in 3.0 release. 

Currently, the only supported structure would look like this:
```
wordpress
└── htdocs
    └── your-site
        ├── wp-admin
        ├── wp-content
        └── wp-includes
```

**Comment by philvallender** [comment]
Hi Jan, 

Thanks for replying. Any ETA on V3? 

Thanks, Phil.

**Comment by borekb** [comment]
Hi Phil, we wanted v3 to be available this month but March is more likely. Thanks, B.
