### ISSUE TITLE
Conflict with EDD PayPal standard gateway

### ISSUE THREAD

**Issue by philvallender** [versionpress/support#19]
Hi Guys, 

I've just discovered that there is a conflict between VP and Easy Digital Downloads that disables the standard PayPal gateway. I've reported this to EDD and thought you should know too. 

Cheers, Phil.

**Comment by borekb** [comment]
EDD will not be supported anyway as it creates custom tables -- those will be supported later this year (not in v3, unfortunately).

**Comment by pavelevap** [comment]
@philvallender: Hi Phil, I am also using VersionPress with EDD, but I did not notice any similar issue during payment? Do you have any screenshot or error message? Did you get any answer from EDD team? Thank you!

**Comment by philvallender** [comment]
Hi @pavelevap, there is no error message but on both my online instance and on serverpress version, PayPal was inoperative (button says please wait but nothing happens) and disabling VP (on the serverpress version) made it work again instantly. Will try same on AWS now.
