### ISSUE TITLE
Activation Error

### ISSUE THREAD

**Issue by georgeolaru** [versionpress/support#2]
I'm using the AMPPS local server (PHP 5.3) and I'm receiving this error upon activation:

`Fatal error: Uncaught exception 'Nette\NotSupportedException' with message 'PHP extension Tokenizer is not loaded.' in /Applications/AMPPS/www/wordpress-installation/wp-content/plugins/versionpress/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php:54 Stack trace: #0 /Applications/AMPPS/www/wordpress-installation/wp-content/plugins/versionpress/bootstrap.php(21): Nette\Loaders\RobotLoader->__construct() #1 /Applications/AMPPS/www/wordpress-installation/wp-content/plugins/versionpress/versionpress.php(37): require_once('/Applications/A...') #2 /Applications/AMPPS/www/wordpress-installation/wp-admin/plugins.php(156): include('/Applications/A...') #3 /Applications/AMPPS/www/wordpress-installation/wp-admin/plugins.php(158): plugin_sandbox_scrape('versionpress/ve...') #4 {main} thrown in /Applications/AMPPS/www/wordpress-installation/wp-content/plugins/versionpress/vendor/nette/robot-loader/src/RobotLoader/RobotLoader.php on line 54`

**Comment by borekb** [comment]
Is AMPPS doing something special? The Tokenizer extension should be [enabled by default](http://php.net/manual/en/tokenizer.installation.php) since 4.3.0. Can you please enable this extension manually?

**Comment by georgeolaru** [comment]
I just enable it manually and it's working great — Thanks!
