### ISSUE TITLE
Locks up on activation

### ISSUE THREAD

**Issue by Type2Designs** [versionpress/support#20]
VersionPress Activation
Setting things up for you. It may take a while, please be patient.

Starting up
Helper database tables created

________________________________________

System Info Page:
Quick summary
array (
  'wordpress-version' => '4.2.7',
  'versionpress-version' => '2.2',
  'operating-system' => 'Linux  2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64',
  'php-version' => '5.6.17',
  'php-sapi' => 'cgi-fcgi',
  'custom-vp-config' => 
  array (
    'git-binary' => '/usr/local/git/bin/git',
  ),
  'git-version' => '1.9.4',
  'git-full-path' => '/usr/local/git/bin/git',
)
Git
array (
  'git-binary-as-configured' => '/usr/local/git/bin/git',
  'git-available' => true,
  'git-version' => '1.9.4',
  'git-binary-as-called-by-vp' => '/usr/local/git/bin/git',
  'git-full-path' => '/usr/local/git/bin/git',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => true,
)
Permissions
array (
  'exec-user' => 'type4',
  'proc_open-user' => 'type4',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)

**Comment by Type2Designs** [comment]
After clicking activation the page thinks awhile and then stops. It never updates the page, the site goes offline but then comes online after while by itself. Going back to the versionpress page shows the activate page again.

___________________________________________________________________________
System requirements check
PHP 5.3
Execute external commands
Git 1.9+ installed
Write access on the filesystem
wpdb hook
Not multisite
Standard directory layout
.gitignore
Access rules can be installed
VersionPress automatically tries to secure certain locations, like wp-content/vpdb. You either don't have a supported web server or rules cannot be enforced. Learn more.

Web size
The initialization will take a little longer. This website contains 87465 entities, which is a lot.

External plugins
You run 17 external plugins we have not tested yet. Read more about 3rd party plugins support.

**Comment by borekb** [comment]
Hi, sorry for the late reply but it just seems that your site is too complex for VersionPress to handle. Supporting various plugins and larger sites will be an ongoing effort this year and beyond.
