### ISSUE TITLE
VersionPress is installed but not yet tracking site

### ISSUE THREAD

**Issue by shwetamukta** [versionpress/support#22]
Hello,
I wanted to add VersionPress plugin in my E-commerce Website but I am getting error when I tried activating VersionPress 2.2 plugin in my site. I have git version 2.7.2 in my system but it is throwing following error. Due to this I am not able to activate VersionPress in my Website. Can some one suggest what is wrong here?

Error:
Git 1.9+ installed

Git version 1.7.9.5 detected with which there are known issues. Please install at least version 1.9 (this can be done side-by-side and VersionPress can be configured to use that specific Git version). Learn more.

**Comment by borekb** [comment]
VersionPress works with Git 1.9 or greater, you have 1.7 as per the message. Please upgrade.

Also please note that VersionPress might not yet be compatible with your e-commerce plugin. Plugin compatibility is tough and we'll be improving it later this year.

**Comment by shwetamukta** [comment]
Hi Borek,
I have latest version of git (2.7.2).
It is giving me wrong message saying I have 1.7 version of git installed in
my system.
I have downloaded and installed it multiple times but I am still facing
same issue.
I have faced the same issue when I was working in my office for another
wordpress website. There also I have latest version of git (2.7.2). I am
working locally there.

Please advise.


Thanks,
Shweta Mukta

On Sat, Mar 5, 2016 at 8:43 PM, Borek Bernard <notifications@github.com>
wrote:

> VersionPress works with Git 1.9 or greater, you have 1.7 as per the
> message. Please upgrade.
>
> Also please note that VersionPress might not yet be compatible with your
> e-commerce plugin. Plugin compatibility is tough and we'll be improving it
> later this year.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/versionpress/support/issues/22#issuecomment-192613810>
> .
>



-- 
Regards,
Shweta Mukta

http://shwetamukta.com/

**Comment by borekb** [comment]
This usually happens if the web server runs under a different user than what you are logged in as. Could you please provide more details about your installation? [System Info page](http://docs.versionpress.net/en/troubleshooting/system-info-page) output would be great.

**Comment by shwetamukta** [comment]
Hi Borek,
The issue has been resolved.
My proc_open() was disabled, When I enabled it, VersionPress started
working.


Thanks,
Shweta Mukta

On Sun, Mar 6, 2016 at 9:09 PM, Borek Bernard <notifications@github.com>
wrote:

> This usually happens if the web server runs under a different user than
> what you are logged in as. Could you please provide more details about your
> installation? System Info page
> <http://docs.versionpress.net/en/troubleshooting/system-info-page> output
> would be great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/versionpress/support/issues/22#issuecomment-192866250>
> .
>



-- 
Regards,
Shweta Mukta

http://shwetamukta.com/

**Comment by borekb** [comment]
Great! Thanks for letting us know.

**Comment by bomakalu** [comment]
Hi there and thanks for this.
AS I have limited experience the updating git has been a real problem 
I cant install a use this plugin as the server has git version 1.8.3.1 
Any pointers ideas for a newbie in this area:

Git
array (
  'git-binary-as-configured' => 'git',
  'git-available' => true,
  'git-version' => '1.8.3.1',
  'git-binary-as-called-by-vp' => 'git',
  'git-full-path' => '/bin/git
',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => false,
)

need some kind of tutorial etc on updating and pointing the latest git version.
thanks for the help

**Comment by borekb** [comment]
As for updating Git, that will depend on your system, try asking on a user forum or something like that.

As for setting the VP config value, see [this docs page](https://docs.versionpress.net/en/getting-started/configuration#vp_git_binary).

**Comment by bomakalu** [comment]
thanks borkb 
sadly now i am getting stalled I have it all configured as re required
i am getting the barber shop waiting / loading symbol over the 
> date : message on the versionpress page?

thanks
