### ISSUE TITLE
Clone results in "The page isn't redirecting properly"

### ISSUE THREAD

**Issue by 650hours** [versionpress/support#24]
I ran this command as per the instructions on your wiki:

wp vp clone --siteurl=http://smartipx.dev.650h.co.uk --dbname=dev_smartIPX --dbuser=*** --dbpass=*** --name=smartIPX

And set-up the Apache vhost config file as follows (which is a normal set-up for all our sites):

---
<VirtualHost 134.213.154.6:80>
        ServerName smartipx.dev.650h.co.uk
        ServerAdmin webmaster@650hours.com
        DocumentRoot /web/smartIPX
        <Directory /web/smartIPX>
                Options -Indexes +FollowSymLinks +MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
                #Include /etc/apache2/include.d/devSite.conf
        </Directory>
        # Possible values include: debug, info, notice, warn, error, crit, alert, emerg.
        LogLevel warn
        ErrorLog /wlog/smartipx.dev.650h.co.uk/error.log
        CustomLog /wlog/smartipx.dev.650h.co.uk/access.log combined
        # Hide source control folders
        RedirectMatch 404 /\\.(hgignore|hg|svn|git)(/.*|$)
</VirtualHost>
---

I have made no changes to the code. The htaccess is standard WP:

---
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
---

Normally our dev sites are password protected, but I have opened this one up so you can see the error - http://smartipx.dev.650h.co.uk/

Can you assist please?

**Comment by borekb** [comment]
It is redirecting to `http://smartipx.dev.650h.co.uk/smartipx-partner-cataleyas-orchid-one-achieves-miercom-performance-verified-certification/smartipx-sliders-yoga-flip-shade/`, any idea why it would do that?

**Comment by barkermn01** [comment]
@borekb 
The only way a redirection can occur like that is threw wordpress is the the PHP function <code lang="php">header("Location: ")</code> so something is causing a redirect to that page  

As this is a clone we could say the original worked before version press so what could cause that with Version press perhaps and unsupported redirection extension has been messed up by version press? just a though

**Comment by borekb** [comment]
@barkermn01 Could you try to find in the code of the site what could be causing this redirect? Then we could check if that's something VersionPress could have messed with. Thanks.

**Comment by 650hours** [comment]
@borekb http://www.smartipx.com/smartipx-partner-cataleyas-orchid-one-achieves-miercom-performance-verified-certification/smartipx-sliders-yoga-flip-shade/ exists and works (this is the site that was cloned) whereas http://smartipx.dev.650h.co.uk/smartipx-partner-cataleyas-orchid-one-achieves-miercom-performance-verified-certification/smartipx-sliders-yoga-flip-shade/ does not work.

I am not sure what it is you want us to look for in the code that may be causing the redirect. Certainly the uncloned site doesn't do this. Any suggestions as to what to look for?

**Comment by borekb** [comment]
@650hours Something is redirecting that URL to `/` and then root back to that page, see this:

![2016-03-23 15_37_57-mozilla firefox](https://cloud.githubusercontent.com/assets/101152/13988672/49d28f82-f10d-11e5-8a16-fe2b2d3dff57.png)

Can you find out what can be causing this redirect? It might be a web server rule, some PHP code or something else.

**Comment by pavelevap** [comment]
@650hours: Hi, could you please log into administration of cloned site and check `Settings - Reading` if `Front page` and `Posts page` are correctly set up? There are known problems with this feature in VP 2.2.

**Comment by 650hours** [comment]
@pavelevap - I changed the "Front page" setting to "A static page" selecting "Home" as the Front page. I checked the live site and left the "Posts page" unselected, same as the live site.

http://smartipx.dev.650h.co.uk/ is now working, although images are missing (compare to http://www.smartipx.com/) - so we're making progress. Any thoughts on the images?

**Comment by pavelevap** [comment]
@650hours: Sorry, you are probably using Visual Composer (VC) which is not supported yet, see #26.

When you insert for example single image with the help of VC then it is saved as following shortcode:

`[vc_single_image image="1434"]`

Number `1434` is ID of file from WordPress Media library, but it is not referenced by VersionPress yet. So VersionPress does not know that this number is ID of any existing entity (and should be replaced by global VPID). In VersionPress 3.0 (coming soon) there will be basic support for WordPress core shortcodes and other improvements for plugins and themes will be implemented later this year.

**Comment by 650hours** [comment]
Thanks @pavelevap @borekb - do you have a roadmap for this (other than the very basic list on http://docs.versionpress.net/en/release-notes/roadmap)? Something we can work with as cloning is a key function for us and the reason we signed up for Early Access Pro.

**Comment by borekb** [comment]
@650hours In the v4 release which should be out later this summer, there'll be a system that the 3rd party plugins / themes will be able to hook into and provide description for their pieces of data. VersionPress will consume these descriptions and start supporting such plugins similarly to how we support WP core today.

We'll likely provide the definitions for the most popular plugins ourselves but the system will be open to anyone, meaning that you will be able to describe e.g. Visual Composer before we get to it. Or maybe you'll get lucky and someone will do it before you :) Again, summer is the current rough estimate when this could be available.
