### ISSUE TITLE
Error when trying to clone site

### ISSUE THREAD

**Issue by slickorange** [versionpress/support#27]
I get multiple errors like the one below when I am trying to clone my site...
Any ideas? 

`WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE meta_id=(SELECT id FROM wp_test_vp_id WHERE vp_id=UNHEX("AA9FA8F0064341658' at line 1 for query UPDATE wp_test_postmeta SET meta_value= WHERE meta_id=(SELECT id FROM wp_test_vp_id WHERE vp_id=UNHEX("AA9FA8F006434165854273D6C37085B7")) made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll, VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks, VersionPress\Synchronizers\SynchronizerBase->synchronize, VersionPress\Synchronizers\SynchronizerBase->fixSimpleReferences, VersionPress\Synchronizers\SynchronizerBase->fixValueReferencesOfOneEntity
`

**Comment by slickorange** [comment]
I have now implemented the fix listed here: https://github.com/versionpress/support/issues/16

Cloning completes until: `Success: All done. Clone Created here"`

Then I get:
```
Path:   /home/wonka/development/wonka/wordpress/test
URL:    http://development/test
[23898:23898:0331/083640:ERROR:navigation_entry_screenshot_manager.cc(141)] Invalid entry with unique id: 126
```
My new clone is working, but all the links, and the admin login still redirects to the original site.

**Comment by pavelevap** [comment]
@slickorange: Hi, could you please share some more details? Your cloned site is in `/home/wonka/development/wonka/wordpress/test` directory and where is your original site located? And what about `siteurl` for original and cloned site?

Did you use `--siteurl` param for [wp vp clone](http://docs.versionpress.net/en/sync/cloning)?

**Comment by slickorange** [comment]
I apologize, I have just realized that my wp-config file was still overriding the URL.
