### ISSUE TITLE
Error when running "restore-site"

### ISSUE THREAD

**Issue by slickorange** [versionpress/support#28]
I get the following error when I try to run `wp vp restore-site`:

`PHP Fatal error:  Cannot redeclare wp_unregister_GLOBALS() (previously declared in /development/wordpress/wp-includes/load.php:17) in /development/wordpress/wp-includes/load.php on line 31`

**Comment by pavelevap** [comment]
@slickorange: Hi, one possible reason is custom code in `wp-config.php` file because WP-CLI has sometimes problems to parse it, see for example here: https://github.com/wp-cli/wp-cli/issues/1631

What is your WordPress and WP-CLI version?

**Comment by slickorange** [comment]
Hi @pavelevap, I have now made sure that WP-CLI and Wordpress is updated to the latest version. I have also deleted my wp-config.php file and generated a new one with WP-CLI. It is still not giving me the same error.

**Comment by pavelevap** [comment]
And what is your WordPress and WP-CLI version? 4.4.2 and 0.23.0?

Do you want to restore database or the whole site from Git repo? Could you paste here the whole `wp vp restore-site` command? Please note that in some cases `--require` param is [needed](http://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site).

**Comment by borekb** [comment]
Closing until we get the info. @slickorange, feel free to reopen. Thanks.
