### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by bankerrahul** [versionpress/support#30]
Warning: require_once(/public_html/wppartners.io/wp-content/plugins/versionpress/vendor/autoload.php): failed to open stream: No such file or directory in /public_html/wppartners.io/wp-content/plugins/versionpress/bootstrap.php on line 57

**Comment by borekb** [comment]
Could you please provide steps to reproduce, i.e., what you did to get to this state? Thanks.

**Comment by bankerrahul** [comment]
I just downloaded the zip from the repo, 

- extracted the zip
- navigated to versionpress/plugins
- compressed the plugin folder
- On the site : plugins > add new
- uploaded the zip file
- throws out this error while trying to activate the plugin

Thanks

**Comment by pavelevap** [comment]
Hi, did you download `versionpress-3.0-beta.zip` from [releases](https://github.com/versionpress/versionpress/releases) section?

**Comment by borekb** [comment]
![image](https://cloud.githubusercontent.com/assets/101152/14344476/27bfe330-fca8-11e5-9244-4ea82445b55f.png)

**Comment by bankerrahul** [comment]
That worked. Thank you so much.

**Comment by borekb** [comment]
Any ideas on how we could make the experience better? I understand that clicking the _Download ZIP_ button in the repo root is tempting..

**Comment by bankerrahul** [comment]
That is perfectly alright. I understand that the main repo is always on development and includes some broken things and bugs :) I am going to test this on a few websites of ours and write you back before this weekend!

**Comment by borekb** [comment]
Thanks.
