### ISSUE TITLE
standard WordPress directory layout

### ISSUE THREAD

**Issue by arnauldb** [versionpress/support#31]
Hello,

what do you mean by :Standard directory layout

It's necessary to use standard WordPress directory layout with the current version of VersionPress.

Thanks for help,

Arnauld

**Comment by borekb** [comment]
Hi, it means that the site should have the layout that you get when you install WordPress without any customizations; VersionPress 2.0 required that.

VersionPress 3.0 supports certain directory layout customizations, see https://github.com/versionpress/versionpress/issues/565.

**Comment by arnauldb** [comment]
ok, thank you.



Arnauld Bordes

facebook <https://www.facebook.com/arnauld.bordes>  twitter
<https://twitter.com/arnauld>  GPG key
<https://www.dropbox.com/s/k90ojdt0o80m63l/arnauld%20arnauld%40gmail.com%20%280x4D0A26DB%29%20pub.asc?dl=0>

mon blog superprofenchine <http://www.superprofenchine.fr/>

arnauld@protonmail.ch
