### ISSUE TITLE
not working with git version 2.5.3

### ISSUE THREAD

**Issue by morinoalaria** [versionpress/support#32]
I just installed a later version of git, 2.5.3, onto my VPS (on Bluehost, it's CentOS 6.7). I'd originally had 1.7.1 installed, so when I tried to VP, it didn't let me install because I didn't have at least version 1.9.

Now it says this:
Git version detected with which there are known issues. Please install at least version 1.9 (this can be done side-by-side and VersionPress can be configured to use that specific Git version).

Note that it doesn't say which version of git I have.

So is VP not compatible with that late a version of git? Should I just downgrade to 1.9?

**Comment by JanVoracek** [comment]
Hi, I use VersionPress with Git 2.6.4 without problems.

It is possible that the old version of Git is still the first one in PATH and VersionPress uses it.
You can check our _system info_ page – `<your site>/wp-admin/admin.php?page=versionpress/admin/system-info.php`
The Git section should contain a path to the Git 2.5.3. If it doesn't, it is possible to define a constant `VP_GIT_BINARY` with a correct path in your `wp-config.php`.

**Comment by morinoalaria** [comment]
Had no idea the system-info page existed, thank you. :) 

I must have done something wrong because this is what I'm seeing:

`array (
  'git-binary-as-configured' => 'git',
  'git-available' => false,
  'output' => 
  array (
    'stdout' => '',
    'stderr' => 'sh: git: command not found',
  ),
  'env-path' => '/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/lib/courier-imap/sbin:/usr/lib/courier-imap/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin',
)`

**Comment by borekb** [comment]
Are you using VersionPress 3.0-beta or 2.2?

**Comment by morinoalaria** [comment]
2.2

**Comment by borekb** [comment]
Then you need to use `vpconfig.neon` as described [here](http://docs.versionpress.net/en/getting-started/configuration#git-binary). Or, switch to 3.0-beta which we would recommend at the moment.

**Comment by morinoalaria** [comment]
I tried switching to 3.0 but I'm unfortunately running an older version of
php so it wouldn't work. I was able to use vpconfig.neon to get it running,
thanks so much for the help!

--
Jamie Klenetsky Fay
Singer, Composer, Designer
http://jamieklenetsky.com
http://newmusicnj.com
