### ISSUE TITLE
Updating Git to 1.9.0 on GoDaddy Shared Linux hosting (cPanel) to support Versionpress 2.2

### ISSUE THREAD

**Issue by unadventurer** [versionpress/support#33]
- VersionPress version: 2.2
- WordPress version: 4.5
- OS, webserver, PHP: GoDaddy Shared Linux Web Server, PHP 5.4
- Git version: Currently 1.7.1

I've SSH'd into my server and I've followed these commands to install the latest version of git:
https://gist.github.com/AddoSolutions/9694163

`cd ~`
`wget http://git-core.googlecode.com/files/git-1.9.0.tar.gz`
`tar zxvf git-1.9.0`
`cd git-1.9.0`
`./configure --prefix=/home/$USER`
`make`
`make install`
`echo 'PATH=$PATH:$HOME/bin' >> $HOME/.bashrc`
`source $HOME/.bashrc`
`cd ..`
`rm -rf ~/git-1.9.0 ~/git-1.9.0.tar.gz`

Any reason these commands wouldnt make 1.9.0 the default install of git so I can get VP up and running?

If you have any suggested tutorials or knowledge docs on this.. it would be much appreciated!

**Comment by borekb** [comment]
@unadventurer Git in the correct version must be in a PATH for the web server user (that's not necessarily the same user under which you SSH in). If this cannot be updated easily, you can use the [`git-binary` config option](http://docs.versionpress.net/en/getting-started/configuration#git-binary) of VersionPress.

**Comment by unadventurer** [comment]
Thank you! I'll trying this later. GoDaddy has been testing my patience. I was able to install the correct version of git in my own dir on my server so I'll try to point it to this when I sit down to work on this later.

**Comment by unadventurer** [comment]
How can I check to see if the git dir where I pointed WP to is seeing it correctly? I can't seem to find any git specific commands for wp-cli... When I refresh my admin page to activate versionpress it still sees the older version of git (1.7.1) 
![2016-04-26 15_48_44-166 62 77 42 - putty](https://cloud.githubusercontent.com/assets/18488882/14836640/6b79c6a4-0bc6-11e6-9b7e-76f59aa39b5c.png)

**Comment by borekb** [comment]
You can find it in the [System Info](http://docs.versionpress.net/en/troubleshooting/system-info-page) page.

BTW those WP-CLI commands look really weird, for example, `$HOME` will not expand when you enclose it in single quotes. The simplest thing to try is to put a `VP_GIT_BINARY` constant into your `wp-config.php`.

**Comment by unadventurer** [comment]
Ah OK that's helpful.. Does this look better? WP is installed in public_html/ and the git-1.9.0 folder is in the root dir.. would it be helpful to move that git folder into public_html? I guess I'm not sure I understand how I'd add the consonant to wp-config.php to get it to work.
![2016-04-26 16_15_13- buy it fire wordpress](https://cloud.githubusercontent.com/assets/18488882/14837069/2e9754c8-0bca-11e6-9e2f-f9fabaf77710.png)

**Comment by unadventurer** [comment]
I added this to wp-config.. Is this what you meant?

![2016-04-26 16_33_09-greenshot image editor](https://cloud.githubusercontent.com/assets/18488882/14837394/b8967512-0bcc-11e6-8c21-9b741613d4b2.png)

**Comment by borekb** [comment]
Yes, something like that, and revert all your previous attempts :) It would be best to first try in an environment that you know well and can fully control, only then move to GoDaddy.

**Comment by moashraf** [comment]
d

**Comment by CesarAntolinez** [comment]
the next command does not work for me
./configure --prefix=/home/$USER
