### ISSUE TITLE
"Git 1.9+ installed"

### ISSUE THREAD

**Issue by HammyHavoc** [versionpress/support#34]
I installed the VersionPress 3.0 Beta and was presented with this error: "Git 1.9+ installed"

- VersionPress version: 3.0 Beta
- WordPress version: 4.5
- OS, webserver, PHP: centOS 5, PHP 5.6.19
- Git version: 2.8.1

**Comment by HammyHavoc** [comment]
More info:

array (
  'wordpress-version' => '4.5',
  'versionpress-version' => '3.0-beta',
  'operating-system' => 'Linux splitanatom.com 2.6.32-042stab093.5 #1 SMP Wed Sep 10 17:39:49 MSK 2014 x86_64',
  'php-version' => '5.6.19',
  'php-sapi' => 'cgi-fcgi',
  'git-version' => '',
  'git-full-path' => '',
)
Git
array (
  'git-binary-as-configured' => 'git',
  'git-available' => false,
  'output' => 
  array (
    'stdout' => '',
    'stderr' => 'sh: git: command not found',
  ),
  'env-path' => '/sbin:/usr/sbin:/bin:/usr/bin',
)
Permissions
array (
  'exec-user' => 'omgoblin',
  'proc_open-user' => 'omgoblin',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)

**Comment by borekb** [comment]
Can you try setting [VP_GIT_BINARY](http://docs.versionpress.net/en/getting-started/configuration#vp_git_binary) config option if that helps?

**Comment by someguy9** [comment]
Just a note (that probably should be added to the doc) but the global user.name and user.email must be set for versionpress to work from what I've seen.

git config --global user.name "your name"
git config --global user.email "email@email.com

**Comment by devonblzx** [comment]
Just a note for others, I received this error because the VP_GIT_BINARY was set from another environment but that binary did not exist on my local env.
