### ISSUE TITLE
Fatal error on activation attempt 

### ISSUE THREAD

**Issue by mweb-marathon** [versionpress/support#37]
- VersionPress version: 3.0 beta zip
- WordPress version: 4.3.1
- OS, webserver, PHP: RHEL aws 5.3
- Git version: 2.7.4

Hi, 

Used wget to download the 3.0 beta zip on my server. extracted in plugins directory, logged into wp-admin and tried to activate and get the following error " 
Parse error: syntax error, unexpected '[' in /export/dev.websitename.com/htdocs/wp-content/plugins/versionpress/versionpress.php on line 516 "

Thanks!

**Comment by borekb** [comment]
Hi, PHP 5.6 is required for VersionPress 3.0, see https://github.com/versionpress/versionpress/issues/726. Can you upgrade your server please?

**Comment by mweb-marathon** [comment]
will do, thanks.
