### ISSUE TITLE
CHMOD errors

### ISSUE THREAD

**Issue by meadow19** [versionpress/support#38]
Hello,

I have a similar problem.

I am using a standard Ubuntu16.04 image with ServerPilot.io on top, with Letsencrypt.org certificates. Then I installed the latest version of Wordpress. 

That's it.

Now, I tried to install Versionpress 3.0, but Wordpress didn't let me upload the plugin. I don't have FTP or FTPS installed on the server it seems. So I had to copy manually via SFTP into the plugins folder.

Now, the Versionpress 'check procedure' was all fine, all ticked. But when I installed it, for a second or two it showed a few lines about chmod errors. I didn't get time to read them, because after a second, the page refreshed and the standard Versionpress page showed.

Now I'm worried that Versionpress is not working correctly. How do I check? There doesn't seem to be a way to go back and check the error messages. Thank you kindly for your help.

**Comment by meadow19** [comment]
Ah, I just leaned how to check the hidden admin page.
Here's what I get for permissions:
I think everything seems okay?

array (
  'exec-user' => 'serverpilot',
  'proc_open-user' => 'serverpilot',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)

**Comment by JanVoracek** [comment]
Hi, it looks fine but I would check the webserver's log file for the chmod errors if you have an access to it. Just to be sure.

**Comment by meadow19** [comment]
Thank you Jan.
I do have root access. 
I checked the apache and nginx error log files, but I can't see anything about chmod errors in them.

It also seems that now my wordpress installation is 'jammed'. I can't activate or deactivate, or remove any plugins or themes. It just stalls, with no error messages until I refresh the page.

Could this be to do with versionpress? Its a completely clean installation, with versionpress 3.0 installed.

**Comment by borekb** [comment]
This is really strange. We discussed it internally some more and have no ideas what could be causing this. Would you be able to do some more research on your own? It will have something to do with your server configuration, that's for sure. Thanks.

**Comment by meadow19** [comment]
Hello,
Thank you for your help.
I'm really impressed with what your project has achieved, and how helpful and responsive you are! Thank you.

I deleted the wordpress installation, database, and user. So we're back to a clean Ubuntu 16.04 install.
Next, I created a brand new wordpress installation. I tested uninstalling a plugin (Hello Dolly! Seriously, this should be on your homepage screenshot as the first thing anyone deletes on their Wordpress install!)
Worked fine.
Next I installed Hello Dolly again, through the plugins tab. Worked fine.
Next I installed Versionpress. Worked fine. No chmod errors this time.
Next I deactivated and deleted the Hello Dolly again.
Checked Versionpress tab, it was recorded.

So all seems to be working fine!

The only two things I did differently this time, as far as I can remember, are:

1) Unzipped wordpress install on the server, using the FTP client, instead of unzipping on my desktop and uploading the unzipped folder.
2) Changed Wordpress address and Site address in "Settings/General" to 
https://mysite.com/wordpressdirectory
instead of http://mysite.com/wordpressdirectory

which is what I think it was before. 
I.e. I added the https instead of http.

Anyway, it seems to be working fine now. Thank you all kindly for your time and effort. If there is a way to donate to your project, please let me know!

**Comment by borekb** [comment]
@meadow19 Thank you, and great that you got it resolved! Useful bug reports and suggestions are the best way to contribute to the project right now :)
