### ISSUE TITLE
Some questions with regards to compatibility with WordFence

### ISSUE THREAD

**Issue by ovizii** [versionpress/support#39]
I found one has to exclude certain directories of Wordfence as they change quite often and generate temp files. 

My first attempt was to edit .gitignore and simply add:
`/wp-content/plugins/wordfence/tmp/*`
or
`/wp-content/plugins/wordfence/tmp/`
but none of that works, I still get alerted about uncommitted changes by VP.

Wordfence detects changed plugin/theme and core files so it picks up on: wp-includes/wp-db.php so I have told WF not to alert me until ti change again.

- VersionPress version: 3.0
- WordPress version: 4.5.1
- OS, webserver, PHP: Linux 4.2.8-1-pve (Debian 8.4), nginx/1.8.1, 5.6.19-0+deb8u1
- Git version: 2.1.4

**Comment by borekb** [comment]
Once Git tracks a file, just adding it to `.gitignore` will not work – it needs to be removed from the repo first. Could that be it?

**Comment by ovizii** [comment]
Not sure, not a git user, just a WP user :-)  
So then what is the normal procedure? 
Instapp VP, edit .gitignore before activating VP?

All I did was install VP, activate it, realize those tmp files were tracked and posted here.

**Comment by borekb** [comment]
Yeah, this workflow needs to be better in the future. Ideally, VersionPress would immediately know that for Wordfence, certain folders should be ignored. We'll try to work with plugin authors to provide this info in a format that VersionPress will be able to consume.

For now, if you want to ignore certain items after they have been put under version control, you have to remove them from Git and then add to `.gitignore`.

**Comment by ovizii** [comment]
OK, I guess I'll have to google the "remove from git part".

I'd also be interested in seeing a GUI for ignoring certain changes, i.e. I am managing all my WP sites with a tool which seems to change an option value periodically, i.e. every hour and versionpress catches this every time so it would be interesting to be able to make an exception for the value below, as an example.

```
[iwp_client_action_message_id]
option_value = 96919	
```

**Comment by borekb** [comment]
The infrastructure for option ignoring shipped in 3.0, see https://github.com/versionpress/versionpress/issues/511. v4.0 will make this user-configurable and we have also some ideas of how to make the UI more pleasant, just please give us some time.

Thanks for your feedback!

**Comment by ovizii** [comment]
One more thing: 

so what is the procedure to get .gitignore working? Shall I follow the uninstall section http://docs.versionpress.net/en/getting-started/installation-uninstallation and deactivate the plugin, delete wp-content/vpbackups, delete .git then activate Versionpress again but before making it live, edit .gitignore?

**Comment by borekb** [comment]
You can edit `.gitignore` while VP is running, there's no problem with that. Just drop to the command line, remove files you want to ignore from the Git repo and update the `.gitignore` file, commit as usual and carry on. Some knowledge of Git is required here but that's how things are at the moment, unfortunately. We'll be making the software more user-friendly in the future.

**Comment by ovizii** [comment]
Thanks, I get it now.
