### ISSUE TITLE
VersionPress on The Changelog!

### ISSUE THREAD

**Issue by adamstac** [versionpress/support#40]
Howdy from The Changelog!

Congrats on going public recently. We'd love to have you on the show sometime soon. Who would be best to have on the show to talk about this project and what you're up to? Feel free to send an email to editors@changelog.com to coordinate.

If you haven't heard of the show, The Changelog is a podcast published weekly on Friday that covers what's fresh and new in open source. You can listen to the show here http://thechangelog.com/podcast

BTW, we recently talked to Matt Mullenweg - https://changelog.com/197

Looking forward to talking to y'all!

Adam, EIC

**Comment by borekb** [comment]
Best "support" ticket yet :) Will get in touch soon, thanks!
