### ISSUE TITLE
Local and remote environment error

### ISSUE THREAD

**Issue by andercard** [versionpress/support#41]
My question is how I can work in a real environment, I mean to have the site on bitbucket/github as a central repository and be able to work with my team taking a test site one live and the premises of our computers

I and tried to do so with git

* git push and git pull

then apply the changes with

* wp vp apply-changes

but the pages, posts and dublican comments

Thank you, this project is great just missing this solution and would be very good

![ff](https://cloud.githubusercontent.com/assets/10929498/14965977/e707704c-1075-11e6-9e5f-481af9ea9bc5.png)

Español
================

mi pregunta es como puedo trabajar en un ambiente real, me refiero a tener el sitio en bitbucket/github como repositorio central y poder trabajar con mi equipo teniendo un sitio de prueba uno en vivo y los locales de nuestros computadores 

yo e probado hacerlo directo con git 

* git push y git pull 

después aplico los cambios con 

* wp vp apply-changes

pero las paginas, entradas y comentario de dublican

Gracias, este proyecto es grandioso solo faltaría esta solución y quedaría muy bien

**Comment by borekb** [comment]
Hi @andercard, it should work as you describe, and VersionPress certainly shouldn't be duplicating contents. What version of VersionPress are you running?

The workflow should generally be something like this:

1. Install VersionPress to a site, activate it
2. `git push` to GitHub
3. On another PC (or environment in general), do `git clone`
4. Copy VersionPress to wp-content/plugins
5. Run `wp vp restore-site ...`
6. Then just `git push` and `git pull` from/to GitHub, followed by `wp vp apply-changes`.

**Comment by andercard** [comment]
Great as you say, is great great, but I kept trying but now generates me the following error.

![sin titulo-1](https://cloud.githubusercontent.com/assets/10929498/14990808/edb2e8fa-1123-11e6-8f50-b13575b398fd.png)


This plugin is great, awesome


Español
========
Genial así como dices, queda excelente grandioso, pero seguí probando pero ahora me genera el siguiente error.

este plugin es grandioso, es impresionante

**Comment by borekb** [comment]
Unfortunately, it's a 3rd party interference (Slider Revolution). We do not support it yet, better support for WP plugins is coming later this year. Sorry.

**Comment by andercard** [comment]
No: (bad luck, the only solution I see is to ignore this plugin (Revolution slider). thank you very much for your help and I repeat great tool.)
Another concerns again :)

Español
========
No : ( que mala suerte, la única solución que veo es ignorar este plugin (revolución slider). muchas gracias por su ayuda y vuelvo a repetir gran herramienta.

Alguna otra inquietud volveré :)

**Comment by andercard** [comment]
try to ignore revolition slider as well

* /wp-content/plugins/revslider /
* /wp-content/uploads/revslider /

all good, until I install the plugin in the other environment I back out the same error but I ignore something more?

Español
==========
intente ignorar slider revolition así 

* /wp-content/plugins/revslider/
* /wp-content/uploads/revslider/

todo bien, hasta que instalo el plugin en el otro entorno me vuelve a salir el mismo error que mas debo ignorar algo mas ?

**Comment by borekb** [comment]
It would need to be completely uninstalled, unfortunately.

**Comment by andercard** [comment]
Okay, I did another installation from scratch to make the tests as I do to ignore the revolution slider plugin from the beginning and does not generate any errors.

Or this is not possible?

Español
===========
vale, es que hice otra instalación desde cero para poder hacer las pruebas como puedo hacer para ignorar desde el principio el plugin de slider revolution y no generar ningún error.

O esto no es posible ?

**Comment by borekb** [comment]
I'm not sure I understand. So you created a fresh installation and don't see any errors there, right?

**Comment by andercard** [comment]
I'm using the translator

http://www.bing.com/translator/

I'm sorry if this not translating well, I will return to try other translator

**Comment by andercard** [comment]
My question is this, how can I do to ignore the plugin (slider revolution).

**Comment by borekb** [comment]
Slider Revolution needs to be uninstalled completely, it cannot be easily ignored.

**Comment by andercard** [comment]
OK, I did a test as follows ignore all related tables revolution slider that are saved in the folder VPDB by the time I funsiono well, I do other tests to see if any error is generated

**Comment by andercard** [comment]
This was the solution I found and I think it works well. ignoring all the tables relationship with the plugin revolution

# ignorar slider revolution
/wp-content/plugins/revslider/
/wp-content/uploads/revslider/
/wp-content/vpdb/options/re/revslider_checktables.ini
/wp-content/vpdb/options/re/revslider_table_version.ini
/wp-content/vpdb/options/re/revslider_update_version.ini
/wp-content/vpdb/options/re/revslider-global-settings.ini
/wp-content/vpdb/options/re/revslider-templates-check.ini
/wp-content/vpdb/options/re/revslider-update-check-short.ini
/wp-content/vpdb/options/rs/rs-templates.ini

**Comment by borekb** [comment]
Glad you found a solution!
