### ISSUE TITLE
Versionpress needed space

### ISSUE THREAD

**Issue by ovizii** [versionpress/support#42]
Just curios, how much space does versionpress need? 
I know that depends on how many changes one does but I'm confused about my space usage. 

I installed VP on a testsite, with almost no visitors and no work done on the site except for regular updates. 

```
root@alfred:/var/www/domain.tld# du -cksh web/
1.3G    web/
1.3G    total
root@alfred:/var/www/domain.tld# du -cksh web/.git/
850M    web/.git/
850M    total
```

Does this look normal? the .git folder is twice the size of the complete site and no, the DB is not that big :-)

**Comment by borekb** [comment]
As you said, it really depends on the site of your site. Can you try to run `git gc --aggressive --prune=now` to see if that helps? That will compact the Git repository as much as possible.

**Comment by borekb** [comment]
@ovizii Could you provide rough stats of how the data of your site is distributed? How large are the following categories?

1. Images or other media (`uploads`)
2. The rest of the files of the site
3. Database size (e.g., size of its dump)

Thank you.

**Comment by ovizii** [comment]
```
git gc --aggressive --prune=no
Counting objects: 21430, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (21034/21034), done.
Writing objects: 100% (21430/21430), done.
Total 21430 (delta 3097), reused 0 (delta 0)
Removing duplicate objects: 100% (256/256), done.
usage: git prune [-n] [-v] [--expire <time>] [--] [<head>...]

    -n, --dry-run         do not remove, show only
    -v, --verbose         report pruned objects
    --progress            show progress
    --expire <expiry-date>
                          expire objects older than <time>

error: failed to run prune

```
```
root@alfred:/var/www/domain.tld/web# du -cksh *
0       0
7.2M    wp-admin
424M    wp-content
14M     wp-includes
447M    total

```
```
root@alfred:/var/www/domain.tld/web# du -cksh wp-content/*
2.5M    wp-content/languages
182M    wp-content/plugins
9.4M    wp-content/themes
228M    wp-content/uploads
1.5M    wp-content/vpdb
424M    total

```
the DB is 17MB (uncompressed)
I've cut out parts that were too small to matter in the grand scheme of things.

**Comment by borekb** [comment]
There is about 230 MB of data that will be hard to compress so the Git repo should be somewhere between 230-300 MB in size. Suspicious is the size of the `plugins` folder – my best guess would be that some plugins is generating a lot of cache files or something like that, which would pollute the Git repo quickly if that changes frequently. That might explain why you're seeing 850 MB size, not 200-300.

Could you dig in more into the `plugins` folder?

**Comment by ovizii** [comment]
nope, the plugins are legit. this is a test site so there really are a lot of plugins installed. not activated though. 

All (106) | Active (10) | Inactive (96) | Must-Use (1)

**Comment by borekb** [comment]
Ah ok. Then, the repo should not have 850 MB. Something large must have been committed to it..

**Comment by ovizii** [comment]
ok, anyway, not an issue, as I said, I'm just testing and finding my feet using versionpress.

Any future plans of extending the VP GUI to allow some interactions/restrictions for git?

**Comment by borekb** [comment]
Generally, yes. What exactly would you like to see?

**Comment by ovizii** [comment]
well, the general stuff I see in other backup/sync/versioning solutions like being able to set a maximum size for the repository or maximum number of changes to keep track of or maximum age of tracked changes.

**Comment by borekb** [comment]
Git works quite differently from these traditional backup methods but there's something about what you suggest. Well, we've still got a long road ahead :) Thanks for your feedback.

**Comment by ovizii** [comment]
Sure thing, thanks for the assistance!
