### ISSUE TITLE
Tracking _wp_session_expires_...

### ISSUE THREAD

**Issue by pingram3541** [versionpress/support#43]
- VersionPress version: 3.0
- WordPress version: 4.5.1
- OS, webserver, PHP: Easy Engine 3.5.5/Ubuntu 14.04/Nginx
- Git version: 1.9.1

Installed for about 24 hours and have several pages of these events along with plugin activations, updates etc.  Seems a little aggressive to track every time the session id is updated.  By default this is supposed to happen twice daily I think but either the WordFence or Clef plugin may be updating this more frequently.  Is this normal behavior I should just ignore or is there some optimization I can take advantage of to prune these events from the list?

**Comment by borekb** [comment]
WP core options that are doing this are already ignored, plugins will need specific support in the future. If you don't mind editing some core VersionPress files, you can add ignore rules to [`wordpress-schema.yml`](https://github.com/versionpress/versionpress/blob/master/plugins/versionpress/src/Database/wordpress-schema.yml#L111) or .gitignore that specific option (it will be an INI file inside a `vpdb` folder).

**Comment by pingram3541** [comment]
So it would look like this:

    - 'option_name: _wp_session_expires_*'

**Comment by borekb** [comment]
Yup.
