### ISSUE TITLE
caching plugin

### ISSUE THREAD

**Issue by morinoalaria** [versionpress/support#45]
My hosting company recommended that I use WP Super Cache to reduce server overhead (currently using Comet Cache). I was about to install it on one of my sites running VP, but I got a warning that the two plugins wouldn't work properly together.

If I can't use WP Super Cache, is there a caching plugin you would recommend? (I'm using VP 2.2, don't have a later version of php available on my server)

**Comment by borekb** [comment]
Hi, 3rd party plugins are generally not supported very well with VersionPress 3.x and below, it will be a big focus of 4.0, see https://github.com/versionpress/versionpress/issues/1036. Therefore, we don't have a recommendation for you, sorry :(
