### ISSUE TITLE
Hard refresh to show updates

### ISSUE THREAD

**Issue by jpen365** [versionpress/support#46]
- VersionPress version: 3.0
- WordPress version: 4.5.2
- OS, webserver, PHP: 7.0.4
- Git version: 2.6.1
- Environment: SiteGround shared server

Hi, installed VP on a brand new WP install with all plugins deactivated (only Akismet installed), twentysixteen active. Changes aren't showing up in VP interface unless I hard-refresh my browser (Chrome).

Also worth noting, at first I thought VP just wasn't logging the changes so I uninstalled and attempted to delete which produced a fatal error and changed the root directory permissions to 750 - which produced a 403 forbidden error on the domain. Anyway, I fixed the folder permissions, reinstalled VP and realized the changes are being logged, they just don't show up unless I hard refresh the browser when viewing the VP dashboard.

**Comment by borekb** [comment]
@jpen365 Can you try to use your browser console (F12) to see if there are any errors reported there? Our UI is powered by JavaScript + REST API and it's possible that the REST API isn't returning the data for some reason. Thanks.

**Comment by jpen365** [comment]
@borekb There are no errors showing up in the console. The only message in the console is related to JQ Migrate.

**Comment by jpen365** [comment]
Also, just to make sure it wasn't a browser issue I accessed the site in Firefox and am seeing the same behavior.

**Comment by jpen365** [comment]
Curiously, a console message is showing up in Firefox that isn't showing up in Chrome. 
![console](https://cloud.githubusercontent.com/assets/4969721/15099146/3790ec52-150b-11e6-8a11-0333f11a4c98.png)

**Comment by jpen365** [comment]
@borekb Another FYI...I got VP 3.0 up and running locally with a XAMPP-powered WP install and it seems to work great. So I think the issue I'm seeing is a Siteground issue. Unless there's a reason to I'm going to close this one and chalk it up to a hosting issue and not a VP issue. Thoughts?

**Comment by borekb** [comment]
Agree that it would be best to ask Siteground support. However, if you find out what the root cause was, I'd be curious to know. Thanks!

**Comment by borekb** [comment]
BTW thanks for your [article](https://premium.wpmudev.org/blog/versionpress/), great work! (despite this unfortunate Siteground issue :) )

**Comment by pavelevap** [comment]
@jpen365: Hi, I will be testing VersionPress compatibility with SiteGround services, but I would like to know which specific plan did you use? I can see standard Shared Hosting or some kind of WordPress Hosting? Did you use StartUp, GrowBig or GoGeek plan? Thank you!

**Comment by jpen365** [comment]
@pavelevap I have the GrowBig plan.

**Comment by pavelevap** [comment]
Hi @jpen365,

we were able to reproduce both problems ([caching](https://github.com/versionpress/versionpress/issues/1052) and [permissions](https://github.com/versionpress/versionpress/issues/945)) and they will be be fixed in upcoming VersionPress 3.0.1. 

Thank you for your report!

**Comment by jpen365** [comment]
Good deal! Thanks!
