### ISSUE TITLE
VersionPress + Dreamhost

### ISSUE THREAD

**Issue by pavelevap** [versionpress/support#47]
It is only my tracking issue for testing Dreamhost services on my several years old website (only some pages):

- Initial installation works pretty well, VP is activated with standard settings, administration is loaded without problems.

After some work with website, I noticed some problems:

- Full Diff was not loaded correctly sometimes.
- I am using MainWP plugin and after theme update the whole website was stucked under `.maintenance` mode. WIthout VP everyhing works well.
- After removing `.maintenance` file, VP was broken (Connection error), hard refresh did not help.
- After deactivating and deleting VP, the whole website was stucked with 403 error (domain directory CHMOD permission was changed from 755 to 750).

I will try to find the cause, add screenshots and find steps to reproduce.

**Comment by borekb** [comment]
(Closing this just to remove it from the open support issues. Feel free to use it though, @pavelevap.)

**Comment by pavelevap** [comment]
Strange, I encountered weird problem at Dreamhost. VP admin panel stopped loading without any reason and after deactivating I was not able to activate VP again. I can see following error in my log:

`client denied by server configuration: .../wp-content/plugins/versionpress/temp/security-check.txt`

It seems it is related to checking `security-check.txt` file on this [line](https://github.com/versionpress/versionpress/blob/0eeb12d4208ed195abec54ba327eea9553f525c4/plugins/versionpress/src/Utils/RequirementsChecker.php#L279).

It looks like some kind of automatic security ban by Dreamhost. I contacted support and will see what is going on.

**Comment by tannerchung** [comment]
@pavelevap have you heard back from Dreamhost? I'm also on Dreamhost and have been wanting to install VersionPress badly!

**Comment by pavelevap** [comment]
Hi @tannerchung,

VP "mostly" works with Dreamhost. I could not reproduce some errors mentioned above and some of them are not important in the end (`security-check.txt` is only tracked and creates notice, but everything works well).

But VP can be used only as a tracking tool in WP administration, using WP-CLI features for cloning sites etc is blocked due to older PHP version on their servers: https://github.com/versionpress/versionpress/issues/1077

I tested only basic hosting plan (10 USD per month), maybe DreamPress or some other services work without problems.
