### ISSUE TITLE
Staging clone created in production parent directory (FastComet hosting)

### ISSUE THREAD

**Issue by holdav** [versionpress/support#49]
Hello,

I want to create staging environment on FastComet hosting which you recommend as VP supported hosting so I run:

```
user@de3 [~/public_html]# wp vp clone --name=staging
Error: The command cannot derive default clone URL. Please specify the --siteurl parameter.
user@de3 [~/public_html]# wp vp clone --name=staging --siteurl=www.website.com/staging
Success: Site files cloned
Success: Clone added as a remote
Success: Enabled pushing to the original repository
Success: Enabled pushing to the clone
Success: wp-config.php updated
Success: Copied VersionPress
Success: Database tables created
Success: VersionPress tables created
Success: Git merge driver added
Success: Database synchronized
Success: All done. Clone created here:

Path:   /home/user/staging
URL:    www.website.com/staging
```

Now if I look at www.website.com/staging there is no staging clone of production web but only 404 error of production site.

Another problem is that staging environment folder isn't created in public_html folder with production web but in its parent (../public_html).

Finally I don't understand why is showing this error message "Error: The command cannot derive default clone URL. Please specify the --siteurl parameter."

Info about environment: VP 3.0, WP 4.5.2, Git 1.9.4, PHP 5.6, Apache, CentOS

Thank you

**Comment by unclhos** [comment]
The clone command makes the sites sibling directory. Where you need it to be in a child directory. You can move your "staging" folder into the "public_html" folder then use the "wp vp restore-site --siteurl='www.website.com/staging' --require=wp-content/plugins/versionpress/src/Cli/vp.php" command from within the "staging" directory. Which should fix your directory paths anywhere that needs it.

http://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site

I will bring up the issue of cloning to a child directory.

**Comment by holdav** [comment]
Thank you.
