### ISSUE TITLE
Error cloning site

### ISSUE THREAD

**Issue by digitalartworks** [versionpress/support#5]
Hi,
I have another problem with "wp vp clone" command. I run it with --debug so I can see debug messages. After messages:

Debug: No readable global config found (0.006s)
Debug: No project config found (0.007s)
Debug: ABSPATH defined: /var/www/mieszkaniowi/prod/ (0.007s)
Debug: Begin WordPress load (0.007s)
Debug: wp-config.php path: /var/www/mieszkaniowi/prod/wp-config.php (0.008s)
Debug: Loaded WordPress (0.283s)
Debug: Running command: vp clone (0.283s)
Success: Site files cloned
The Git repo of this site already defines remote 'dev', overwrite it? [y/n] y
Success: Updated remote configuration
Success: Enabled pushing to the original repository
Success: Enabled pushing to the clone
Success: wp-config.php updated
Success: Copied VersionPress
Success: Database tables created
Success: VersionPress tables created

there is several errors like this bellow:

WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE meta_id=(SELECT id FROM wp_dev_vp_id WHERE vp_id=UNHEX("56E0E071AF2C43229E' at line 1 for query UPDATE wp_dev_postmeta SET meta_value= WHERE meta_id=(SELECT id FROM wp_dev_vp_id WHERE vp_id=UNHEX("56E0E071AF2C43229E0CA1C5673F18B6")) made by include('phar:///usr/local/bin/wp-cli.phar/php/boot-phar.php'), include('phar:///usr/local/bin/wp-cli.phar/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronize, VersionPress\Synchronizers\SynchronizerBase->synchronize, VersionPress\Synchronizers\SynchronizerBase->fixSimpleReferences, VersionPress\Synchronizers\SynchronizerBase->fixValueReferencesOfOneEntity

You can see that "meta_value=" have no value

What can be wrong?

**Comment by JanVoracek** [comment]
Hi,

it's a bug in VersionPress. We will fix it in 2.2 (comming next week). You can either wait, or I can describe you how to fix it. 

Anyway, thanks for the report.

**Comment by digitalartworks** [comment]
So I will wait.

Thanks
