### ISSUE TITLE
Cannot Activate on FastComet Hosting

### ISSUE THREAD

**Issue by ZloVolk** [versionpress/support#51]
I have this issue appear when trying to activate Version Press
•	Git 1.9+ installed
Git version detected with which there are known issues. Please install at least version 1.9 (this can be done side-by-side and VersionPress can be configured to use that specific Git version). Learn more.

I am currently Using FastComet as you suggested for hosting. 
 Trying to View the Full System Info leads to a 404 error
I have tried this on an existing install and a fresh install.

I cannot for the life of me know how to make version press see the git version that is already installed on the server.
I have tried changing the path in the WP config, I have tried doing it through WP-CLI. 
How do I get this to activate?

Version Press: 3.0.1
WordPress: 4.5.2
-PHP 5.3-5.6 +7
-MySQL 5.7 /InnoDB
-Apache 2.2
-ngninx 1.8.0
-cPanel 11.52.11
-memcache 1.4.4
-CentOS 6.5
- git 1.9.4

**Comment by borekb** [comment]
Hi, did you try to contact FastComet support about this? They certainly support VersionPress, at least to the point where it could be activated. Maybe you're on some of their old server? It's really hard to tell from here, please try to contact them. Thanks.

**Comment by ZloVolk** [comment]
I did. That actually did help thank you so so much!

**Comment by borekb** [comment]
:+1:
