### ISSUE TITLE
Database cloning - what should happen

### ISSUE THREAD

**Issue by peterglock** [versionpress/support#52]
- VersionPress version: 3.0.1
- WordPress version: 4.5.2
- OS, webserver, PHP: CentOS 6, Apache 2.4, PHP 5.6.22
- Git version: 2.8.3

I have many plugins installed on my live site. Some create their own db tables. When creating a clone of the live site `wp vp clone --name=staging` not all of the db tables are copied across. Is there any workaround?

**Comment by pavelevap** [comment]
Hi,

it is not possible yet. But during summer there will be 3rd party plugin support available and you can track progress here: https://github.com/versionpress/versionpress/issues/1036
