### ISSUE TITLE
Docs specify safe_mode, but this has been removed from php 5.4.0 onwards

### ISSUE THREAD

**Issue by aidanheerdegen** [versionpress/support#53]
The install docs specify turning safe_mode off:

http://docs.versionpress.net/en/getting-started/installation-uninstallation

but this has been removed from php since v 5.4.0

http://php.net/manual/en/features.safe-mode.php

**Comment by borekb** [comment]
Thanks, I've updated the docs, see https://github.com/versionpress/docs/pull/61
