### ISSUE TITLE
Moved wordpress, now VersionPress is broken

### ISSUE THREAD

**Issue by aidanheerdegen** [versionpress/support#55]
```php
  'wordpress-version' => '4.5.2',
  'versionpress-version' => '3.0.1',
  'operating-system' => 'Linux cosima.anu.edu.au 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64',
  'php-version' => '5.6.22',
  'php-sapi' => 'apache2handler',
  'git-version' => '2.8.3',
  'git-full-path' => '/usr/bin/git
```

Having overcome by previous issue (#54), I was in the position of having a wordpress install in the root directory, which makes it hard (and unsupported) to clone.

So I followed the [instructions to move a wordpress install to it's own directory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory), but now VersionPress is broken. I can no longer access the main page with commits etc. It is blank.

Do I have to reinstall and reactivate VersionPress?

Thanks.

**Comment by borekb** [comment]
@aidanheerdegen Yes you do. The changes to project structure need to be done before activating VersionPress [as per this docs page](http://docs.versionpress.net/en/feature-focus/custom-project-structure). Actually, I'm going to update the docs to stress this more.

Thanks for the report.

**Comment by borekb** [comment]
I've [updated the docs](https://github.com/versionpress/docs/pull/60). The top section now looks like this:

![2016-06-20 11_01_46-custom project structure _ versionpress docs](https://cloud.githubusercontent.com/assets/101152/16188565/795e9eda-36d6-11e6-8e56-00b92f8d8f70.png)
