### ISSUE TITLE
 "Click here to show changes." doesn't do anything.

### ISSUE THREAD

**Issue by h-kawada** [versionpress/support#56]
- VersionPress version: 3.0.1
- WordPress version: 4.5.3
- OS, webserver, PHP: CentOS7, Nginx, PHP7
- Git version: 2.8.4

The below message is displayed but clicking "Click here to show changes." doesn't do anything other than replacing the text with "Click here to hide changes".

> You have uncommitted changes in your WordPress directory. Click here to show changes.

I suppose this should list up the uncommitted changes for further actions.

**Comment by borekb** [comment]
@h-kawada Thanks for the report.

@JanVoracek, isn't this the same issue you had recently with tests? The one when the issue disappeared when running `git status` manually..

**Comment by JanVoracek** [comment]
@borekb Yes, it could be the same issue. However, I still can't remember if we found any solution.

**Comment by borekb** [comment]
@h-kawada Could you try if running `git status` manually (in a console) resolves the issue?

**Comment by vasek17** [comment]
Hi @h-kawada, this is a bug we introduced in release 3.0.1. I am sorry for that.
It is already resolved and the fix will be shipped in release 3.0.2.

**Comment by h-kawada** [comment]
@vasek17 Thanks! I'll give 3.0.2. a try.
