### ISSUE TITLE
Says I need PHP 5.6 or higher even though command line says I'm on PHP 7.0

### ISSUE THREAD

**Issue by andrewbanchich** [versionpress/support#57]
- VersionPress version: 3.0
- WordPress version: 4.5.3
- OS, webserver, PHP: Ubuntu, DigitalOcean, 7.0
- Git version: 1.9.1

I've upgraded my whole server, installed PHP 7.0, did apt-get update, installed Git, and restarted Apache, but VersionPress keeps saying I have PHP 5.6 installed and won't let me start using the plugin.

**Comment by JanVoracek** [comment]
Hi, can you please check the System Info page – [docs](http://docs.versionpress.net/en/troubleshooting/system-info-page)? It is quite common that the webserver uses different version of PHP than CLI.

**Comment by andrewbanchich** [comment]
Got it, thanks!

**Comment by borekb** [comment]
Good. BTW, 5.6 should be supported, not sure why the activation screen would complain about that..
