### ISSUE TITLE
Access rules can be installed, ok but ??

### ISSUE THREAD

**Issue by dotMastaz** [versionpress/support#58]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 3.0.1
- WordPress version: 4.5.3
- OS, webserver, PHP: Trusty, Apache, Php 7.0.8
- Git version: 1.9.1

Hello,
First, thank you for this WONDERFUL PLUGIN !
Ok :
I have error on activation :
Access rules can be installed: ...
I go to http://docs.versionpress.net/en/getting-started/installation-uninstallation#supported-web-servers
But i don't know what to do or check ??
What is the problem ?

Thank you !

**Comment by JanVoracek** [comment]
Hi, Nicolas.

This "requirement" checks whether Apache applies `.htaccess` files inside the VersionPress directory. Anyway, it should be only warning – you should be able to active VersionPress even when this warning occurs. 

However, if you want to use the site on production, please be sure anyone cannot access files in `wp-content/vpdb`. This directory contains raw data from the database.
