### ISSUE TITLE
wordpress crashes when activate version press plugin

### ISSUE THREAD

**Issue by mrsathish05** [versionpress/support#62]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 
- WordPress version:
- OS, webserver, PHP:
- Git version:

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by mrsathish05** [comment]
when i tried to activate the version press i got this below message 
Web size
The initialization will take a little longer. This website contains 856831 entities.

External plugins
You run 23 external plugins we have not tested yet. Read more about 3rd party plugins support.

View full system info

and once i click acitvate the site has been crashed

**Comment by pavelevap** [comment]
Hi,

what do you mean with "crashed"? Is there any error message (visible or in `error.log`) or something else?

There are really many entities, how big is your database? Do you have many posts, terms or other data related to some plugins?

**Comment by mrsathish05** [comment]
hi Team,once i installed the version press plugin and tried to activate the plugin i got the below error message              after this error message i got scheduled maintenance window              




The error we got in error.log PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/content/wp-includes/functions.php on line 4165,
Regards,Sathish M.R

Date: Thu, 1 Sep 2016 01:15:42 -0700

**Comment by borekb** [comment]
Thanks, we'll look at the memory consumption.

At the same time, your site is certainly too complex for VersionPress now, you won't be able to use it yet :( We're working to support plugins in v4 and beyond, see versionpress/versionpress#1036.
