### ISSUE TITLE
Never makes it past maintenance mode - ends up back in need to activate mode

### ISSUE THREAD

**Issue by ihafkenschiel** [versionpress/support#63]
I pass the system requirements. There is a warning for:

Web size
The initialization will take a little longer. This website contains 305063 entities.
External plugins
You run 30 external plugins we have not tested yet. Read more about 3rd party plugins support.

When I click Activate Versionpress, it takes me to the screen that says:
Setting things up for you
Starting up
Helper database created

Then it is in maintenance mode if I refresh.

Then  few minutes later it says Versionpress needs to be activated again. I have done this 3 times, same result every time.

Here is my system info:

Quick summary

array (
  'wordpress-version' => '4.6',
  'versionpress-version' => '3.0.2',
  'operating-system' => 'Linux 696208-app2 2.6.32-573.18.1.el6.x86_64 #1 SMP Wed Jan 6 11:20:49 EST 2016 x86_64',
  'php-version' => '5.6.25',
  'php-sapi' => 'cgi-fcgi',
  'git-version' => '2.9.3',
  'git-full-path' => '/usr/bin/git
',
)

Git

array (
  'git-binary-as-configured' => 'git',
  'git-available' => true,
  'git-version' => '2.9.3',
  'git-binary-as-called-by-vp' => 'git',
  'git-full-path' => '/usr/bin/git
',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => true,
)

Permissions

array (
  'exec-user' => 'dev',
  'proc_open-user' => 'dev',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)

WordPress

array (
  'wp-version' => '4.6',
  'siteurl' => 'https://beta.example.com',
  'home' => 'https://beta.example.com',
  'installed-plugins' => 
  array (
    'advanced-custom-fields-pro/acf.php' => 
    array (
      'Name' => 'Advanced Custom Fields PRO',
      'PluginURI' => 'https://www.advancedcustomfields.com/',
      'Version' => '5.3.10',
      'Author' => 'Elliot Condon',
      'AuthorURI' => 'http://www.elliotcondon.com/',
      '__IsActive' => true,
    ),
    'akismet/akismet.php' => 
    array (
      'Name' => 'Akismet',
      'PluginURI' => 'https://akismet.com/',
      'Version' => '3.1.11',
      'Author' => 'Automattic',
      'AuthorURI' => 'https://automattic.com/wordpress-plugins/',
      '__IsActive' => true,
    ),
    'autoptimize/autoptimize.php' => 
    array (
      'Name' => 'Autoptimize',
      'PluginURI' => 'http://blog.futtta.be/autoptimize',
      'Version' => '2.0.2',
      'Author' => 'Frank Goossens (futtta)',
      'AuthorURI' => 'http://blog.futtta.be/',
      '__IsActive' => false,
    ),
    'better-internal-link-search/better-internal-link-search.php' => 
    array (
      'Name' => 'Better Internal Link Search',
      'PluginURI' => 'http://wordpress.org/extend/plugins/better-internal-link-search/',
      'Version' => '1.2.12',
      'Author' => 'Blazer Six',
      'AuthorURI' => 'http://www.blazersix.com/',
      '__IsActive' => true,
    ),
    'broken-link-checker/broken-link-checker.php' => 
    array (
      'Name' => 'Broken Link Checker',
      'PluginURI' => 'http://w-shadow.com/blog/2007/08/05/broken-link-checker-for-wordpress/',
      'Version' => '1.11.2',
      'Author' => 'Janis Elsts, Vladimir Prelovac',
      'AuthorURI' => 'http://w-shadow.com/',
      '__IsActive' => true,
    ),
    'coming-soon/coming-soon.php' => 
    array (
      'Name' => 'Coming Soon Page & Maintenance Mode by SeedProd',
      'PluginURI' => 'http://www.seedprod.com',
      'Version' => '5.0.4',
      'Author' => 'SeedProd',
      'AuthorURI' => 'http://www.seedprod.com',
      '__IsActive' => true,
    ),
    'custom-login/custom-login.php' => 
    array (
      'Name' => 'Custom Login',
      'PluginURI' => 'https://frosty.media/plugins/custom-login',
      'Version' => '3.2.5',
      'Author' => 'Austin Passy',
      'AuthorURI' => 'http://austin.passy.co',
      '__IsActive' => true,
    ),
    'disable-comments/disable-comments.php' => 
    array (
      'Name' => 'Disable Comments',
      'PluginURI' => 'http://wordpress.org/extend/plugins/disable-comments/',
      'Version' => '1.5.1',
      'Author' => 'Samir Shah',
      'AuthorURI' => 'http://rayofsolaris.net/',
      '__IsActive' => false,
    ),
    'enable-media-replace/enable-media-replace.php' => 
    array (
      'Name' => 'Enable Media Replace',
      'PluginURI' => 'http://www.mansjonasson.se/enable-media-replace',
      'Version' => '3.0.4',
      'Author' => 'Måns Jonasson',
      'AuthorURI' => 'http://www.mansjonasson.se',
      '__IsActive' => false,
    ),
    'export-to-text/export-to-text.php' => 
    array (
      'Name' => 'Export to Text',
      'PluginURI' => 'http://www.hypedtext.com',
      'Version' => '2.4',
      'Author' => 'Hyped Text',
      'AuthorURI' => 'http://www.hypedtext.com',
      '__IsActive' => false,
    ),
    'google-sitemap-generator/sitemap.php' => 
    array (
      'Name' => 'Google XML Sitemaps',
      'PluginURI' => 'http://www.arnebrachhold.de/redir/sitemap-home/',
      'Version' => '4.0.8',
      'Author' => 'Arne Brachhold',
      'AuthorURI' => 'http://www.arnebrachhold.de/',
      '__IsActive' => true,
    ),
    'gravityforms/gravityforms.php' => 
    array (
      'Name' => 'Gravity Forms',
      'PluginURI' => 'http://www.gravityforms.com',
      'Version' => '2.0.6',
      'Author' => 'rocketgenius',
      'AuthorURI' => 'http://www.rocketgenius.com',
      '__IsActive' => true,
    ),
    'gravityforms-multilingual/plugin.php' => 
    array (
      'Name' => 'Gravity Forms Multilingual',
      'PluginURI' => 'http://wpml.org/documentation/related-projects/gravity-forms-multilingual/',
      'Version' => '1.3.11',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'mailchimp-for-wp/mailchimp-for-wp.php' => 
    array (
      'Name' => 'MailChimp for WordPress',
      'PluginURI' => 'https://mc4wp.com/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-page',
      'Version' => '4.0.3',
      'Author' => 'ibericode',
      'AuthorURI' => 'https://ibericode.com/',
      '__IsActive' => true,
    ),
    'post-types-order/post-types-order.php' => 
    array (
      'Name' => 'Post Types Order',
      'PluginURI' => 'http://www.nsp-code.com',
      'Version' => '1.8.9.2',
      'Author' => 'Nsp Code',
      'AuthorURI' => 'http://www.nsp-code.com',
      '__IsActive' => true,
    ),
    'query-monitor/query-monitor.php' => 
    array (
      'Name' => 'Query Monitor',
      'PluginURI' => 'https://github.com/johnbillion/query-monitor',
      'Version' => '2.12.0',
      'Author' => 'John Blackbourn',
      'AuthorURI' => 'https://johnblackbourn.com/',
      '__IsActive' => false,
    ),
    'rename-wp-login/rename-wp-login.php' => 
    array (
      'Name' => 'Rename wp-login.php',
      'PluginURI' => 'https://wordpress.org/plugins/rename-wp-login/',
      'Version' => '2.5.5',
      'Author' => 'Ella Iseulde Van Dorpe',
      'AuthorURI' => 'https://iseulde.com',
      '__IsActive' => true,
    ),
    'rich-tax-description-editor/main.php' => 
    array (
      'Name' => 'Rich Tax Description Editor',
      'PluginURI' => 'http://wordpress.org/support/plugin/rich-tax-description-editor',
      'Version' => '1.2.4',
      'Author' => 'Davit Barbakadze',
      'AuthorURI' => 'http://wordpress.org/support/profile/jayarjo',
      '__IsActive' => true,
    ),
    'simple-301-redirects/wp-simple-301-redirects.php' => 
    array (
      'Name' => 'Simple 301 Redirects',
      'PluginURI' => 'http://www.scottnelle.com/simple-301-redirects-plugin-for-wordpress/',
      'Version' => '1.07',
      'Author' => 'Scott Nellé',
      'AuthorURI' => 'http://www.scottnelle.com/',
      '__IsActive' => true,
    ),
    'simple-301-redirects-addon-bulk-uploader/simple-301-bulk-uploader.php' => 
    array (
      'Name' => 'Simple 301 Redirects - Addon - Bulk CSV Uploader',
      'PluginURI' => 'http://kingpro.me/plugins/support-plugins/simple-301-redirects-addon-bulk-csv-uploader',
      'Version' => '1.0.14',
      'Author' => 'Ash Durham',
      'AuthorURI' => 'http://durham.net.au/',
      '__IsActive' => true,
    ),
    'social-warfare/social-warfare.php' => 
    array (
      'Name' => 'Social Warfare',
      'PluginURI' => 'http://warfareplugins.com',
      'Version' => '2.0.5',
      'Author' => 'Warfare Plugins',
      'AuthorURI' => 'http://warfareplugins.com',
      '__IsActive' => true,
    ),
    'sucuri-scanner/sucuri.php' => 
    array (
      'Name' => 'Sucuri Security - Auditing, Malware Scanner and Hardening',
      'PluginURI' => 'https://wordpress.sucuri.net/',
      'Version' => '1.8.1',
      'Author' => 'Sucuri, INC',
      'AuthorURI' => 'https://sucuri.net',
      '__IsActive' => true,
    ),
    'tablepress/tablepress.php' => 
    array (
      'Name' => 'TablePress',
      'PluginURI' => 'https://tablepress.org/',
      'Version' => '1.7',
      'Author' => 'Tobias Bäthge',
      'AuthorURI' => 'https://tobias.baethge.com/',
      '__IsActive' => true,
    ),
    'tablepress-responsive-tables/tablepress-responsive-tables.php' => 
    array (
      'Name' => 'TablePress Extension: Responsive Tables',
      'PluginURI' => 'http://tablepress.org/extensions/responsive-tables/',
      'Version' => '1.2',
      'Author' => 'Tobias Bäthge',
      'AuthorURI' => 'http://tobias.baethge.com/',
      '__IsActive' => true,
    ),
    'updraftplus/updraftplus.php' => 
    array (
      'Name' => 'UpdraftPlus - Backup/Restore',
      'PluginURI' => 'https://updraftplus.com',
      'Version' => '2.12.18.22',
      'Author' => 'UpdraftPlus.Com, DavidAnderson',
      'AuthorURI' => 'https://updraftplus.com',
      '__IsActive' => true,
    ),
    'use-google-libraries/use-google-libraries.php' => 
    array (
      'Name' => 'Use Google Libraries',
      'PluginURI' => 'http://jasonpenney.net/wordpress-plugins/use-google-libraries/',
      'Version' => '1.6.2.1',
      'Author' => 'Jason Penney',
      'AuthorURI' => 'http://jasonpenney.net/',
      '__IsActive' => true,
    ),
    'user-role-editor/user-role-editor.php' => 
    array (
      'Name' => 'User Role Editor',
      'PluginURI' => 'https://www.role-editor.com',
      'Version' => '4.27.1',
      'Author' => 'Vladimir Garagulya',
      'AuthorURI' => 'https://www.role-editor.com',
      '__IsActive' => false,
    ),
    'versionpress/versionpress.php' => 
    array (
      'Name' => 'VersionPress',
      'PluginURI' => 'http://versionpress.net/',
      'Version' => '3.0.2',
      'Author' => 'VersionPress',
      'AuthorURI' => 'http://versionpress.net/',
      '__IsActive' => true,
    ),
    'w3-total-cache/w3-total-cache.php' => 
    array (
      'Name' => 'W3 Total Cache',
      'PluginURI' => 'http://www.w3-edge.com/wordpress-plugins/w3-total-cache/',
      'Version' => '0.9.4.1',
      'Author' => 'Frederick Townes',
      'AuthorURI' => 'http://www.linkedin.com/in/w3edge',
      '__IsActive' => true,
    ),
    'widget-logic/widget_logic.php' => 
    array (
      'Name' => 'Widget Logic',
      'PluginURI' => 'http://wordpress.org/extend/plugins/widget-logic/',
      'Version' => '0.57',
      'Author' => 'Alan Trewartha',
      'AuthorURI' => 'http://freakytrigger.co.uk/author/alan/',
      '__IsActive' => true,
    ),
    'wiser-structured-data-creator/wiser-structured-data-creator.php' => 
    array (
      'Name' => 'Wiser Semantic Structured Data',
      'PluginURI' => 'wisersites.com',
      'Version' => '1.0.1',
      'Author' => 'Wiser Sites',
      'AuthorURI' => 'http://wisersites.com',
      '__IsActive' => true,
    ),
    'wpml-cms-nav/plugin.php' => 
    array (
      'Name' => 'WPML CMS Nav',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '1.4.19',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'wpml-media/plugin.php' => 
    array (
      'Name' => 'WPML Media',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '2.1.22',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'sitepress-multilingual-cms/sitepress.php' => 
    array (
      'Name' => 'WPML Multilingual CMS',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '3.5.1.1',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'wpml-sticky-links/plugin.php' => 
    array (
      'Name' => 'WPML Sticky Links',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '1.4.0',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'wpml-string-translation/plugin.php' => 
    array (
      'Name' => 'WPML String Translation',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '2.4.1.1',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'wpml-translation-analytics/plugin.php' => 
    array (
      'Name' => 'WPML Translation Analytics',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '1.0.7',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => false,
    ),
    'wpml-translation-management/plugin.php' => 
    array (
      'Name' => 'WPML Translation Management',
      'PluginURI' => 'https://wpml.org/',
      'Version' => '2.2.2',
      'Author' => 'OnTheGoSystems',
      'AuthorURI' => 'http://www.onthegosystems.com/',
      '__IsActive' => true,
    ),
    'wordpress-seo/wp-seo.php' => 
    array (
      'Name' => 'Yoast SEO',
      'PluginURI' => 'https://yoast.com/wordpress/plugins/seo/#utm_source=wpadmin&utm_medium=plugin&utm_campaign=wpseoplugin',
      'Version' => '3.4.2',
      'Author' => 'Team Yoast',
      'AuthorURI' => 'https://yoast.com/',
      '__IsActive' => true,
    ),
  ),

  'active-plugins' => 
  array (
    0 => 'gravityforms/gravityforms.php',
    1 => 'advanced-custom-fields-pro/acf.php',
    2 => 'akismet/akismet.php',
    3 => 'better-internal-link-search/better-internal-link-search.php',
    4 => 'broken-link-checker/broken-link-checker.php',
    5 => 'coming-soon/coming-soon.php',
    6 => 'custom-login/custom-login.php',
    7 => 'google-sitemap-generator/sitemap.php',
    8 => 'gravityforms-multilingual/plugin.php',
    9 => 'mailchimp-for-wp/mailchimp-for-wp.php',
    10 => 'post-types-order/post-types-order.php',
    11 => 'rename-wp-login/rename-wp-login.php',
    12 => 'rich-tax-description-editor/main.php',
    13 => 'simple-301-redirects-addon-bulk-uploader/simple-301-bulk-uploader.php',
    14 => 'simple-301-redirects/wp-simple-301-redirects.php',
    15 => 'sitepress-multilingual-cms/sitepress.php',
    16 => 'social-warfare/social-warfare.php',
    17 => 'sucuri-scanner/sucuri.php',
    18 => 'tablepress-responsive-tables/tablepress-responsive-tables.php',
    19 => 'tablepress/tablepress.php',
    20 => 'updraftplus/updraftplus.php',
    21 => 'use-google-libraries/use-google-libraries.php',
    22 => 'versionpress/versionpress.php',
    23 => 'w3-total-cache/w3-total-cache.php',
    24 => 'widget-logic/widget_logic.php',
    25 => 'wiser-structured-data-creator/wiser-structured-data-creator.php',
    26 => 'wordpress-seo/wp-seo.php',
    27 => 'wpml-cms-nav/plugin.php',
    28 => 'wpml-media/plugin.php',
    29 => 'wpml-sticky-links/plugin.php',
    30 => 'wpml-string-translation/plugin.php',
    31 => 'wpml-translation-management/plugin.php',
  ),
)

Server environment / PHP info

array (
  'bz2' => 
  array (
    'BZip2 Support' => 'Enabled',
    'Stream Wrapper support' => 'compress.bzip2://',
    'Stream Filter support' => 'bzip2.decompress, bzip2.compress',
    'BZip2 Version' => '1.0.5, 10-Dec-2007',
  ),
  'calendar' => 
  array (
    'Calendar support' => 'enabled',
  ),
  'cgi-fcgi' => 
  array (
    'cgi.check_shebang_line' => '1',
    'cgi.discard_path' => '0',
    'cgi.fix_pathinfo' => '1',
    'cgi.force_redirect' => '1',
    'cgi.nph' => '0',
    'cgi.redirect_status_env' => 'no value',
    'cgi.rfc2616_headers' => '0',
    'fastcgi.logging' => '1',
  ),
  'Core' => 
  array (
    'PHP Version' => '5.6.25',
    'allow_url_fopen' => 'On',
    'allow_url_include' => 'Off',
    'always_populate_raw_post_data' => '0',
    'arg_separator.input' => '&',
    'arg_separator.output' => '&',
    'asp_tags' => 'Off',
    'auto_append_file' => 'no value',
    'auto_globals_jit' => 'On',
    'auto_prepend_file' => 'no value',
    'browscap' => 'no value',
    'default_charset' => 'UTF-8',
    'default_mimetype' => 'text/html',
    'disable_classes' => 'no value',
    'disable_functions' => 'no value',
    'display_errors' => 'Off',
    'display_startup_errors' => 'Off',
    'doc_root' => 'no value',
    'docref_ext' => 'no value',
    'docref_root' => 'no value',
    'enable_dl' => 'Off',
    'enable_post_data_reading' => 'On',
    'error_append_string' => 'no value',
    'error_log' => 'no value',
    'error_prepend_string' => 'no value',
    'error_reporting' => 
    array (
      0 => '4983',
      1 => '32759',
    ),
    'exit_on_timeout' => 'Off',
    'expose_php' => 'On',
    'extension_dir' => '/usr/lib64/php/modules',
    'file_uploads' => 'On',
    'highlight.comment' => '#FF8000',
    'highlight.default' => '#0000BB',
    'highlight.html' => '#000000',
    'highlight.keyword' => '#007700',
    'highlight.string' => '#DD0000',
    'html_errors' => 'On',
    'ignore_repeated_errors' => 'Off',
    'ignore_repeated_source' => 'Off',
    'ignore_user_abort' => 'Off',
    'implicit_flush' => 'Off',
    'include_path' => '.:/usr/share/pear:/usr/share/php',
    'input_encoding' => 'no value',
    'internal_encoding' => 'no value',
    'log_errors' => 'On',
    'log_errors_max_len' => '1024',
    'mail.add_x_header' => 'On',
    'mail.force_extra_parameters' => 'no value',
    'mail.log' => 'no value',
    'max_execution_time' => '800',
    'max_file_uploads' => '20',
    'max_input_nesting_level' => '64',
    'max_input_time' => '800',
    'max_input_vars' => '3000',
    'memory_limit' => '512M',
    'output_buffering' => '4096',
    'output_encoding' => 'no value',
    'output_handler' => 'no value',
    'post_max_size' => '32M',
    'precision' => '14',
    'realpath_cache_size' => '16K',
    'realpath_cache_ttl' => '120',
    'register_argc_argv' => 'Off',
    'report_memleaks' => 'On',
    'report_zend_debug' => 'On',
    'request_order' => 'GP',
    'sendmail_from' => 'no value',
    'sendmail_path' => '/usr/sbin/sendmail -t -i',
    'serialize_precision' => '17',
    'short_open_tag' => 'Off',
    'SMTP' => 'localhost',
    'smtp_port' => '25',
    'sql.safe_mode' => 'Off',
    'sys_temp_dir' => 'no value',
    'track_errors' => 'Off',
    'unserialize_callback_func' => 'no value',
    'upload_max_filesize' => '32M',
    'upload_tmp_dir' => 'no value',
    'user_dir' => 'no value',
    'user_ini.cache_ttl' => '300',
    'user_ini.filename' => '.user.ini',
    'variables_order' => 'GPCS',
    'xmlrpc_error_number' => '0',
    'xmlrpc_errors' => 'Off',
    'zend.detect_unicode' => 'On',
    'zend.enable_gc' => 'On',
    'zend.multibyte' => 'Off',
    'zend.script_encoding' => 'no value',
  ),
  'ctype' => 
  array (
    'ctype functions' => 'enabled',
  ),
  'curl' => 
  array (
    'cURL support' => 'enabled',
    'cURL Information' => '7.19.7',
    'Age' => '3',
    'Features' => NULL,
    'AsynchDNS' => 'No',
    'CharConv' => 'No',
    'Debug' => 'No',
    'GSS-Negotiate' => 'Yes',
    'IDN' => 'Yes',
    'IPv6' => 'Yes',
    'krb4' => 'No',
    'Largefile' => 'Yes',
    'libz' => 'Yes',
    'NTLM' => 'Yes',
    'SPNEGO' => 'No',
    'SSL' => 'Yes',
    'SSPI' => 'No',
    'Protocols' => 'tftp, ftp, telnet, dict, ldap, ldaps, http, file, https, ftps, scp, sftp',
    'Host' => 'x86_64-redhat-linux-gnu',
    'SSL Version' => 'NSS/3.19.1 Basic ECC',
    'ZLib Version' => '1.2.3',
    'libSSH Version' => 'libssh2/1.4.2',
  ),

**Comment by borekb** [comment]
Hi, VersionPress currently does not support this large / complex sites, unfortunately. 3rd party plugin support is coming in v4 in about a month or two, large sites are going to be optimized for beyond that.
