### ISSUE TITLE
VersionPress initial commit and timeout in backend

### ISSUE THREAD

**Issue by nickw108** [versionpress/support#65]
I activated VersionPress via wp-cli like so:

``` r, engine='bash'
../wp vp activate
Success: PHP 5.6+
Success: 'mbstring' extension
Success: Execute external commands
Success: Git 1.9+ installed
Success: Write access on the filesystem
Success: Access rules can be installed
Success: wpdb hook
Success: Not multisite
Success: Standard directory layout
Warning: Web size
  The initialization will take a little longer. This website contains 129666 entities.
Warning: External plugins
  You run 21 external plugins we have not tested yet. <a href="http://docs.versionpress.net/en/feature-focus/external-plugins">Read more about 3rd party plugins support.</a>
There are some warnings. Continue? [y/n] y
Starting up
Helper database tables created
PHP Warning:  Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Database/ShortcodesReplacer.php on line 148
Warning: Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Database/ShortcodesReplacer.php on line 148
PHP Warning:  Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Utils/WordPressMissingFunctions.php on line 24
Warning: Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Utils/WordPressMissingFunctions.php on line 24
PHP Warning:  Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Database/ShortcodesReplacer.php on line 148
Warning: Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Database/ShortcodesReplacer.php on line 148
PHP Warning:  Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Utils/WordPressMissingFunctions.php on line 24
Warning: Invalid argument supplied for foreach() in /home/.../wp-content/plugins/versionpress/src/Utils/WordPressMissingFunctions.php on line 24
All database work done
VersionPress put into active state
Creating initialization commit in the repository
All finished, VersionPress is ready
Success: VersionPress is fully activated.
```

But it looks like the initialization commit did not suceed, because when I call git status I see this

``` r, engine='bash'
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   .gitignore
    modified:   wp-includes/wp-db.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    .gitattributes
    wp-config.common.php
    wp-content/uploads/
    wp-content/vpdb/
    wp-includes/wp-db.php.original
```

I could do that commit manually, but I also noticed that all of a sudden I can no longer save files with VIM either. Not sure if VersionPress has changed any permissions on the server?

When I go to `wp-admin/admin.php?page=versionpress` the page content is loading forever, i.e. no commits are being displayed.

I don't have root access on that server, so possibilities are somewhat limited.
- VersionPress version: 3.0.2
- WordPress version: 4.6.1
- OS, webserver, PHP: FreeBSD, Apache, PHP 5.6.24
- Git version: 2.8.1

**Comment by borekb** [comment]
Hi @nickw108, did you get it resolved? It looks like VersionPress wasn't installed correctly on your server, not quite sure why. Maybe you found the root cause?

**Comment by m1m1k** [comment]
Hi I'm getting a similar problem after installing VersionPress on my site when trying to "Save Draft"

`
Warning: Invalid argument supplied for foreach() in [siteroot]/wp-content/plugins/versionpress/src/Database/VpidRepository.php on line 49

Warning: Invalid argument supplied for foreach() in [siteroot]/wp-content/plugins/versionpress/src/Database/VpidRepository.php on line 62

Warning: Cannot modify header information - headers already sent by (output started at [siteroot]/wp-content/plugins/versionpress/src/Database/VpidRepository.php:49) in [siteroot]/wp-admin/post.php on line 197

Warning: Cannot modify header information - headers already sent by (output started at [siteroot]/wp-content/plugins/versionpress/src/Database/VpidRepository.php:49) in [siteroot]/wp-includes/pluggable.php on line 1210`
