### ISSUE TITLE
Errors when trying to restore-site

### ISSUE THREAD

**Issue by slickorange** [versionpress/support#66]
Hi there. I am getting errors when I try to restore a site ("site restore"):

`
Success: Git merge driver added 
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ) at line 1 for query SELECT term_id, taxonomy FROM wp_term_taxonomy WHERE term_taxonomy_id IN () made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll, VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks, VersionPress\Synchronizers\TermTaxonomiesSynchronizer->synchronize, VersionPress\Synchronizers\SynchronizerBase->synchronize, VersionPress\Synchronizers\TermTaxonomiesSynchronizer->doEntitySpecificActions, VersionPress\Utils\WordPressCacheUtils::clearTermCache, clean_term_cache WordPress database error Duplicate entry '0-post_tag' for key 'term_id_taxonomy' for query create unique index term_id_taxonomy on wp_term_taxonomy(term_id, taxonomy) made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll, VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks, VersionPress\Synchronizers\TermTaxonomiesSynchronizer->synchronize, VersionPress\Database\Database->query WordPress database error Can't DROP 'term_id_taxonomy'; check that column/key exists for query drop index term_id_taxonomy on wp_term_taxonomy made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\Runner->start, WP_CLI\Runner->_run_command, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, VersionPress\Cli\VPInternalCommand->finishInitClone, VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll, VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks, VersionPress\Synchronizers\TermTaxonomiesSynchronizer->synchronize, VersionPress\Database\Database->query Success: Database synchronized
`

I can reproduce by:
1. Deleting VPDB folder
2. Activating VP
3. wp vp restore-site -siteurl='http://development/b/'

The errors get more as I make changes to the DB before I try to restore again.

**Comment by borekb** [comment]
@slickorange Are you trying to clone the site from a working one, or restore from a repo where you don't have a database yet?

**Comment by slickorange** [comment]
@borekb I have not made any clones. I simply activated VP, and then tried to restore the site from the repo. (In the same site.) So the site has a database.

**Comment by borekb** [comment]
Then you need `wp vp apply-changes` instead of `restore-site`. Can you try that?

**Comment by slickorange** [comment]
We are trying to use Versionpress a bit different than the standard use case. Since we have separate / remote dev, test & production environments that each have their own DB, cloning is not going to work for us.
The idea was that we activate VP in the development install, then push that to test & production.
When we push from dev to production again we do a normal git merge where the VPDB files are then mergerd and then do a restore-site on production to get the latest db with the merged in changes from development. I don't know if that makes sense?

We had it working earlier in our project, not sure why we are having these issue now.

**Comment by borekb** [comment]
Yes, that workflow sounds fine. Are the sites using any 3rd party plugins? That might be causing problems.

**Comment by slickorange** [comment]
Yes, a few. I was wondering about that..
I guess I will need to wait for 4.0?

**Comment by slickorange** [comment]
I realize I am trying with apply-changes but on a db that was probably screwed up on the previous failed attempts, restoring db to original state now to try again - sorry, common sense, I know!

**Comment by borekb** [comment]
Ok, that might be it, let us know how you get on.
