### ISSUE TITLE
VersionPress Installation fails without fault in logs etc.

### ISSUE THREAD

**Issue by GeorgBNM** [versionpress/support#67]
The VersionPress Installation can be normally started with this screen:

![image](https://cloud.githubusercontent.com/assets/22478972/18883455/890ffe9a-84e3-11e6-9265-b9c01427fcd3.png)

Then it shows:

![image](https://cloud.githubusercontent.com/assets/22478972/18883670/66508068-84e4-11e6-90f7-acaf04ffd963.png)

After maintenance it comes back with:

![image](https://cloud.githubusercontent.com/assets/22478972/18883849/3ccd8046-84e5-11e6-94f0-2004591beb3f.png)

Activation is not completed.
There's nothing in the logs and the last .ini file in the specific folder contains this:

[FFCD02149CEB4731962D7EC81E339FF6.zip](https://github.com/versionpress/support/files/496207/FFCD02149CEB4731962D7EC81E339FF6.zip)

VersionPress version: 3.0.2
WordPress version: 4.6.1
OS, webserver, PHP: Debian 8, PHP 7.0.8
Git version: 2.1.4

Activated Plugins:

Redux Framework by Team Redux version 3.6.2, 
WP Missed Schedule by sLaNGjI's Team version 2014.1231.2016.1, 
Advanced Custom Fields: Repeater Field by Elliot Condon version 1.1.1, 
Advanced Custom Fields - Widget Relationship Field add-on by Dallas Johnson version 1.3.4, 
Advanced Custom Fields by Elliot Condon version 4.4.9, 
Amazon Simple Affiliate (ASA 2) by Timo Reith version 1.5.0, 
AMP by Automattic version 0.3.3, 
Antispam Bee by pluginkollektiv version 2.6.9, 
AntiVirus by pluginkollektiv version 1.3.9, 
Avatar Manager by Cătălin Dogaru version 1.6.1, 
BackWPup by Inpsyde GmbH version 3.3.4, 
Broken Link Checker by Janis Elsts, Vladimir Prelovac version 1.11.2, 
Code Snippets by Shea Bunge version 2.7.0, 
Easy Affiliate Links by Bootstrapped Ventures version 1.3, 
Easy Social Share Buttons for WordPress by CreoApps version 3.7.2, 
Edit Author Slug by Brandon Allen version 1.2.1, 
Email Address Encoder by Till Krüss version 1.0.5, 
Instant Articles for WP by Automattic, Dekode, Facebook version 3.1.3, 
FooTable by Brad Vincent version 0.3.1, 
Glue for Yoast SEO & AMP by Joost de Valk version 0.3.2, 
Google Website Translator by Prisna.net by Prisna version 1.3, 
Imsanity by Jason Hinkle version 2.3.6, 
InfiniteWP - Client by Revmakx version 1.6.1.1, 
MailChimp für WordPress by ibericode version 4.0.4, 
Ninja Formulare by Die WP-Ninjas version 3.0.5, 
Ultimate Nofollow by bitacre version 1.4.5, 
Optimus by KeyCDN version 1.4.7, 
plista by wordpress@plista.com version 1.5.1, 
Post Status Notifier Lite by ifeelweb.de version 1.8.9, 
Postman SMTP by Jason Hendriks version 1.7.2, 
Pricemesh - Price Comparison | Preisvergleich by pricemesh version 1.6.8, 
Q2W3 Fixed Widget by Max Bond version 5.0.3, 
Regenerate Thumbnails by Alex Mills (Viper007Bond) version 2.2.6, 
Shortcodes Ultimate by Vladimir Anokhin version 4.9.9, 
Social Icons Widget by Daniel Nisbet version 16.07, 
TablePress by Tobias Bäthge version 1.7, 
Category Order and Taxonomy Terms Order by Nsp-Code version 1.4.8, 
Themewich Sections by Andre Gagnon version 1.01, 
Themewich Shortcodes by Andre Gagnon version 1.4.2, 
Two Factor Authentication by David Nutbourne + David Anderson, original plugin by Oskar Hane version 1.2.13, 
User Role Editor by Vladimir Garagulya version 4.27.2, 
VersionPress by VersionPress version 3.0.2, 
Widget Alias by Mickey Kay, MIGHTYminnow version 1.7.2, 
Widget Logic by Alan Trewartha version 0.57, 
WooCommerce Cloak Affiliate Links by datafeedr.com version 1.0.5, 
WooCommerce Quantity Increment by Automattic, WooThemes version 1.1.0, 
WooCommerce by WooThemes version 2.6.4, 
Yoast SEO by Team Yoast version 3.5, 
WP All Import Pro by Soflyy version 4.3.1, 
WP-Appbox by Marcel Schmilgeit version 3.4.2, 
Auto Affiliate Links by Lucian Apostol version 5.2.7.5, 
WP Cerber by Gregory M version 2.9, 
WP-DraftsForFriends by Lester 'GaMerZ' Chan version 1.0.2, 
WP Most Popular by Matt Geri version 0.3.1, 
WP-Polls by Lester 'GaMerZ' Chan version 2.73.1, 
WP Rocket by WP Media version 2.8.14, 
WP to Twitter by Joseph Dolson version 3.2.13, 
Prosodia VGW OS für Zählmarken (VG WORT) by Prosodia – Verlag für Musik und Literatur version 3.15.6, 
WP All Import - ACF Add-On by Soflyy version 3.1.0, 
WP All Import - Link Cloaking Add-on by Soflyy version 1.0.8, 
WP All Import - User Import Add-On by Soflyy version 1.0.6, 
WP All Import - WooCommerce Add-On Pro by Soflyy version 2.3.0, 
XML Sitemap & Google News feeds by RavanH version 4.7.4

Any idea?
Thanks in advance!

Best regards

GeorgBNM

**Comment by borekb** [comment]
@GeorgBNM Thanks for the (nice!) report. The last INI seems fine, however, this site is way too complex for VersionPress. We're working on 3rd party plugin support in https://github.com/versionpress/versionpress/issues/1036, you can watch the progress there.

**Comment by GeorgBNM** [comment]
Hi @borekb ,

too complex? That's the reason i want to use VersionPress! ;)
Too bad it did not work!

Thanks.

**Comment by borekb** [comment]
We will get there one day :-)

**Comment by GeorgBNM** [comment]
Can't wait! :) Hurry up! ;)
