### ISSUE TITLE
Recommended workflow for team?

### ISSUE THREAD

**Issue by Spone** [versionpress/support#68]
Hello there,

as a team, we're working on the same Wordpress website, at the same time on our local computers and a staging environement (server). It's not clear from the docs what is the best way to proceed in this case.

We are working on different parts of the same website:
- some developers are coding the theme (which has its own git repo and is excluded from VersionPress using .gitignore)
- some developers are coding plugins (also excluded from VersionPress using .gitignore)
- some developers are installing and configuring plugins (these should be versioned by VersionPress)
- all the developers are modifying plugins and WP configuration
- writers are creating Pages, Posts and Media

We would like to be able to work either on local Wordpress install (for the developers) or staging environment (for the writers) and then periodically merge the code and contents together.

This way, developers can:
- pull the contents (Posts, Pages, Media) from the staging environment and test it / improve it locally
- merge the work from the other developers
- push everything to the staging environment

**Comment by unclhos** [comment]
This is how I use VersionPress with my team. I setup a private bare repo in another part of my server. I have a git sibling directory to my public_html so it's not viewable via the browser. This is where everyone will push and pull from. On all the local installs, we run a git hook file post-merge with the command `wp vp apply-changes`

Server side is a bit more difficult. I don't allow any changes to be made server side and it's for client viewing only. So on the bar repo we use the post-receive hook to do a fetch and hard reset and the websites git repo to the bare repo and then run the `wp vp apply-changes` command again.

One problem you may have is after pulling to your local computer if there are any merge conflicts, you'll have to resolve them and run the `wp vp apply-changes` command manually. I am still running VersionPress V2 so I have this issue a lot, but I believe changes in V3 should prevent a lot of these.

**Comment by borekb** [comment]
@Spone To add to waht @unclhos said, the [WP-CLI commands](https://docs.versionpress.net/en/feature-focus/wp-cli) are basically what you need. Your team members can `wp vp pull/push` freely between the clones (one clone per team member, staging server is another clone, private GitHub / Bitbucket repo likely another one).

**Comment by hbcfw** [comment]
@unclhos would you mind giving a more detailed step-by-step on how you accomplish this? We are new to VersionPress and would like to achieve this workflow.

**Comment by unclhos** [comment]
@hbcfw These workflow setups would need to be custom to what your individual team needs. My team uses it for development of lots of sites. So we also have lots of custom scripts to automate tasks. Things that would need to be considered: 1. Is this for a live site or a development site? 2. Are you going to use a bare repository or push/pull directly to another site? 3(a). If using bare repository, where are you hosting it? 3(b). How will you initiate the sync between bare repo and server site? (Hard resets or pull/merge? 4. Does this workflow need to be replicated many times over or just once? 
If you would like to hire help to develop a custom workflow that works for your needs, send an email to coders@redmugcoders.com

**Comment by borekb** [comment]
We've got a [blog post about remote workflows](https://blog.versionpress.net/2016/11/remote-workflows/) now. Does that help?

I'm going to close the issue now, feel free to open a new one if you need further help.
