### ISSUE TITLE
Advanced Custom Fields support issue

### ISSUE THREAD

**Issue by okolimar** [versionpress/support#71]
When restoring site that is using Advanced Custom Fields plugin from remote repository, images that are added as custom fields to pages for example are not restored. This is because ACF is linking images through their media ids that are not restored by VersionPress. I could not figure out an elegant workaround for this issue.

Thank you for great tool!

- VersionPress version: 3.0.1
- WordPress version: 4.6
- OS, webserver, PHP: dockerized WordPress instance, apache server, PHP 5.6
- Git version: stable

**Comment by pavelevap** [comment]
Hi,

you have to add support for `value-references` to Advanced Custom Fields plugin.

This feature is [available](https://blog.versionpress.net/2016/10/versionpress-4-0-alpha/) in latest 4.0-alpha1 version ([download](https://github.com/versionpress/versionpress/releases)).

You can find detailed manual [here](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) or use [example](https://gist.github.com/JanVoracek/b5530707ff19e3ccf1b85978d271e0bd) for WooCommerce (not complete).

**Comment by borekb** [comment]
Hi @okolimar, as @pavelevap said, the plugin definition would need to written for ACF which does not exist yet. It is a popular plugin so it will be high on the priority list, however, there is no quick workaround at the moment. Do you think you would attempt to write it yourself?

Anyway, I'm closing this issue for now, feel free to comment if you need further help.

**Comment by okolimar** [comment]
Thanky You for all answers. Currently I am busy, but I will keep this in mind :)
