### ISSUE TITLE
Using a development life-cycle -  Dev, Staging, Live

### ISSUE THREAD

**Issue by lizat** [versionpress/support#72]
Hi Versionpress,

I am considering using VP. I would like to see the instructions on how to install VP in a dev environment and them how to promote to e.g. staging, then to production. Do you have something I can read about this - for example one of my questions is do I install VP on each environment and if so how are things synchronised?

Thank you,

Liz

**Comment by borekb** [comment]
Hi @lizat, there's [this blog post](https://blog.versionpress.net/2016/11/remote-workflows/), let me know if it answers your questions about the workflows.

**Comment by lizat** [comment]
Thank you it does mostly.

I think our workflow will be like this:

 1. Development (& testing) on Local Machine with web server, promote to
 2. Staging on production server, pre-live tests in the production
    environment, promote to
 3. Live site on the production server

I think therefore this is logically what I do:

  * Install VP on the development server (1)
  * First time only: create a Git Repo for the project
  * Then when ready I use VP push to upload to Git Repo
  * Use VP push to load from the Git Repo to Staging, when ready
  * Use VP Push to load from Git Repo to Live

Therefore I only have VP on the dev environment. If I use this approach 
it is single threaded, by which I mean: I must have completed the 
previous release all the way to installed in Live before I push new 
changes to the Git Repo. If this assumption is correct what would be the 
best method to make that independent - do I need two Repos or two VP 
installations?

I haven't used Git previously only other version management software 
locally with non WP projects. I assume that creating Repos is something 
I do on Git rather than in VP?

Thank you for the advice,

Liz

**Comment by borekb** [comment]
VersionPress needs to be installed in all environments; it's its code that synchronizes the database after Git push / pull.

Also note that in Git, there are multiple repos, all equal to each other. Each site clone will have its own repo.

**Comment by borekb** [comment]
I'm closing this for now, if you have further questions @lizat feel free to reopen or create a new ticket.

**Comment by lizat** [comment]
yes, thank you for helping.
