### ISSUE TITLE
Unable to uninstall VersionPress

### ISSUE THREAD

**Issue by mravery** [versionpress/support#73]
I have been using VersionPress and wanted to uninstall it to try out some plugins that had known issues with it. Upon deactivating I received this message:

`Fatal error: Uncaught Error: Call to undefined method VersionPress\ChangeInfos\UntrackedChangeInfo::getScope() in /Users/avery/dev/wordpress/wp-content/plugins/versionpress/src/Utils/UninstallationUtil.php:40 Stack trace: #0 /Users/avery/dev/wordpress/wp-content/plugins/versionpress/admin/deactivate.php(56): VersionPress\Utils\UninstallationUtil::uninstallationShouldRemoveGitRepo() #1 /Users/avery/dev/wordpress/wp-admin/admin.php(250): include('/Users/avery/de...') #2 {main} thrown in /Users/avery/dev/wordpress/wp-content/plugins/versionpress/src/Utils/UninstallationUtil.php on line 40`

**I am still unable to deactivate/uninstall. How can I resolve this issue?**

Please be specific when describing the issue. Also, these details will help:

`array (
  'wordpress-version' => '4.7',
  'versionpress-version' => '4.0-alpha1',
  'operating-system' => 'Darwin celestra.fnanet 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64',
  'php-version' => '7.1.0',
  'php-sapi' => 'apache2handler',
  'git-version' => '2.10.1',
  'git-full-path' => '/usr/bin/git
',
)
'apache2handler' => 
  array (
    'Apache Version' => 'Apache/2.4.23 (Unix) PHP/7.1.0',
    'Apache API Version' => '20120211',
    'Server Administrator' => 'avery@avericity.com',
    'Hostname:Port' => 'wordpress.localhost:0',
    'User/Group' => 'avery(501)/20',
    'Max Requests' => 'Per Child: 0 - Keep Alive: on - Max Per Connection: 100',
    'Timeouts' => 'Connection: 60 - Keep-Alive: 5',
    'Virtual Server' => 'Yes',
    'Server Root' => '/usr/local/opt/httpd24',
    'Loaded Modules' => 'core mod_so http_core prefork mod_authn_file mod_authn_core mod_authz_host mod_authz_groupfile mod_authz_user mod_authz_core mod_access_compat mod_auth_basic mod_reqtimeout mod_filter mod_mime mod_log_config mod_env mod_headers mod_setenvif mod_version mod_unixd mod_status mod_autoindex mod_vhost_alias mod_dir mod_alias mod_rewrite mod_php7',
    'engine' => '1',
    'last_modified' => '0',
    'xbithack' => '0',
  )
`

**Comment by mravery** [comment]
I did a little bit of research into the code. `getScope` is a function defined in the `TrackedChangeInfo` class but it isn't a part of the `ChangeInfo` interface. When an `UntrackedChangeInfo` object gets stored, it doesn't have a `getScope()` method, but the code assumes that the object is one of the other types of `ChangeInfo` objects.

I modified UninstallationUtil.php:40 with this:

`return method_exists($changeInfoList[0], "getScope") && $changeInfoList[0]->getScope() === 'versionpress' && $firstChangeInfo->getAction() === 'activate';`

This allowed the process to continue but then I got this:

`Warning: include(/Users/avery/dev/wordpress/wp-content/plugins/versionpress/vendor/composer/../../src/Utils/UninstallationUtil.php): failed to open stream: No such file or directory in /Users/avery/dev/wordpress/wp-content/plugins/versionpress/vendor/composer/ClassLoader.php on line 412

Warning: include(): Failed opening '/Users/avery/dev/wordpress/wp-content/plugins/versionpress/vendor/composer/../../src/Utils/UninstallationUtil.php' for inclusion (include_path='.:') in /Users/avery/dev/wordpress/wp-content/plugins/versionpress/vendor/composer/ClassLoader.php on line 412

Fatal error: Uncaught Error: Class 'VersionPress\Utils\UninstallationUtil' not found in /Users/avery/dev/wordpress/wp-content/plugins/versionpress/admin/deactivate.php:56 Stack trace: #0 /Users/avery/dev/wordpress/wp-admin/admin.php(250): include() #1 {main} thrown in /Users/avery/dev/wordpress/wp-content/plugins/versionpress/admin/deactivate.php on line 56`

**Comment by mravery** [comment]
After checking again, the error happens because I refresh a page that I shouldn't. The fix that I submitted should work. Feel free to implement this or close this issue.

**Comment by borekb** [comment]
Hi @mravery, that indeed feels like a bug in VP. Would you mind opening an issue in the [main repo](https://github.com/versionpress/versionpress/)? Glad that you found a workaround, I'm closing this.
