### ISSUE TITLE
Versionpress not tracking Database changes

### ISSUE THREAD

**Issue by KT-Reality** [versionpress/support#74]
- VersionPress version: 3.0.2
- WordPress version: 4.7
- OS, webserver, PHP: 5.6.23
- Git version: 2.11.0

Hi,

I have installed versionpress which works fine for file changes but unable to track database changes. Though I have also noticed that it has not created folder "vpdb" which is to be under wp-content folder. Please suggest steps to resolve and whats going wrong with the setup.

Thanks,
Komalchand

**Comment by borekb** [comment]
Hi @KT-Reality, did the activation process end with some errors? Did you activate via wp-admin or WP-CLI?

**Comment by KT-Reality** [comment]
As usual smooth process of plugin installation but in first attepmt it fetched the error of "git not detected".

**Comment by borekb** [comment]
That sounds like VersionPress was not fully activated, is that right? See https://docs.versionpress.net/en/getting-started/installation-uninstallation#installation.

**Comment by KT-Reality** [comment]
Yes, I think same. I have followed the same procedure as mentioned in the link. Even though one query for you : Where to execute the command like "wp vp update ./versionpress.zip".

**Comment by KT-Reality** [comment]
Actually I am working on my machine(xampp) with my localhost

**Comment by KT-Reality** [comment]
vesrionpress uninstall and again installed with smoothly but it doesn't track db changes like plugin activation/deactivation/theme activate/post create/delate and so on. Please can you give some idea to track the problem So I will sort problem myself. Your suggestion will be very helpful.

**Comment by KT-Reality** [comment]
Hey, Now I am able to see the database changes via VP but while hitting to "Undo" button it show the error as "Error: Objects with missing references cannot be restored. For example we cannot restore comment where the related post was deleted." 

Please look into this.

**Comment by borekb** [comment]
That is not an error, it's a correct state. Some changes cannot be undone if newer, incompatible changes have been done since then.

Glad that you made it work!

**Comment by KT-Reality** [comment]
Some database changes works with a big **bug**. while **rollback** to the changes like **post created** it 

> loggout the user means it directly delete the user from database

. This is totally unexpected.

**Comment by borekb** [comment]
It's hard to tell what went wrong without any additional details. Are you running a site with some plugins by any chance? Those are not currently supported, see https://docs.versionpress.net/en/getting-started/about-eap.

**Comment by KT-Reality** [comment]
The site we are testing includes the following plugins:

1.  Advanced Custom Fields
2. Advanced Custom Fields Pro
3. Advanced Custom Fields: Font Awesome
4. Buooy Scroll To Top	
5. Favicon by RealFaviconGenerator
6. GK Widget Rules
7. Insert HTML Snippet
8. MiwoFTP	
9. Responsive Lightbox
10. Symple Shortcodes
11. TW Pagination
12. WordPress Importer

Do you think any of the above plugins would affect the VP performance?

**Comment by borekb** [comment]
Such site will not work with VersionPress 3.x, unfortunately. We're working on plugin support as part of VersionPress 4.0 which should ship in the first half of this year. You can track the progress here: https://github.com/versionpress/versionpress/milestone/16.

**Comment by KT-Reality** [comment]
Thanks @borekb AS you I asked previously to update the VP version, So can you please at least suggest the way to upgrade VP 3.0 to VP alpha version.

**Comment by KT-Reality** [comment]
Unfortunately client has suggested to stop to use this VP plugin due to this bug(user deleted while rollback) even lot of hours spend for VP.

**Comment by borekb** [comment]
VersionPress is currently in pre-production mode, that is correct. Thanks for trying it though.

**Comment by KT-Reality** [comment]
Hi @borekb again I have made some test with VP and surprisingly got best output for both files as well as database changes
