### ISSUE TITLE
change path of git on wp-config

### ISSUE THREAD

**Issue by nusquama** [versionpress/support#76]
hi

versionpress doesnt work. i am on planethoster, and i have to change path of git on wp-config

but i dont know how to do

thanks

**Comment by borekb** [comment]
Hi, it's the `VP_GIT_BINARY` option in configuration, see https://docs.versionpress.net/en/getting-started/configuration#vp_git_binary (be sure to read the whole page).

**Comment by nusquama** [comment]
thanks, but, i dont know how to write exactly in wp-config.

**Comment by borekb** [comment]
Hi, see WordPress documentation for that. Thanks.

**Comment by nusquama** [comment]
i write this in wp-config
wp vp config VP_GIT_BINARY '/custom/path/to/git'
and it's no working

**Comment by borekb** [comment]
What's not working? The configuration is not written? It is but has no effect? Could you post a piece of the resulting `wp-config.php` please?

**Comment by nusquama** [comment]
i put exactly this in my wp-config.php
wp vp config VP_GIT_BINARY '/usr/local/cpanel/3rdparty/bin';

and i have errror 500 and cannot access my website
i am with planethoster. And they said git is '/usr/local/cpanel/3rdparty/bin' 

but i am not a specialist of php, and i don't know how to said to versionpress to go to path of git

**Comment by borekb** [comment]
`wp vp config...` is a command-line command, not something that should be put to `wp-config.php`. Please refer to https://docs.versionpress.net/en/getting-started/configuration.

**Comment by nusquama** [comment]
so i dont't know how to give path on versionpress for git :(

**Comment by hxinen** [comment]
Hi, 

Just add this to your wp-config:
`define('VP_GIT_BINARY', '/usr/local/cpanel/3rdparty/bin/git');`
