### ISSUE TITLE
Cannot activate VP due to GIT and access rules

### ISSUE THREAD

**Issue by dklebedev** [versionpress/support#77]
Hello. System check has to ! marks:
1. GIT below 1.9
2. You either don't have a supported web server or rules cannot be enforced.

My server is Apache. How do I approach this?

**Comment by dklebedev** [comment]
*two ! marks

**Comment by dklebedev** [comment]
My hosting configured GIT and now I seem to be running VP.

**Comment by borekb** [comment]
Good!
