### ISSUE TITLE
VP doesn't seem to be tracking changes

### ISSUE THREAD

**Issue by dklebedev** [versionpress/support#78]
array (7)
   "wordpress-version" => "4.7" (3)
   "versionpress-version" => "4.0-alpha1" (10)
   "operating-system" => "Linux pixel.beget.ru 4.8.14-0-beget-acl #1 SMP Sun Dec 11 17:53:02 UTC 2016 x86_64" (82)
   "php-version" => "5.6.29" (6)
   "php-sapi" => "apache2handler" (14)
   "git-version" => "2.11.0.258" (10)

**Comment by dklebedev** [comment]
Changed the theme. Added a blogpost. 

VP screen reads: No more commits to show.

**Comment by borekb** [comment]
Are you running some WP plugins? Were there some warnings on the activation screen?

**Comment by dklebedev** [comment]
Clean install.
There was a warning about not being able to enforce access rules.

**Comment by borekb** [comment]
Is the browser console showing some JS errors or warnings? Could you post some screenshots?

**Comment by dklebedev** [comment]
Okay. I'll do that when I'm at my desktop.

**Comment by dklebedev** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by dklebedev** [comment]
http://pasteboard.co/lfWrzCqJO.png

**Comment by borekb** [comment]
This commonly happens with 3rd party plugins but if you don't have them, it must be something else. The only warning you indicated were about the unsupported web server. Could you attach a [full system info](https://docs.versionpress.net/en/troubleshooting/system-info-page) please?

**Comment by borekb** [comment]
Closing this to clear things up, if you still have this issue @dklebedev feel free to reopen.
