### ISSUE TITLE
Revolutions Slider Support

### ISSUE THREAD

**Issue by eddielee394** [versionpress/support#79]
- VersionPress version: 4.0-alpha
- WordPress version: 4.7.1
- OS, webserver, PHP:  Linux, Apache, 7.0.14 (siteground)
- Git version: 2.6.1

Tested Revolution Slider on a few different VP instances and have been able to confirm it is not currently compatible with VP.  

When cloning, rev_slider tables are not included in cloned tables.  

`Fatal error: Uncaught Exception: fetch - <b>Table 'website_lms.wp_staging_revslider_sliders' doesn't exist</b><br>---<br> Query: select * from wp_staging_revslider_sliders where `type` != &#039;template&#039; OR `type` IS NULL order by id ASC in /home/website/public_html/staging/wp-content/plugins/revslider/includes/framework/functions.class.php:14 Stack trace: #0 /home/website/public_html/staging/wp-content/plugins/revslider/includes/framework/db.class.php(26): RevSliderFunctions::throwError('fetch - <b>Tabl...', -1) #1 /home/website/public_html/staging/wp-content/plugins/revslider/includes/framework/db.class.php(41): RevSliderDB->throwError('fetch - <b>Tabl...') #2 /home/website/public_html/staging/wp-content/plugins/revslider/includes/framework/db.class.php(145): RevSliderDB->checkForErrors('fetch') #3 /home/website/public_html/staging/wp-content/plugins/revslider/includes/slider.class.php(2940): RevSliderDB->fetch('wp_staging_revs...', '`type` != 'temp...', 'id', '', 'ASC') #4 /home/website/public_html/staging/ in /home/website/public_html/staging/wp-content/plugins/revslider/includes/framework/functions.class.php on line 14`

**Comment by borekb** [comment]
Thanks for confirming this. There is currently no [plugin definition](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) for Revolution Slider which is why its tables are not included in the cloned site.
