### ISSUE TITLE
Posts/Pages password protected by default

### ISSUE THREAD

**Issue by smith64fx** [versionpress/support#8]
Hello,
When I clone a site, all the posts and pages on the cloned site are password protected by default. Any idea why this is so?

**Comment by borekb** [comment]
Hi, can you please check your INI files inside `wp-content/vpdb/posts` whether they have `post_password = ""` (no password protection) or `post_password = "somevalue"` (pwd protection enabled)? Is your database in sync with that?

**Comment by pavelevap** [comment]
@smith64fx: Hi, I could not reproduce. I installed WP 4.4 (Twenty Sixteen), VersionPress 2.2, added 2 Posts and 2 Pages (one of those password protected). Then I cloned this site: `wp vp clone --name=staging`, see: http://docs.versionpress.net/en/sync/cloning. My staging site works as expected, only one Post is password protected. Do you have any additional info about WP and VP versions and activated theme/plugins?

**Comment by smith64fx** [comment]
Hey @pavelevap I found out what the problem was. my server was not right configured and created everything made by exec() as a root user, so the files could not be properly processed.

Can close this... Thank you for your help!
