### ISSUE TITLE
Show you how to activate the plugin?

### ISSUE THREAD

**Issue by ecountry** [versionpress/support#80]
Quick summary
array (
  'wordpress-version' => '4.7.1',
  'versionpress-version' => '3.0.2',
  'operating-system' => 'Linux vs-120 3.2.0-4-amd64 #1 SMP Debian 3.2.81-2 x86_64',
  'php-version' => '5.6.29',
  'php-sapi' => 'cgi-fcgi',
  'git-version' => '1.9.1',
  'git-full-path' => '/usr/bin/git
',
)
Git
array (
  'git-binary-as-configured' => 'git',
  'git-available' => true,
  'git-version' => '1.9.1',
  'git-binary-as-called-by-vp' => 'git',
  'git-full-path' => '/usr/bin/git
',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => true,
)

Good afternoon!

We install your plug-in, set up php and live, but the final tap minimize activation is still not active. In the admin panel's warnings: https://www.screencast.com/t/theCKsRfC What you need to do in order to activate the plugin?

![image](https://cloud.githubusercontent.com/assets/101152/22059883/f7bfe6d2-dd6e-11e6-9a48-86a19fcd58c1.png)

**Comment by borekb** [comment]
Hi, you have 29 plugins which isn't going to work with VersionPress, currently. Sorry for that, we're working on plugin support for the upcoming 4.0.

**Comment by ecountry** [comment]
That is, the plug-in will not work for me? Or if you put version 4.0 (alpha), it can earn?

**Comment by borekb** [comment]
Yes, VersionPress will not work for site. 4.0 is a work in progress and will likely not help either at this point.

**Comment by ecountry** [comment]
Very sorry about .... And when can we expect the release of working?

**Comment by borekb** [comment]
v4 will be released this year (no ETA) and then it depends how quickly will plugin authors or the community write plugin definitions.

**Comment by ecountry** [comment]
Thank you! It remains to wait ... What a pity that now plug-in development ... It is very necessary ...
