### ISSUE TITLE
VP Branches

### ISSUE THREAD

**Issue by eddielee394** [versionpress/support#82]
What is the recommended workflow when using git branches and VP?  Particularly when it comes to merging a feature branch with master.

**Comment by borekb** [comment]
There's no support for this through the UI but you can branch and merge on the command line.

**Comment by eddielee394** [comment]
Right, I guess my question was geared more towards whether there are any special VP commands required when merging a branch with master to make sure the db changes are synced properly.  Or would we just do something like:  
`git checkout master`
`git merge <branch-name>`
`wp vp apply-changes` 

For example, my current workflow is setup for team development:  
- Production
- Staging (Production Clone)
  - Dev1 (Staging clone)
  - Dev2 (Staging clone) 

Which basically consists of our Production environment which pulls from Staging.  Staging then pulls from both Dev1 & Dev2.  Dev1 & Dev2 being independent development working directories.  

- Developer creates feature branch on Dev1/Dev2, does work,  pushes to Staging.  
- Once approved on staging, branch is merged to staging Master & pushed to Production environment.  

Also, I noticed that VP automatically commits changes to the working directory without having to run `git commit`.   Is this normal behavior?  Or is there any way we can control when a revision is commited like with the standard git-flow (i.e. using `git commit`)?  It's not a crucial issue, I'm just noticing that with more complex workflow setups, it causes the git history to become a bit long & sloppy.  Ideally, if we could control when changes are committed, it'll allow for a much cleaner revision history by including all my working changes in a single commit.  

Btw, I've been reaching out directly to all the developers of the premium themes/plugins I consistently use about integrating native VP support as part of the dev roadmap.  I've been linking them to the plugin support thread here on github & have been getting a positive response so far.  Hopefully, it'll help with expanding the plugin support for VP in the future.  Can't tell you how much i wish i could use VP with some of the more complex sites I've been building with Membermouse, woocommerce, and particularly visual composer and revolution slider.

**Comment by borekb** [comment]
Hi @eddielee394,

1. Yes, just `apply-changes` after Git commands should be alright.
2. VersionPress doesn't commit file changes automatically – it should just display a notification that there are some. Something weird is going on. One possibility is that files are committed with some unrelated change like updating an option or something, but that should be normally prevented by VersionPress (it only commits related files so if you have edited file on the disk and an option changes, only that option change should be committed).

Thanks for your effort in contacting plugin / theme authors, that is really great. Hopefully it can be production-ready quite soon, we're looking forward to it ourselves :)

**Comment by eddielee394** [comment]
> VersionPress doesn't commit file changes automatically
Sorry, let me clarify.  VP isn't committing file changes automatically.  It's committing the db changes automatically.  It looks like the commits are changes in the options, but nonetheless it's creating a pretty long & messy commit history. 

Not sure if it's possible, but is there anyway we'd be able to restrict events like this so that they're only committed when we manually do `git-commit` or something similar?  For example, in the screenshot below I have 12 commits in the history that I believe are options updates just from disabling notifications in the admin panel.  

See screenshot: http://i.imgur.com/VX2MExe.png

**Comment by borekb** [comment]
Such updates should be generally ignored (similar concept to `.gitignore`, just more VersionPress-specific). It can be done in a plugin definition file as described [here](https://github.com/versionpress/versionpress/blob/325cd8335b4083a17d2e489c5b72b018f7f103eb/docs/Plugin-Support.md#ignoring-entities).
