### ISSUE TITLE
cannot clone, no remotes created at all, only files

### ISSUE THREAD

**Issue by waltersm** [versionpress/support#85]
Hi,
Using:
versionpress v4 alpha, wp 4.6.2, Debian 8.1, Apache 2, PHP 5.6, git 2.1.4

mnw@jessies:~/www.newgreenpowersolutions.co.uk/html$ wp vp clone --name=stage4 --siteurl=https://www.newgreenpowersolutions.co.uk/stage4 --debug
Debug (bootstrap): No readable global config found (0.009s)
Debug (bootstrap): No project config found (0.01s)
Debug (bootstrap): No package autoload found to load. (0.166s)
Debug (bootstrap): ABSPATH defined: /home/mnw/www.newgreenpowersolutions.co.uk/html/ (0.166s)
Debug (bootstrap): Begin WordPress load (0.166s)
Debug (bootstrap): wp-config.php path: /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-config.php (0.166s)

PHP Notice:  Undefined index: cpt_slider in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 28
Notice: Undefined index: cpt_slider in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 28
PHP Notice:  Undefined index: cpt_service in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 55
Notice: Undefined index: cpt_service in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 55
PHP Notice:  Undefined index: cpt_portfolio in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 82
Notice: Undefined index: cpt_portfolio in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 82
PHP Notice:  Undefined index: cpt_testimonial in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 166
Notice: Undefined index: cpt_testimonial in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 166
PHP Notice:  Undefined index: cpt_client in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 194
Notice: Undefined index: cpt_client in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 194
PHP Notice:  Undefined index: cpt_team in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 221
Notice: Undefined index: cpt_team in /home/mnw/www.newgreenpowersolutions.co.uk/html/wp-content/themes/enigma-premium/core/customs/cpt.php on line 221
Debug (bootstrap): Loaded WordPress (0.525s)
Debug (bootstrap): Running command: vp clone (0.525s)
Success: Site files cloned
The Git repo of this site already defines remote 'stage4', overwrite it? [y/n] y
Error: Could not update remote's URL
mnw@jessies:~/www.newgreenpowersolutions.co.uk/html$ wp vp check-requirements

Success: PHP 5.6+
Success: 'mbstring' extension
Success: Execute external commands
Success: Git 1.9+ installed
Success: Write access on the filesystem
Success: Access rules can be installed

Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 
- WordPress version:
- OS, webserver, PHP:
- Git version:

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

mnw@jessies:~/www.newgreenpowersolutions.co.uk/html$ wp --info
PHP binary:     /usr/bin/php5
PHP version:    5.6.27-0+deb8u1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.1.0

$ git remote -v
<returns nothing>

Any help would be great, I'd love to be able to use this

Ta,
Mark.

**Comment by borekb** [comment]
Hi @waltersm, there seem to be some errors / warnings unrelated to VersionPress (in you there's `cpt.php`), could you try to get rid of those and try again?

The attempt to overwrite a Git remote means that you cloned to `stage4` before. When VersionPress clones the site, it sets up Git remote to point to the clone so that for example `wp vp pull --from=stage4` works in the future (`stage4` is configured to point to the Git repo in the sibling directory).

When you answer "yes" to the prompt to overwrite the remote, it should do it. Is the Git repo writable by the user running the shell command? For example, can you `git commit` from command line to the main site?

Thanks.

**Comment by waltersm** [comment]
Hi,
how would I go about removing those errors - seems they're caused by our theme using custom database tables? I can't remove the tables as it would stop our site from working?

I have not cloned stage4 before - never - I have tried a new name everytime and everytime the same result.

There are no git remotes as I've shown - it seems to never have attempted to create any - ie never got that far?

I'll check the git commit but the user is a member of the group that owns the parent folder and all the files.

Ta,
Mark.

**Comment by borekb** [comment]
The remote thing is really strange. Can you confirm that:

1. VersionPress creates commits fine e.g. when creating posts, editing options etc.?
2. VersionPress creates commits when you change a file on a disk (e.g., via FTP) and then go to the VP screen in wp-admin and commit from there?
3. `git commit` works from the command line?

Thanks!

**Comment by waltersm** [comment]
ok my bad, perms were all messed up, the plugin is installed by user www-data but my linux user was a member of www-data group and the group did not have the same perms on the files as the owner, so I couldn't even git commit because it couldn't lock the .git file.
Trying the clone again.

**Comment by borekb** [comment]
Cool! BTW, custom tables in your theme will not work correctly unless they have [definition files](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) for them, but those are not even supported for themes yet.

**Comment by waltersm** [comment]
ok cool, the clone works, sorry for wasting anyone's time and thanks for looking at this so quickly.

**Comment by waltersm** [comment]
Thanks, I'm replacing the theme as part of the change so it should be fine

Thanks again
Mark
