### ISSUE TITLE
Remote (Local / Offline) VersionPress Install

### ISSUE THREAD

**Issue by wishmedia** [versionpress/support#86]
- VersionPress version: (Latest)
- WordPress version: (Latest)
- OS, webserver, PHP: (7.x)
- Git version: (2.11.0)

Trying to set up a Remote Workflow on Git:

I ran the “Git clone” function, then I tried wp vp restore-site.

The first time it said “wp core needs to be installed”. This wasn’t noted on your how-to’s (https://blog.versionpress.net/2016/11/remote-workflows/), but I pulled the DB off the remote server and tried again.

After I installed the DB, Versionpress did not exist in the plugin folder (so wp vp restore-site did nothing). Although this also wasn't stated in your how-to's, I downloaded the Versionpress plugin and dragged the folders in manually.

**_Note: VP Was installed on the live server._**

After I installed both the DB & VP, I tried the “wp vp restore-site” and it just errored out. I couldn’t get it to work:

Error: Unfortunately, this site was not tracked by VersionPress.
            Therefore, it cannot be restored.

**Comment by borekb** [comment]
Hi @wishmedia, the blog post is a quick overview of the possibilities, not a complete step by step procedure as noted in there. Sorry if it was confusing.

You shouldn't be pulling the database itself, like the MySQL dump or something, everything is restored from the Git repository. Full docs are here: https://docs.versionpress.net/en/feature-focus/wp-cli#vp-restore-site.

In your Git repo, do you see `wp-content/vpdb` folder and then some files and folders in it?
