### ISSUE TITLE
Versionpress is installed and activated but I am getting Error: 'vp' is not a registered wp command when trying to use the terminal

### ISSUE THREAD

**Issue by jessiemele** [versionpress/support#88]
I recently installed and activated versionpress on my wordpress site primarily to use it for a testing version with the cloning site and am having an issue early on. I have WP-CLI installed and that is working properly, but when I try and put in a command with ‘vp’ example: "wp vp clone --name=staging" I get the error: Error: 'vp' is not a registered wp command. See 'wp help’. I’m not sure if I missed a step somewhere but no commands with ‘vp' work. I have tried version 3.0.2 and 4.0. It is creating the wp-config.common.php and linking to it at the top of the wp-config.php file, but the wp-config.common.php is blank. Am I missing something?
- VersionPress version: 3.0.2 (tested with 4.0 as well)
- WordPress version: 4.7.2
- PHP: 5.6.29
- Git version: 2.7.3

**Comment by borekb** [comment]
Hi @jessiemele, `wp vp ...` should work regardless of `wp-config.php`. Can you execute other WP-CLI commands on that site fine? For example, you can get info about the VersionPress plugin like this:

```
$ wp plugin get versionpress
```

It should print out something like this:

```
+-------------+-------------------------------------+
| Field       | Value                               |
+-------------+-------------------------------------+
| name        | versionpress                        |
| title       | VersionPress                        |
| author      | VersionPress                        |
| version     | DEV                                 |
| description | Git-versioning plugin for WordPress |
| status      | active                              |
+-------------+-------------------------------------+
```

**Comment by jessiemele** [comment]
Hi @borekb thank you again, I ran that and got this 
![screen shot 2017-03-03 at 5 16 57 pm](https://cloud.githubusercontent.com/assets/7845167/23571104/5efd481a-0035-11e7-89f5-d6a77e84b32f.png)
back

**Comment by borekb** [comment]
Strange.. you can try adding `--require=wp-content/plugins/versionpress/src/Cli/vp.php` to your WP-CLI command but it shouldn't be necessary when VersionPress is active.

**Comment by jessiemele** [comment]
I did that and got back:$ --require=wp-content/plugins/versionpress/src/Cli/vp.php
-bash: --require=wp-content/plugins/versionpress/src/Cli/vp.php: No such file or directory

**Comment by borekb** [comment]
It needs to be added to a standard command, e.g., 

```
wp vp clone ... --require=wp-content/plugins/versionpress/src/Cli/vp.php
```

See https://docs.versionpress.net/en/feature-focus/wp-cli#working-with-versionpress-commands.

**Comment by jessiemele** [comment]
that worked when I added the string after my command, it doesn't work without it but it does when I use that. I switched back to version 4.0 and when I run that command now I get this:
[baron-mordo]$ wp vp clone --name=staging --require=wp-content/plugins/versionpress/src/Cli/vp.php
Database tables for the clone already exist, they will be dropped and re-created. Proceed? [y/n] y
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/jamdel22/dcapclaims.com/wp-content/plugins/versionpress/src/Git/GitRepository.php on line 491

**Comment by pavelevap** [comment]
Hi @jessiemele,

it looks like you are using PHP 5.6.x, but WP-CLI is specifically using some older PHP version. Which webhost do you use? Parse error is probably related to [this line](https://github.com/versionpress/versionpress/blob/4.0-alpha1/plugins/versionpress/src/Git/GitRepository.php#L491), where is `...` operator for variadic function (available only in PHP 5.6 and higher).

Could you please try runnig `wp cli info` command to get PHP version info?

**Comment by jessiemele** [comment]
this site is on dreamhost and here is the info after running wp cli info:
PHP binary:	/usr/local/php55/bin/php
PHP version:	5.5.38
php.ini used:	/etc/php55/php.ini
WP-CLI root dir:	/usr/local/wp
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.0.0

**Comment by pavelevap** [comment]
Yes, it looks like WP-CLI is using PHP 5.5 which is not compatible with latest VP version. You can try VP 3.0.2, ask Dreamhost support to update PHP version for WP-CLI or try to revert [this](https://github.com/versionpress/versionpress/commit/9dafd8aa09bc03df86e1872695fe269bc1f7fdc6) commit from your VP installation (not sure if there are possible consequences).

I will create issue for main VP project, because we should also check PHP version for WP-CLI, but I am not sure if there will be support for PHP 5.5.x, even if it very common issue for shared hosts (Dreamhost, SiteGround, etc). What do you think @borekb?

**Comment by borekb** [comment]
Great that you were able to track the issue down! PHP 5.6 is required since https://github.com/versionpress/versionpress/issues/726, there's some explanation there. For a WP-CLI PHP version, we even have this issue: https://github.com/versionpress/versionpress/issues/1077. VersionPress 4.0 should better warn about incorrect PHP version.

**Comment by pavelevap** [comment]
Ooops, I did not notice my own issue :-)

**Comment by borekb** [comment]
:)

@jessiemele please try to contact DreamHost, maybe they will be able to update the PHP version for you. I'm going to close this issue now, if we can help with anything else please reopen it or create a new one. Thanks.

**Comment by jessiemele** [comment]
@borekb in dreamhost it says it is running 5.6 fastCGI, so is that not the case if it is different when I run wp cli info?

**Comment by jessiemele** [comment]
@borekb sorry I just answered my own question, I'll contact dreamhost to see if they can update my wp-cli version of PHP, sorry for reopening.

**Comment by borekb** [comment]
No problem, good luck!
