### ISSUE TITLE
Deletion failed: error

### ISSUE THREAD

**Issue by meadows19** [versionpress/support#89]
Hello.

- VersionPress version: 3.0.2
- WordPress version: 4.7.3
- OS, webserver, PHP: DigitalOcean, Ubuntu, PHP 7
- Git version: Unknown

1) I successfully 'deactivate' the plugin from the Wordpress Plugins page.
2) Then I 'delete' the plugin from the plugins list. This is supposed to remove all data.
3) It seems to be working, but then an error message is shown at the top of the page: "Deletion failed: error".

I refreshed the page. The Versionpress entry is gone.

My question is: how can I be sure that all the associated data is also deleted?
What are the file locations I need to check on the server?
Is there anything I need to manually change? I saw mention of manually restoring the wp-db.php file from wp-db.php.original. I don't know what that means or if it applies in this case. How can I check?

Thank you kindly for your help.

**Comment by borekb** [comment]
Hi @meadows19, during [deactivation](https://github.com/versionpress/versionpress/blob/81239e533d1e94fb609cfcb0503384880497e7f4/plugins/versionpress/setup-hooks.php#L604), this happens:

- `wp-db.php` is restored to the original WordPress version
- Git merge driver is uninstalled

Then, when you delete the plugin, the [uninstallation script](https://github.com/versionpress/versionpress/blob/master/plugins/versionpress/uninstall.php) does this:

- Drops the `wp_vp_id` table.
- Removes `wp-content/vpdb` folder
- Moves `.git` folder to `wp-content/vpbackups` just to be sure
- Then some smaller things like removes certain constants from `wp-config.php`, removes some options and usermeta, etc.

**Comment by meadows19** [comment]
Thank you for your reply and the details @borekb 

It seems the deactivation went fine, so I'm assuming that both of these were successful:

- `wp-db.php` is restored to the original WordPress version
- Git merge driver is uninstalled

The deletion failed, so I checked and found that:

- `vp_id` table is removed
- `wp-content/vpdb` folder is removed
- `wp-content/vpbackups` folder is created


However, I found these things remained:

- the `wp-config` file still contained `define('VP_ENVIRONMENT', 'live');`
- `wp-config.common.php` still exists
- `vp_commit_frequently_written_entities_hourly` cron event still exists

Is there anything else I need to manually remove? What are the user meta you mentioned?

**Comment by borekb** [comment]
The usermeta is called `vp_show_welcome_panel`, see [`VersionPressOptions.php`](https://github.com/versionpress/versionpress/blob/bd898332523ec68097315f3de7cf2e385537d208/plugins/versionpress/src/Initialization/VersionPressOptions.php).

**Comment by pavelevap** [comment]
Hi @meadows19, I tried to reproduce it with my Dreamhost account (PHP 7) and I did not experienced similar error message.

- `wp-config.php` file does not contain `define('VP_ENVIRONMENT', 'live');` but link to `wp-config.common.php` file is still at the beginning:
```
// Configuration common to all environments
include_once __DIR__ . '/wp-config.common.php';
```

- Also `wp-config.common.php` still exists (required by `wp-config.php` file).
- `vp_commit_frequently_written_entities_hourly` cron event also still exists.
- `.gitignore` file still exists.

All of them are probably general VP issues which should be further investigated and removed.

Error message is probably related to constant in `wp-config.php` file which was not removed and method [removeVersionPressConstants](https://github.com/versionpress/versionpress/blob/master/plugins/versionpress/uninstall.php#L47) failed. I am not sure why, but there are some ideas:

- File permissions for `wp-config.php` file. Did you manually updated this file after VP activation?
- Specific changes of `wp-config.php` file. Did you add any specific constants?
- Did you try to check `error.log` if there is any clue?

But it can be also something else, error message is triggered directly by WordPress ([here](https://github.com/WordPress/WordPress/blob/222ee437fef1688245c3d0d2bfa050a06262f3eb/wp-admin/js/updates.js#L1619)).

Could you please try following?

- Make a clean WP installation, install VP, activate, make some changes and then delete. Is this error reproducible in this way?
- Could you share your `wp-config.php` file (without credentials) if you made any custom changes?

**Comment by borekb** [comment]
@meadows19 I'm closing this to clear up the issues, if you have further questions feel free to reopen or create a new issue. Thanks.

**Comment by meadows19** [comment]
Sorry about the delay in replying.

@pavelevap I have two wordpress installations on the same server.

One is the live site, and one is the staging site. Both are nearly exactly the same. Both were running versionpress with over 100 pages in changes. Then I removed versionpress from the live site (and saw this error) but kept it on the staging site.

If you like, I can give you the credentials to the staging site, and you can uninstall versionpress or play about with anything or check any files. I'm pretty sure that the error will be reproduced the same. It'snot a problem if you change anything, because when you are finished, I will restore from a server snapshot/backup.

**Comment by pavelevap** [comment]
Hi @meadows19, it would be great, I can test it to see this error in action. You can contact me at pavelevap(at)gmail.com.
