### ISSUE TITLE
VersionPress Dashboard in WP is stalled

### ISSUE THREAD

**Issue by Guddina-tim** [versionpress/support#9]
Posting this from a previous email conversation to bring the solution here.

When I log into the WP dashboard and go to VersionPress (fresh install), I only see a grey/white bar with scrolling diagonal loading lines flowing across the page. Nothing else shows.

However, VP is correctly pushing commits to my Git Repo.

When I open my console, I see this error relating to ../versionpress/admin/public/gui/app.js  -

-----

> Uncaught TypeError: Cannot read property 'body' of undefined(anonymous function) @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:396f.callback @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:403(anonymous function) @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:403n.emit @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:404n.onreadystatechange @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:404
> app.js?ver=86d5c1b14dc6690ddae39025e301b906:396 Uncaught TypeError: Cannot read property 'body' of undefined(anonymous function) @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:396f.callback @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:403(anonymous function) @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:403n.emit @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:404n.onreadystatechange @ app.js?ver=86d5c1b14dc6690ddae39025e301b906:404

**Comment by borekb** [comment]
Hi, which versions of WordPress and VersionPress are you on?

**Comment by Guddina-tim** [comment]
WordPress 4.0 and VP 2.2

**Comment by borekb** [comment]
We can reproduce it on 4.0 and VP 2.2 as well. Would there be any chance for you to upgrade to the current release of WordPress?

**Comment by borekb** [comment]
This BTW confirms that VersionPress 2.2 does not work on 4.0, as noted in [system requirements](http://docs.versionpress.net/en/release-notes/2.2#system-requirements). We thought it might work on 3.9+ but there's no `wp_json_encode()` function before WP 4.1 which is required by VersionPress 2.2.

Closing this for now, let us know if we can help with anything else.
