### ISSUE TITLE
loading page 

### ISSUE THREAD

**Issue by omarghamraoui** [versionpress/support#90]
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 3.0.2
- WordPress version: 4.7.3
- OS, webserver, PHP: Linux, apache: 2.4.18, PHP 5.6
- Git version: 2.7.4

When I activated versionPress i got this error and the page stay loading 
![1](https://cloud.githubusercontent.com/assets/11414466/23799647/91b844a2-05a9-11e7-90e7-e60358fe05c4.png)

Best regards
You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

**Comment by borekb** [comment]
@omarghamraoui Hi, there are some permission issues on your hosting but even if you got it sorted, VersionPress wouldn't work well with so many plugins. It's currently in development and this is a [known limitation](https://docs.versionpress.net/en/getting-started/about-eap), sorry about that.
