### ISSUE TITLE
Undo/Roll back to this is not visible

### ISSUE THREAD

**Issue by Amadzahid** [versionpress/support#92]
Hi,
  I install VersionPress on my site & it's tracking good. The only problem I face is its not showing undo/Roll back option. I tried to figure out but didn't succeeded. 

Can you please help me out from this? As I tried to figure out from last 3 to 4 days. Thanks

Regards,
Amad Zahid

**Comment by borekb** [comment]
Hi @Amadzahid, could you please post your [system info](https://docs.versionpress.net/en/troubleshooting/system-info-page) and a screenshot? Thanks.

**Comment by borekb** [comment]
As the dialog says, you have uncommitted changes in the site which is probably due to some 3rd party plugins that are not supported yet (see [Early Access limitations](https://docs.versionpress.net/en/getting-started/about-eap)). VersionPress is unfortunately not recommended yet for such sites.
