### ISSUE TITLE
Version press empty of 500

### ISSUE THREAD

**Issue by wokadeh** [versionpress/support#94]
VersionPress version 3/4
WordPress version 4.7.4
php 7.0.15-0 ubuntu0.16.04.4
git version 2.7.4

Hello everyone,

I got the problem that my versionpress is not tracking anything anymore since about one month. I can see the last commits being pushed, which is but so much of a help:

`VP-Action: option/create/updraft_jobdata_4485d4828d3f

VP-Action: option/create/updraftplus_locked_fd

VP-Action: option/edit/updraft_backup_history

VP-Action: option/delete/updraft_jobdata_4485d4828d3f

VP-Action: option/edit/updraft_jobdata_4485d4828d3f

VP-Action: option/edit/updraft_last_backup

VP-Action: option/edit/updraft_last_scheduled_fd

VP-Action: option/edit/updraft_lastmessage

VP-Action: option/edit/updraftplus_last_lock_time_fd

VP-Action: option/edit/updraftplus_semaphore_fd

VP-Action: option/edit/updraftplus_unlocked_fd

X-VP-Version: 3.0.2
X-VP-Environment: default`

The versionpress page remains empty like described here: https://docs.versionpress.net/en/troubleshooting/ui-not-loading

I setup the page on my local device in a docker instance as well as on a public webserver. Both show an empty versionpress page. The git remote is at gitlab and they both shall share that remote to be a dev and a prod environment. 

I went on to update my local instance versionpress from 3.0.2 to 4 and got no change. The odd thing was that for the first time on connecting with the repository after reactivation it displayed and undefined error on the connection to the remote. But there is none shown in the Network Console BUT an 500 Internal Server Error on GET of commits. 

On git in the terminal of Ubuntu I can git pull and push freely.

I am happy for your help

Best regards
Wokadeh

**Comment by borekb** [comment]
Hi @wokadeh, the problem is probably with your plugins, VersionPress currently doesn't support them, sorry. We're working to resolve that in v4 and beyond.

**Comment by wokadeh** [comment]
Okay, thank you very much for your answer. I'm looking forward to the solution since VersionPress is such an important tool actually for everyone using WordPress.

**Comment by wokadeh** [comment]
Sorry to reopen, but I cannot re-establish my site to the state were versionpress was working.

First I tried to deactivate plugin after plugin thinking at one point vp must be working again. I also tried deactivating and activating vp again to motivate it to work again. Without success.

Second I took a totally new docker instance, reinstalled the whole wordpress stuff, installed vp, then I could clone my repo to the www/html folder. I had my running wordpress and versionpress. Now again any commit or checkout to another branch again leads to vp not working anymore. And still I can't figure out what's the source. There are no logs in the wp-content/versionpress/log folder.
The last git commit messages provide also no information I can work with. :-(

**Comment by borekb** [comment]
So clean WP + VersionPress worked for some period of time and then stopped, or did it never work?

**Comment by wokadeh** [comment]
Yes, clean WP + VP works. It stopped working one month ago and I cannot distinguish from the last commit what was the breaking point. The commit message is listed in the first post. 

You said it was probably the fault of incompatibility with another plugin. However, deactivating all of the other plugins did not help. What kind of refresh would be needed?

**Comment by borekb** [comment]
It will be hard to retrospectively debug this but when you try a fresh installation now in your Docker container, does it work? Does it stop working after some time or after some plugin installation?

**Comment by wokadeh** [comment]
Yes, then it works.
I developed my site a lot further with content and different plugins and have production version on a web host and a staging version on my local system running in a docker container. The changes of development were committed to my git repository with versionpress. Everything was working perfectly until I noticed that nothing ist tracked anymore. 
So when I do a fresh installation on my staging system I try to checkout the latest commits in my repository in hope to return to the latest working state to see what the differences are to my not-tracked-production system to hopefully find the issue and get it tracked again...

**Comment by borekb** [comment]
Unless you find the root cause of why your production environment stopped tracking changes, I don't think you'll have much luck :(

**Comment by wokadeh** [comment]
Interesting, it is possible to pull the latest version from the Live system via `wp vp pull` even when the web service cannot be displayed! :-) :-)
See therefore also #95

**Comment by borekb** [comment]
`wp vp pull` works on the Git level, it doesn't really care whether the live site is working or not. But if it was broken, pulling to another environment will probably result in a broken site as well. But it's worth trying :)

**Comment by wokadeh** [comment]
No, everything turned out to be great! I was working on terminal layer, synchronized my local and remote system frequently and now even the web interface of versionpress is available again! Hurrraaayyy! :-) :-)
