### ISSUE TITLE
File system permissions in existing repo with custom folder structure

### ISSUE THREAD

**Issue by markchitty** [versionpress/support#96]
Hi,

First off, epic project. Huge thanks 😃 

To business - got a permissions problem on install 😢 . Some special circumstances are at play:

* Pre-existing git repo
* Custom WP folder structure ([Bedrock](http://roots.io/bedrock))
* VVV virtual machine dev env, running on OSX host
* Project root mapped into vm so that I can use all my local dev tools, git client etc on my host machine, but still have the file changes appear automatically in the VVV dev env
    * VVV file mapping config is
```
config.vm.synced_folder \"$REPO_ROOT\",
                        \"/home/vagrant/project_root/\",
                        :owner => \"www-data\",
                        :mount_options => [ \"dmode=775\", \"fmode=774\" ]
```

I followed the custom folder structure instructions, modified my wp-config.php, and lo the VP plugin installed and activated fine. But once it was complete I was left in a *strange* situation.

* `$ git status` on the vm showed everything committed to the repo, all good to go
* `$ git status` on the host machine however showed *all* repo files modified. Huh?

Turns out the modifications were down to permissions:

```
host$ ls -la readme.md
-rw-r--r--@ ... readme.md

vvv$ ls -la readme.md
-rwxrwxr-- ... readme.md

vvv$ git diff HEAD^ HEAD -- readme.md
diff --git a/readme.md b/readme.md
old mode 100644
new mode 100755
```

Two things were weird:
1. File permissions in the mapped folder on the host machine didn't match the same file permissions on the guest - 644 != 774
1. File permissions on the guest machine didn't match what git said they were - 774 != 755

4 hours of head scratching later I have narrowed down this weirdness to:
1. VirtualBox doesn't allow changing owner/permissions for files in synced folders (http://stackoverflow.com/a/25831658). If you run `chmod` from the guest machine, the synced file permissions *don't* change on the guest machine but *do* change on the host machine. This explains the file permission differences between guest and host.
1. The only file mode Git tracks is the user executable bit (http://stackoverflow.com/a/34546706). So `chmod 7xx` with any (legitimate) values of x will result in `new mode 100755` in git-land.

Soooooo, whilst this explained a lot, I was still left wondering why this (attempted) permission change happened across my entire repo in the first place. I searched for `chmod` in the VP codebase and found it only in two files - *MergeDriverInstaller.php* and *FileSystem.php*. I suspect I may have been hit by something similar to what is mentioned in issue [#945](https://github.com/versionpress/versionpress/issues/945), specifically by @pavelevap . It looks like possiblyFixGitPermissions is still changing file permissions across the entire repo. This is probably a consequence of either a) my pre-existing repo, or b) my custom WP folder structure, or both.

Your thoughts?

---

After a bit more head scratching and a slight intake of breath I fixed the the 'modified' file permissions on the host machine by resetting to the 'Activated VersionPress' commit:

```
$ git reset --hard HEAD
```

Sorted. Phew.

BTW, I know a bunch of this is the consequence of my VVV dev env, not VersionPress per se, but I thought I'd include it here as VVV is a common WP dev tool and others may hit a similar issue.

---

From system info page (love that you have a system info page :)

```
  'wordpress-version' => '4.7.4',
  'versionpress-version' => '4.0-alpha1',
  'operating-system' => 'Linux vvv 3.13.0-68-generic #111-Ubuntu SMP ...,
  'php-version' => '7.0.19-1+deb.sury.org~trusty+1',
  'php-sapi' => 'fpm-fcgi',
  'git-version' => '1.9.1',
  'git-full-path' => '/usr/bin/git
```

**Comment by borekb** [comment]
Hey @markchitty, what a report :) I don't think that the `possiblyFixGitPermissions()` caused that as it [immediately returns](https://github.com/versionpress/versionpress/blob/c54b38994576408e2c92de058a308a314b25c7fe/plugins/versionpress/src/Utils/FileSystem.php#L132-L134) on UNIX-like systems. Not sure what could have caused it to be honest but it's good that you got it resolved!

**Comment by markchitty** [comment]
Hi @borekb.

Okay, I figured out some more... and it's nothing to do with VersionPress (directly) - the different guest vs host file permissions of the repo folder is the root cause of everything.

In my normal day-to-day WordPress developing life, I only ever run `$ git commit` from my host OSX machine. This has full file permission control over the repo root, so standard file permissions (644) propagate into the git index as normal.

Then VersionPress comes along, and performs the first ever `$ git commit` from the guest vm. 

In the guest, the repo root file permissions are pre-set to 774 by the VVV file mapping (`config.vm.synced_folder ... :mount_options => [ \"dmode=775\", \"fmode=774\" ]`), and they're not changeable. The git index says the repo file permissions should be 644, but the working directory permissions are now 774. 644 != 774 so git goes "Aha, all these files are different", and they get schlurped up into the first VersionPress commit. Confusion ensues.

If I'd ever done a commit from the guest vm, I'd have hit this problem all by myself, so I feel VersionPress is blameless here 😄 . 

One of those days - productivity: zero, learning: ten.

**Comment by markchitty** [comment]
Ah yes, and for any other poor soul following this merry tale, the solution to this VVV synced repo root file permissions shenanigans is to tell git to ignore file permission differences:

```
git config core.fileMode false
```

(more about this on [stackoverflow](http://stackoverflow.com/a/1580644)).

It's a good idea to do this *before* you activate VersionPress as then you won't have to reset all the affected files in a new commit after the first VersionPress commit.

**Comment by borekb** [comment]
That's excellent info, permissions are always tricky so this will certainly help other people. I've "starred" this ticket, thanks!
