### ISSUE TITLE
Can't activate in admin console after activating plugin

### ISSUE THREAD

**Issue by Techgeekster** [versionpress/support#98]
- VersionPress version:  4.0
- WordPress version: 4.8
- OS, webserver, PHP: Windows 10, HostGator, 5.6.30
- Git version: 2.10.2.windows.1

After I installed the plugin and clicked activate, I navigated to the VersionPress admin console on the left-hand side to click the active button to finish installing.  However, the activate button is greyed out.

**Comment by pavelevap** [comment]
Hi @Techgeekster,

so you are stuck on [this](https://docs.versionpress.net/en/getting-started/installation-uninstallation) page and it is not possible to activate VersionPress? All requirements are checked? Could you please paste here full system info (link at the bottom of activation page)?

**Comment by Techgeekster** [comment]
I'm on the second part of the two step process.

I placed my system info in my previous post, is there something I'm missing?

**Comment by pavelevap** [comment]
So, you see something like this (only activation button is not active)?

https://docs.versionpress.net/media/requirements-checker.png

All requirements checks passed? Could you please upload screenshot of this page?

There is also detailed [system info page](https://docs.versionpress.net/en/troubleshooting/system-info-page), could you paste your details here?

Thank you!

**Comment by kalich5** [comment]
I have same problem. 

WordPress 4.8
VersionPress 4.0-alpha1 

![chyba](https://user-images.githubusercontent.com/8988898/27379223-c86fa19e-567a-11e7-907c-1b803fbcfd6f.png)

**Comment by Techgeekster** [comment]
Ooooooh, okay, so my Git version on my windows computer is the latest version but I don't have Git higher than 1.9 installed on hostGator.
I tried figuring out how to install git on hostGator but I'm not having much luck. I know this might be out of your line of expertise, but hostGator chat was no help, they just told me it was possible but they couldn't tell me how.  Do you know how to install/update git on a hostGator server?  I've been googling for hours and haven't been able to figure this out.  I'm pretty new to hosting a website myself.

**Comment by Techgeekster** [comment]
Just found out from my hosting service that they cannot update the server because I'm on a shared server.  Guess I can't use VersionPress.  This makes me very sad :(

**Comment by pavelevap** [comment]
Hi @kalich5 :-)

System [info page](https://docs.versionpress.net/en/troubleshooting/system-info-page) is available? Could you please look into your error log and search for related PHP errors? I remember, I saw this problem somewhere, but I am not sure how it was caused.

@Techgeekster: Sorry, but VersionPress is Git-based tool, so it is not possible to use it without Git. You will not be able to install Git on shared server, the only way is change your host, see related [page](https://docs.versionpress.net/en/integrations/hosts).

**Comment by kalich5** [comment]
Info page is not available. Solved on FB, it looks like a bug in VersionPress

**Comment by borekb** [comment]
Related [Facebook discussion](https://www.facebook.com/photo.php?fbid=10211283798503754&set=o.818428044850028&type=1&theater).

**Comment by pavelevap** [comment]
@kalich5: I was able to reproduce, thank you!

https://github.com/versionpress/versionpress/issues/1244

**Comment by twentyfortysix** [comment]
same here.
the page is "blank" WP 4.9.6, VP 4.0-beta, no errors WP_debug on, PHP errors on

I found out that the proc_open is not available on my hosting.. I know it is required.. but the VP should check the dependencies first and let me know right?

**Comment by surabhimodak** [comment]
Hi, I am also facing the same issue where the activation button is greyed out. What should I do?  Can someone help me please? I have installed wordpress on Google Cloud Platform. 

Help needed asap. 
Thank you.
